// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansNKoUnjoined_700Bold = require('./NotoSansNKoUnjoined_700Bold.ttf');
