// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const NovaSquare_400Regular = require('./400Regular/NovaSquare_400Regular.ttf');
