// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansGunjalaGondi_500Medium = require('./NotoSansGunjalaGondi_500Medium.ttf');
