/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const NotoSansGunjalaGondi_500Medium = require('./NotoSansGunjalaGondi_500Medium.ttf');
