/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export const __fontFamilyName__ = 'Snippet';
export const __fontFamilyVersion__ = 6;

export const Snippet_Regular400 = require('./8cc4ae1951b9917cd740fe17346eee27c893d200ad251063c1aa3c48b6e02682.ttf');
