// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const TitilliumWeb_400Regular_Italic = require('./TitilliumWeb_400Regular_Italic.ttf');
