/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const RibeyeMarrow_Regular400 = require('./c246f9f2e382d8da82319762b401df8a1426fa767b74d168f0d1abca33fdd43d.ttf');
