// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const FunnelDisplay_300Light: number;
export const FunnelDisplay_400Regular: number;
export const FunnelDisplay_500Medium: number;
export const FunnelDisplay_600SemiBold: number;
export const FunnelDisplay_700Bold: number;
export const FunnelDisplay_800ExtraBold: number;
