/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const IMFellGreatPrimer_Regular400 = require('./fede2a25cf42680231c7bfb90da7306e0962092c8e1074fbfc44ef59289257ec.ttf');
export const IMFellGreatPrimer_Regular400_Italic = require('./020c8f65ef327b827d6e28ca2e4be8f019b4a81075f1c7c00a53993664b41b93.ttf');
