/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const IMFellGreatPrimer_400Regular = require('./IMFellGreatPrimer_400Regular.ttf');
export const IMFellGreatPrimer_400Regular_Italic = require('./IMFellGreatPrimer_400Regular_Italic.ttf');
