// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const PlaywriteESDeco_100Thin: number;
export const PlaywriteESDeco_200ExtraLight: number;
export const PlaywriteESDeco_300Light: number;
export const PlaywriteESDeco_400Regular: number;
