// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const GoogleSans_400Regular = require('./GoogleSans_400Regular.ttf');
