// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export const __metadata__: any;
export const CascadiaMono_200ExtraLight: number;
export const CascadiaMono_300Light: number;
export const CascadiaMono_400Regular: number;
export const CascadiaMono_500Medium: number;
export const CascadiaMono_600SemiBold: number;
export const CascadiaMono_700Bold: number;
export const CascadiaMono_200ExtraLight_Italic: number;
export const CascadiaMono_300Light_Italic: number;
export const CascadiaMono_400Regular_Italic: number;
export const CascadiaMono_500Medium_Italic: number;
export const CascadiaMono_600SemiBold_Italic: number;
export const CascadiaMono_700Bold_Italic: number;
