// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansKayahLi_600SemiBold = require('./NotoSansKayahLi_600SemiBold.ttf');
