/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const KaiseiHarunoUmi_400Regular = require('./KaiseiHarunoUmi_400Regular.ttf');
export const KaiseiHarunoUmi_500Medium = require('./KaiseiHarunoUmi_500Medium.ttf');
export const KaiseiHarunoUmi_700Bold = require('./KaiseiHarunoUmi_700Bold.ttf');
