// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Ysabeau_200ExtraLight = require('./Ysabeau_200ExtraLight.ttf');
