/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Puritan_Regular400: number;
export const Puritan_Regular400_Italic: number;
export const Puritan_Bold700: number;
export const Puritan_Bold700_Italic: number;
