// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const NotoSansTamil_100Thin = require('./100Thin/NotoSansTamil_100Thin.ttf');
export const NotoSansTamil_200ExtraLight = require('./200ExtraLight/NotoSansTamil_200ExtraLight.ttf');
export const NotoSansTamil_300Light = require('./300Light/NotoSansTamil_300Light.ttf');
export const NotoSansTamil_400Regular = require('./400Regular/NotoSansTamil_400Regular.ttf');
export const NotoSansTamil_500Medium = require('./500Medium/NotoSansTamil_500Medium.ttf');
export const NotoSansTamil_600SemiBold = require('./600SemiBold/NotoSansTamil_600SemiBold.ttf');
export const NotoSansTamil_700Bold = require('./700Bold/NotoSansTamil_700Bold.ttf');
export const NotoSansTamil_800ExtraBold = require('./800ExtraBold/NotoSansTamil_800ExtraBold.ttf');
export const NotoSansTamil_900Black = require('./900Black/NotoSansTamil_900Black.ttf');
