/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const NotoSansTamil_100Thin = require('./NotoSansTamil_100Thin.ttf');
export const NotoSansTamil_200ExtraLight = require('./NotoSansTamil_200ExtraLight.ttf');
export const NotoSansTamil_300Light = require('./NotoSansTamil_300Light.ttf');
export const NotoSansTamil_400Regular = require('./NotoSansTamil_400Regular.ttf');
export const NotoSansTamil_500Medium = require('./NotoSansTamil_500Medium.ttf');
export const NotoSansTamil_600SemiBold = require('./NotoSansTamil_600SemiBold.ttf');
export const NotoSansTamil_700Bold = require('./NotoSansTamil_700Bold.ttf');
export const NotoSansTamil_800ExtraBold = require('./NotoSansTamil_800ExtraBold.ttf');
export const NotoSansTamil_900Black = require('./NotoSansTamil_900Black.ttf');
