// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const RobotoMono_100Thin = require('./100Thin/RobotoMono_100Thin.ttf');
export const RobotoMono_200ExtraLight = require('./200ExtraLight/RobotoMono_200ExtraLight.ttf');
export const RobotoMono_300Light = require('./300Light/RobotoMono_300Light.ttf');
export const RobotoMono_400Regular = require('./400Regular/RobotoMono_400Regular.ttf');
export const RobotoMono_500Medium = require('./500Medium/RobotoMono_500Medium.ttf');
export const RobotoMono_600SemiBold = require('./600SemiBold/RobotoMono_600SemiBold.ttf');
export const RobotoMono_700Bold = require('./700Bold/RobotoMono_700Bold.ttf');
export const RobotoMono_100Thin_Italic = require('./100Thin_Italic/RobotoMono_100Thin_Italic.ttf');
export const RobotoMono_200ExtraLight_Italic = require('./200ExtraLight_Italic/RobotoMono_200ExtraLight_Italic.ttf');
export const RobotoMono_300Light_Italic = require('./300Light_Italic/RobotoMono_300Light_Italic.ttf');
export const RobotoMono_400Regular_Italic = require('./400Regular_Italic/RobotoMono_400Regular_Italic.ttf');
export const RobotoMono_500Medium_Italic = require('./500Medium_Italic/RobotoMono_500Medium_Italic.ttf');
export const RobotoMono_600SemiBold_Italic = require('./600SemiBold_Italic/RobotoMono_600SemiBold_Italic.ttf');
export const RobotoMono_700Bold_Italic = require('./700Bold_Italic/RobotoMono_700Bold_Italic.ttf');
