// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const SansitaSwashed_900Black = require('./SansitaSwashed_900Black.ttf');
