// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const AlegreyaSC_400Regular = require('./AlegreyaSC_400Regular.ttf');
