/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const EduAUVICWANTPre_400Regular = require('./EduAUVICWANTPre_400Regular.ttf');
export const EduAUVICWANTPre_500Medium = require('./EduAUVICWANTPre_500Medium.ttf');
export const EduAUVICWANTPre_600SemiBold = require('./EduAUVICWANTPre_600SemiBold.ttf');
export const EduAUVICWANTPre_700Bold = require('./EduAUVICWANTPre_700Bold.ttf');
