// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Butcherman_400Regular = require('./Butcherman_400Regular.ttf');
