// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaypenSansDeva_700Bold = require('./PlaypenSansDeva_700Bold.ttf');
