// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const JosefinSlab_200ExtraLight = require('./JosefinSlab_200ExtraLight.ttf');
