/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const Content_400Regular = require('./Content_400Regular.ttf');
export const Content_700Bold = require('./Content_700Bold.ttf');
