/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Oxygen_Light300: number;
export const Oxygen_Regular400: number;
export const Oxygen_Bold700: number;
