/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const RedactedScript_300Light: number;
export const RedactedScript_400Regular: number;
export const RedactedScript_700Bold: number;
