/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Palanquin_Thin100: number;
export const Palanquin_ExtraLight200: number;
export const Palanquin_Light300: number;
export const Palanquin_Regular400: number;
export const Palanquin_Medium500: number;
export const Palanquin_SemiBold600: number;
export const Palanquin_Bold700: number;
