/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const Palanquin_100Thin = require('./Palanquin_100Thin.ttf');
export const Palanquin_200ExtraLight = require('./Palanquin_200ExtraLight.ttf');
export const Palanquin_300Light = require('./Palanquin_300Light.ttf');
export const Palanquin_400Regular = require('./Palanquin_400Regular.ttf');
export const Palanquin_500Medium = require('./Palanquin_500Medium.ttf');
export const Palanquin_600SemiBold = require('./Palanquin_600SemiBold.ttf');
export const Palanquin_700Bold = require('./Palanquin_700Bold.ttf');
