/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const IBMPlexSansCondensed_400Regular_Italic = require('./IBMPlexSansCondensed_400Regular_Italic.ttf');
