// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const KarlaTamilUpright_400Regular = require('./KarlaTamilUpright_400Regular.ttf');
