/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const NotoSansTangsa_400Regular: number;
export const NotoSansTangsa_500Medium: number;
export const NotoSansTangsa_600SemiBold: number;
export const NotoSansTangsa_700Bold: number;
