// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Manjari_100Thin = require('./100Thin/Manjari_100Thin.ttf');
export const Manjari_400Regular = require('./400Regular/Manjari_400Regular.ttf');
export const Manjari_700Bold = require('./700Bold/Manjari_700Bold.ttf');
