/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metdata__: Any;
export const Manjari_100Thin: number;
export const Manjari_400Regular: number;
export const Manjari_700Bold: number;
