// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const BalooPaaji2_400Regular = require('./400Regular/BalooPaaji2_400Regular.ttf');
export const BalooPaaji2_500Medium = require('./500Medium/BalooPaaji2_500Medium.ttf');
export const BalooPaaji2_600SemiBold = require('./600SemiBold/BalooPaaji2_600SemiBold.ttf');
export const BalooPaaji2_700Bold = require('./700Bold/BalooPaaji2_700Bold.ttf');
export const BalooPaaji2_800ExtraBold = require('./800ExtraBold/BalooPaaji2_800ExtraBold.ttf');
