// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansCyproMinoan_400Regular = require('./NotoSansCyproMinoan_400Regular.ttf');
