// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const KoHo_200ExtraLight = require('./KoHo_200ExtraLight.ttf');
export const KoHo_200ExtraLight_Italic = require('./KoHo_200ExtraLight_Italic.ttf');
export const KoHo_300Light = require('./KoHo_300Light.ttf');
export const KoHo_300Light_Italic = require('./KoHo_300Light_Italic.ttf');
export const KoHo_400Regular = require('./KoHo_400Regular.ttf');
export const KoHo_400Regular_Italic = require('./KoHo_400Regular_Italic.ttf');
export const KoHo_500Medium = require('./KoHo_500Medium.ttf');
export const KoHo_500Medium_Italic = require('./KoHo_500Medium_Italic.ttf');
export const KoHo_600SemiBold = require('./KoHo_600SemiBold.ttf');
export const KoHo_600SemiBold_Italic = require('./KoHo_600SemiBold_Italic.ttf');
export const KoHo_700Bold = require('./KoHo_700Bold.ttf');
export const KoHo_700Bold_Italic = require('./KoHo_700Bold_Italic.ttf');
