/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const NotoSansGurmukhi_600SemiBold = require('./NotoSansGurmukhi_600SemiBold.ttf');
