/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const Rasa_300Light = require('./Rasa_300Light.ttf');
export const Rasa_400Regular = require('./Rasa_400Regular.ttf');
export const Rasa_500Medium = require('./Rasa_500Medium.ttf');
export const Rasa_600SemiBold = require('./Rasa_600SemiBold.ttf');
export const Rasa_700Bold = require('./Rasa_700Bold.ttf');
