/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metdata__: Any;
export const Rasa_300Light: number;
export const Rasa_400Regular: number;
export const Rasa_500Medium: number;
export const Rasa_600SemiBold: number;
export const Rasa_700Bold: number;
