/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Cutive_Regular400 = require('./2e0849ce3a9bd06c1d093ce26a2727da8b032430d3d39d191cfd79df0983d490.ttf');
