/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Tillana_Regular400: number;
export const Tillana_Medium500: number;
export const Tillana_SemiBold600: number;
export const Tillana_Bold700: number;
export const Tillana_ExtraBold800: number;
