// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Tillana_400Regular = require('./Tillana_400Regular.ttf');
export const Tillana_500Medium = require('./Tillana_500Medium.ttf');
export const Tillana_600SemiBold = require('./Tillana_600SemiBold.ttf');
export const Tillana_700Bold = require('./Tillana_700Bold.ttf');
export const Tillana_800ExtraBold = require('./Tillana_800ExtraBold.ttf');
