// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansDuployan_700Bold = require('./NotoSansDuployan_700Bold.ttf');
