// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const ScoutieSans_500Medium = require('./ScoutieSans_500Medium.ttf');
