// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoRashiHebrew_300Light = require('./NotoRashiHebrew_300Light.ttf');
