// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaywriteINGuides_400Regular = require('./PlaywriteINGuides_400Regular.ttf');
