// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const ElsieSwashCaps_400Regular = require('./400Regular/ElsieSwashCaps_400Regular.ttf');
export const ElsieSwashCaps_900Black = require('./900Black/ElsieSwashCaps_900Black.ttf');
