/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const ArimaMadurai_Thin100: number;
export const ArimaMadurai_ExtraLight200: number;
export const ArimaMadurai_Light300: number;
export const ArimaMadurai_Regular400: number;
export const ArimaMadurai_Medium500: number;
export const ArimaMadurai_Bold700: number;
export const ArimaMadurai_ExtraBold800: number;
export const ArimaMadurai_Black900: number;
