// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const font42dotSans_300Light: number;
export const font42dotSans_400Regular: number;
export const font42dotSans_500Medium: number;
export const font42dotSans_600SemiBold: number;
export const font42dotSans_700Bold: number;
export const font42dotSans_800ExtraBold: number;
