// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Chathura_100Thin = require('./Chathura_100Thin.ttf');
export const Chathura_300Light = require('./Chathura_300Light.ttf');
export const Chathura_400Regular = require('./Chathura_400Regular.ttf');
export const Chathura_700Bold = require('./Chathura_700Bold.ttf');
export const Chathura_800ExtraBold = require('./Chathura_800ExtraBold.ttf');
