// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const Alexandria_100Thin: number;
export const Alexandria_200ExtraLight: number;
export const Alexandria_300Light: number;
export const Alexandria_400Regular: number;
export const Alexandria_500Medium: number;
export const Alexandria_600SemiBold: number;
export const Alexandria_700Bold: number;
export const Alexandria_800ExtraBold: number;
export const Alexandria_900Black: number;
