// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const GermaniaOne_400Regular = require('./GermaniaOne_400Regular.ttf');
