/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteID_100Thin = require('./PlaywriteID_100Thin.ttf');
export const PlaywriteID_200ExtraLight = require('./PlaywriteID_200ExtraLight.ttf');
export const PlaywriteID_300Light = require('./PlaywriteID_300Light.ttf');
export const PlaywriteID_400Regular = require('./PlaywriteID_400Regular.ttf');
