/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metdata__: Any;
export const EBGaramond_400Regular: number;
export const EBGaramond_500Medium: number;
export const EBGaramond_600SemiBold: number;
export const EBGaramond_700Bold: number;
export const EBGaramond_800ExtraBold: number;
export const EBGaramond_400Regular_Italic: number;
export const EBGaramond_500Medium_Italic: number;
export const EBGaramond_600SemiBold_Italic: number;
export const EBGaramond_700Bold_Italic: number;
export const EBGaramond_800ExtraBold_Italic: number;
