// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSerifToto_400Regular = require('./NotoSerifToto_400Regular.ttf');
