// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaywriteNZBasicGuides_400Regular = require('./PlaywriteNZBasicGuides_400Regular.ttf');
