// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansEthiopic_500Medium = require('./NotoSansEthiopic_500Medium.ttf');
