// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const NotoSerifGeorgian_100Thin = require('./NotoSerifGeorgian_100Thin.ttf');
export const NotoSerifGeorgian_200ExtraLight = require('./NotoSerifGeorgian_200ExtraLight.ttf');
export const NotoSerifGeorgian_300Light = require('./NotoSerifGeorgian_300Light.ttf');
export const NotoSerifGeorgian_400Regular = require('./NotoSerifGeorgian_400Regular.ttf');
export const NotoSerifGeorgian_500Medium = require('./NotoSerifGeorgian_500Medium.ttf');
export const NotoSerifGeorgian_600SemiBold = require('./NotoSerifGeorgian_600SemiBold.ttf');
export const NotoSerifGeorgian_700Bold = require('./NotoSerifGeorgian_700Bold.ttf');
export const NotoSerifGeorgian_800ExtraBold = require('./NotoSerifGeorgian_800ExtraBold.ttf');
export const NotoSerifGeorgian_900Black = require('./NotoSerifGeorgian_900Black.ttf');
