/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const Stoke_300Light = require('./Stoke_300Light.ttf');
export const Stoke_400Regular = require('./Stoke_400Regular.ttf');
