// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Stoke_300Light = require('./Stoke_300Light.ttf');
export const Stoke_400Regular = require('./Stoke_400Regular.ttf');
