/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const NotoSerifLao_100Thin: number;
export const NotoSerifLao_200ExtraLight: number;
export const NotoSerifLao_300Light: number;
export const NotoSerifLao_400Regular: number;
export const NotoSerifLao_500Medium: number;
export const NotoSerifLao_600SemiBold: number;
export const NotoSerifLao_700Bold: number;
export const NotoSerifLao_800ExtraBold: number;
export const NotoSerifLao_900Black: number;
