// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const EduAUVICWANTDots_400Regular: number;
export const EduAUVICWANTDots_500Medium: number;
export const EduAUVICWANTDots_600SemiBold: number;
export const EduAUVICWANTDots_700Bold: number;
