/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const IBMPlexSansCondensed_700Bold_Italic = require('./IBMPlexSansCondensed_700Bold_Italic.ttf');
