// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const NotoSerifTamil_100Thin = require('./100Thin/NotoSerifTamil_100Thin.ttf');
export const NotoSerifTamil_200ExtraLight = require('./200ExtraLight/NotoSerifTamil_200ExtraLight.ttf');
export const NotoSerifTamil_300Light = require('./300Light/NotoSerifTamil_300Light.ttf');
export const NotoSerifTamil_400Regular = require('./400Regular/NotoSerifTamil_400Regular.ttf');
export const NotoSerifTamil_500Medium = require('./500Medium/NotoSerifTamil_500Medium.ttf');
export const NotoSerifTamil_600SemiBold = require('./600SemiBold/NotoSerifTamil_600SemiBold.ttf');
export const NotoSerifTamil_700Bold = require('./700Bold/NotoSerifTamil_700Bold.ttf');
export const NotoSerifTamil_800ExtraBold = require('./800ExtraBold/NotoSerifTamil_800ExtraBold.ttf');
export const NotoSerifTamil_900Black = require('./900Black/NotoSerifTamil_900Black.ttf');
export const NotoSerifTamil_100Thin_Italic = require('./100Thin_Italic/NotoSerifTamil_100Thin_Italic.ttf');
export const NotoSerifTamil_200ExtraLight_Italic = require('./200ExtraLight_Italic/NotoSerifTamil_200ExtraLight_Italic.ttf');
export const NotoSerifTamil_300Light_Italic = require('./300Light_Italic/NotoSerifTamil_300Light_Italic.ttf');
export const NotoSerifTamil_400Regular_Italic = require('./400Regular_Italic/NotoSerifTamil_400Regular_Italic.ttf');
export const NotoSerifTamil_500Medium_Italic = require('./500Medium_Italic/NotoSerifTamil_500Medium_Italic.ttf');
export const NotoSerifTamil_600SemiBold_Italic = require('./600SemiBold_Italic/NotoSerifTamil_600SemiBold_Italic.ttf');
export const NotoSerifTamil_700Bold_Italic = require('./700Bold_Italic/NotoSerifTamil_700Bold_Italic.ttf');
export const NotoSerifTamil_800ExtraBold_Italic = require('./800ExtraBold_Italic/NotoSerifTamil_800ExtraBold_Italic.ttf');
export const NotoSerifTamil_900Black_Italic = require('./900Black_Italic/NotoSerifTamil_900Black_Italic.ttf');
