// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Finlandica_600SemiBold = require('./Finlandica_600SemiBold.ttf');
