// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const ZenKakuGothicNew_300Light = require('./ZenKakuGothicNew_300Light.ttf');
export const ZenKakuGothicNew_400Regular = require('./ZenKakuGothicNew_400Regular.ttf');
export const ZenKakuGothicNew_500Medium = require('./ZenKakuGothicNew_500Medium.ttf');
export const ZenKakuGothicNew_700Bold = require('./ZenKakuGothicNew_700Bold.ttf');
export const ZenKakuGothicNew_900Black = require('./ZenKakuGothicNew_900Black.ttf');
