/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const ZenKakuGothicNew_300Light = require('./ZenKakuGothicNew_300Light.ttf');
export const ZenKakuGothicNew_400Regular = require('./ZenKakuGothicNew_400Regular.ttf');
export const ZenKakuGothicNew_500Medium = require('./ZenKakuGothicNew_500Medium.ttf');
export const ZenKakuGothicNew_700Bold = require('./ZenKakuGothicNew_700Bold.ttf');
export const ZenKakuGothicNew_900Black = require('./ZenKakuGothicNew_900Black.ttf');
