// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const DancingScript_500Medium = require('./DancingScript_500Medium.ttf');
