// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaywriteDKUloopet_400Regular = require('./PlaywriteDKUloopet_400Regular.ttf');
