/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const ShantellSans_300Light_Italic = require('./ShantellSans_300Light_Italic.ttf');
