// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const PlaywriteAUSAGuides_400Regular = require('./PlaywriteAUSAGuides_400Regular.ttf');
