/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const Simonetta_400Regular: number;
export const Simonetta_400Regular_Italic: number;
export const Simonetta_900Black: number;
export const Simonetta_900Black_Italic: number;
