// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Glegoo_400Regular = require('./Glegoo_400Regular.ttf');
export const Glegoo_700Bold = require('./Glegoo_700Bold.ttf');
