/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const Karantina_300Light = require('./Karantina_300Light.ttf');
export const Karantina_400Regular = require('./Karantina_400Regular.ttf');
export const Karantina_700Bold = require('./Karantina_700Bold.ttf');
