// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const KalniaGlaze_100Thin = require('./100Thin/KalniaGlaze_100Thin.ttf');
export const KalniaGlaze_200ExtraLight = require('./200ExtraLight/KalniaGlaze_200ExtraLight.ttf');
export const KalniaGlaze_300Light = require('./300Light/KalniaGlaze_300Light.ttf');
export const KalniaGlaze_400Regular = require('./400Regular/KalniaGlaze_400Regular.ttf');
export const KalniaGlaze_500Medium = require('./500Medium/KalniaGlaze_500Medium.ttf');
export const KalniaGlaze_600SemiBold = require('./600SemiBold/KalniaGlaze_600SemiBold.ttf');
export const KalniaGlaze_700Bold = require('./700Bold/KalniaGlaze_700Bold.ttf');
