/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const NotoSerifKannada_800ExtraBold = require('./NotoSerifKannada_800ExtraBold.ttf');
