// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const MonsieurLaDoulaise_400Regular = require('./MonsieurLaDoulaise_400Regular.ttf');
