/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const ProtestRevolution_400Regular = require('./ProtestRevolution_400Regular.ttf');
