/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const NotoSansCherokee_100Thin: number;
export const NotoSansCherokee_200ExtraLight: number;
export const NotoSansCherokee_300Light: number;
export const NotoSansCherokee_400Regular: number;
export const NotoSansCherokee_500Medium: number;
export const NotoSansCherokee_600SemiBold: number;
export const NotoSansCherokee_700Bold: number;
export const NotoSansCherokee_800ExtraBold: number;
export const NotoSansCherokee_900Black: number;
