/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const UnicaOne_Regular400 = require('./5616e05bc01af9a3a0c6ab46088658b8dfa74ac2b709df893baaefaa711889ed.ttf');
