/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const NotoSansGurmukhi_800ExtraBold = require('./NotoSansGurmukhi_800ExtraBold.ttf');
