/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const Mukta_200ExtraLight = require('./Mukta_200ExtraLight.ttf');
export const Mukta_300Light = require('./Mukta_300Light.ttf');
export const Mukta_400Regular = require('./Mukta_400Regular.ttf');
export const Mukta_500Medium = require('./Mukta_500Medium.ttf');
export const Mukta_600SemiBold = require('./Mukta_600SemiBold.ttf');
export const Mukta_700Bold = require('./Mukta_700Bold.ttf');
export const Mukta_800ExtraBold = require('./Mukta_800ExtraBold.ttf');
