// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Mukta_200ExtraLight = require('./200ExtraLight/Mukta_200ExtraLight.ttf');
export const Mukta_300Light = require('./300Light/Mukta_300Light.ttf');
export const Mukta_400Regular = require('./400Regular/Mukta_400Regular.ttf');
export const Mukta_500Medium = require('./500Medium/Mukta_500Medium.ttf');
export const Mukta_600SemiBold = require('./600SemiBold/Mukta_600SemiBold.ttf');
export const Mukta_700Bold = require('./700Bold/Mukta_700Bold.ttf');
export const Mukta_800ExtraBold = require('./800ExtraBold/Mukta_800ExtraBold.ttf');
