/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export const __fontFamilyName__ = 'Poor Story';
export const __fontFamilyVersion__ = 4;

export const PoorStory_Regular400 = require('./a915416edf6eea5c6eb16e098a45ee910564e4d15dfba8a3136e293e2f2d8a67.ttf');
