// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const Grenze_100Thin: number;
export const Grenze_100Thin_Italic: number;
export const Grenze_200ExtraLight: number;
export const Grenze_200ExtraLight_Italic: number;
export const Grenze_300Light: number;
export const Grenze_300Light_Italic: number;
export const Grenze_400Regular: number;
export const Grenze_400Regular_Italic: number;
export const Grenze_500Medium: number;
export const Grenze_500Medium_Italic: number;
export const Grenze_600SemiBold: number;
export const Grenze_600SemiBold_Italic: number;
export const Grenze_700Bold: number;
export const Grenze_700Bold_Italic: number;
export const Grenze_800ExtraBold: number;
export const Grenze_800ExtraBold_Italic: number;
export const Grenze_900Black: number;
export const Grenze_900Black_Italic: number;
