// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const EduAUVICWANTDots_600SemiBold = require('./EduAUVICWANTDots_600SemiBold.ttf');
