// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const FiraSansExtraCondensed_100Thin = require('./FiraSansExtraCondensed_100Thin.ttf');
export const FiraSansExtraCondensed_100Thin_Italic = require('./FiraSansExtraCondensed_100Thin_Italic.ttf');
export const FiraSansExtraCondensed_200ExtraLight = require('./FiraSansExtraCondensed_200ExtraLight.ttf');
export const FiraSansExtraCondensed_200ExtraLight_Italic = require('./FiraSansExtraCondensed_200ExtraLight_Italic.ttf');
export const FiraSansExtraCondensed_300Light = require('./FiraSansExtraCondensed_300Light.ttf');
export const FiraSansExtraCondensed_300Light_Italic = require('./FiraSansExtraCondensed_300Light_Italic.ttf');
export const FiraSansExtraCondensed_400Regular = require('./FiraSansExtraCondensed_400Regular.ttf');
export const FiraSansExtraCondensed_400Regular_Italic = require('./FiraSansExtraCondensed_400Regular_Italic.ttf');
export const FiraSansExtraCondensed_500Medium = require('./FiraSansExtraCondensed_500Medium.ttf');
export const FiraSansExtraCondensed_500Medium_Italic = require('./FiraSansExtraCondensed_500Medium_Italic.ttf');
export const FiraSansExtraCondensed_600SemiBold = require('./FiraSansExtraCondensed_600SemiBold.ttf');
export const FiraSansExtraCondensed_600SemiBold_Italic = require('./FiraSansExtraCondensed_600SemiBold_Italic.ttf');
export const FiraSansExtraCondensed_700Bold = require('./FiraSansExtraCondensed_700Bold.ttf');
export const FiraSansExtraCondensed_700Bold_Italic = require('./FiraSansExtraCondensed_700Bold_Italic.ttf');
export const FiraSansExtraCondensed_800ExtraBold = require('./FiraSansExtraCondensed_800ExtraBold.ttf');
export const FiraSansExtraCondensed_800ExtraBold_Italic = require('./FiraSansExtraCondensed_800ExtraBold_Italic.ttf');
export const FiraSansExtraCondensed_900Black = require('./FiraSansExtraCondensed_900Black.ttf');
export const FiraSansExtraCondensed_900Black_Italic = require('./FiraSansExtraCondensed_900Black_Italic.ttf');
