/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const FiraSansExtraCondensed_Thin100 = require('./aa0b73aa84c42a6d80d67e8301430b1553b52c7bd68fb79ebe8a2ff750ff58d7.ttf');
export const FiraSansExtraCondensed_Thin100_Italic = require('./9f3e0c06798b24d5853a7192055d69133a9cbd73a9af9f24f62a00b0040d5776.ttf');
export const FiraSansExtraCondensed_ExtraLight200 = require('./bbe50e8aab5ce91f02434c94791440b79cfbc9ee514967d9db84519325fb09bc.ttf');
export const FiraSansExtraCondensed_ExtraLight200_Italic = require('./1c79fb24ec14754ab4fcb134db375dcab006d976fab22d0b109e35fdfcd23366.ttf');
export const FiraSansExtraCondensed_Light300 = require('./40d22d65e7e493b473980345c73d89b480fede26e26e656d2f209dca5e38c1ff.ttf');
export const FiraSansExtraCondensed_Light300_Italic = require('./facbc467dbce58d849a1d881e13552a97aac95f1729e1fc2616bcbb139bc454e.ttf');
export const FiraSansExtraCondensed_Regular400 = require('./86b9aeff0987b7a36348174495862b0223a80ca3b251901d0ee4e171911f3313.ttf');
export const FiraSansExtraCondensed_Regular400_Italic = require('./a9b18a404b2171c7bd6f0b62b4a449ac30caaf7479ea04cf72848bf1e102975a.ttf');
export const FiraSansExtraCondensed_Medium500 = require('./7fcaa10bd6c77effd3a995f07ef8dcc91c68362f20f82be9f906ba8cd66e3a36.ttf');
export const FiraSansExtraCondensed_Medium500_Italic = require('./cf42464fc9f3e1569e0e1538e46fcc39fd02dba1db928aa594205dd74b6e7c72.ttf');
export const FiraSansExtraCondensed_SemiBold600 = require('./0763b0bd415a608f8406877206fbac60d4785217a0983cf5569a0a2ed2922a87.ttf');
export const FiraSansExtraCondensed_SemiBold600_Italic = require('./0f8d32c8579b66b9a1c5be889f3a3b21d4bd26f53af102bd2b4669b8407da059.ttf');
export const FiraSansExtraCondensed_Bold700 = require('./f844b8d0ff4049bc54bf6eeb2fadd15e2e910f98d0a77a3ca693111015e8a365.ttf');
export const FiraSansExtraCondensed_Bold700_Italic = require('./07bfb33f5214d059269b95893bcb1220d50d72c1912c6b53f105a147900b7806.ttf');
export const FiraSansExtraCondensed_ExtraBold800 = require('./7a9cf07642c68b3200835e3a7e3688ed58ed76a3180a2e5cf9b94ce09e158671.ttf');
export const FiraSansExtraCondensed_ExtraBold800_Italic = require('./16f3dcda792af199394d486b422a6a669c52ee944c7bacd532337e88d9840501.ttf');
export const FiraSansExtraCondensed_Black900 = require('./99e363528f9256b35bd83f2a25a2e5f6739df4eeb724246bc87c5ab657192270.ttf');
export const FiraSansExtraCondensed_Black900_Italic = require('./53c97db75ae729e99796dc36bad33e04ea9d0036b759f49f202c3b403c3df3eb.ttf');
