// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Eczar_400Regular = require('./Eczar_400Regular.ttf');
export const Eczar_500Medium = require('./Eczar_500Medium.ttf');
export const Eczar_600SemiBold = require('./Eczar_600SemiBold.ttf');
export const Eczar_700Bold = require('./Eczar_700Bold.ttf');
export const Eczar_800ExtraBold = require('./Eczar_800ExtraBold.ttf');
