// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Unbounded_200ExtraLight = require('./200ExtraLight/Unbounded_200ExtraLight.ttf');
export const Unbounded_300Light = require('./300Light/Unbounded_300Light.ttf');
export const Unbounded_400Regular = require('./400Regular/Unbounded_400Regular.ttf');
export const Unbounded_500Medium = require('./500Medium/Unbounded_500Medium.ttf');
export const Unbounded_600SemiBold = require('./600SemiBold/Unbounded_600SemiBold.ttf');
export const Unbounded_700Bold = require('./700Bold/Unbounded_700Bold.ttf');
export const Unbounded_800ExtraBold = require('./800ExtraBold/Unbounded_800ExtraBold.ttf');
export const Unbounded_900Black = require('./900Black/Unbounded_900Black.ttf');
