/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const BioRhymeExpanded_800ExtraBold = require('./BioRhymeExpanded_800ExtraBold.ttf');
