// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSerif_600SemiBold_Italic = require('./NotoSerif_600SemiBold_Italic.ttf');
