/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metdata__: Any;
export const Nosifer_400Regular: number;
