// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const HindSiliguri_300Light: number;
export const HindSiliguri_400Regular: number;
export const HindSiliguri_500Medium: number;
export const HindSiliguri_600SemiBold: number;
export const HindSiliguri_700Bold: number;
