// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const EduAUVICWANTArrows_400Regular = require('./EduAUVICWANTArrows_400Regular.ttf');
export const EduAUVICWANTArrows_500Medium = require('./EduAUVICWANTArrows_500Medium.ttf');
export const EduAUVICWANTArrows_600SemiBold = require('./EduAUVICWANTArrows_600SemiBold.ttf');
export const EduAUVICWANTArrows_700Bold = require('./EduAUVICWANTArrows_700Bold.ttf');
