/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const NotoSerifGurmukhi_100Thin: number;
export const NotoSerifGurmukhi_200ExtraLight: number;
export const NotoSerifGurmukhi_300Light: number;
export const NotoSerifGurmukhi_400Regular: number;
export const NotoSerifGurmukhi_500Medium: number;
export const NotoSerifGurmukhi_600SemiBold: number;
export const NotoSerifGurmukhi_700Bold: number;
export const NotoSerifGurmukhi_800ExtraBold: number;
export const NotoSerifGurmukhi_900Black: number;
