// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Trispace_100Thin = require('./100Thin/Trispace_100Thin.ttf');
export const Trispace_200ExtraLight = require('./200ExtraLight/Trispace_200ExtraLight.ttf');
export const Trispace_300Light = require('./300Light/Trispace_300Light.ttf');
export const Trispace_400Regular = require('./400Regular/Trispace_400Regular.ttf');
export const Trispace_500Medium = require('./500Medium/Trispace_500Medium.ttf');
export const Trispace_600SemiBold = require('./600SemiBold/Trispace_600SemiBold.ttf');
export const Trispace_700Bold = require('./700Bold/Trispace_700Bold.ttf');
export const Trispace_800ExtraBold = require('./800ExtraBold/Trispace_800ExtraBold.ttf');
