// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const BitcountPropDoubleInk_900Black = require('./BitcountPropDoubleInk_900Black.ttf');
