// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const GrenzeGotisch_400Regular = require('./GrenzeGotisch_400Regular.ttf');
