/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const AfacadFlux_100Thin = require('./AfacadFlux_100Thin.ttf');
export const AfacadFlux_200ExtraLight = require('./AfacadFlux_200ExtraLight.ttf');
export const AfacadFlux_300Light = require('./AfacadFlux_300Light.ttf');
export const AfacadFlux_400Regular = require('./AfacadFlux_400Regular.ttf');
export const AfacadFlux_500Medium = require('./AfacadFlux_500Medium.ttf');
export const AfacadFlux_600SemiBold = require('./AfacadFlux_600SemiBold.ttf');
export const AfacadFlux_700Bold = require('./AfacadFlux_700Bold.ttf');
export const AfacadFlux_800ExtraBold = require('./AfacadFlux_800ExtraBold.ttf');
export const AfacadFlux_900Black = require('./AfacadFlux_900Black.ttf');
