/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const FiraSansCondensed_Thin100: number;
export const FiraSansCondensed_Thin100_Italic: number;
export const FiraSansCondensed_ExtraLight200: number;
export const FiraSansCondensed_ExtraLight200_Italic: number;
export const FiraSansCondensed_Light300: number;
export const FiraSansCondensed_Light300_Italic: number;
export const FiraSansCondensed_Regular400: number;
export const FiraSansCondensed_Regular400_Italic: number;
export const FiraSansCondensed_Medium500: number;
export const FiraSansCondensed_Medium500_Italic: number;
export const FiraSansCondensed_SemiBold600: number;
export const FiraSansCondensed_SemiBold600_Italic: number;
export const FiraSansCondensed_Bold700: number;
export const FiraSansCondensed_Bold700_Italic: number;
export const FiraSansCondensed_ExtraBold800: number;
export const FiraSansCondensed_ExtraBold800_Italic: number;
export const FiraSansCondensed_Black900: number;
export const FiraSansCondensed_Black900_Italic: number;
