// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Inconsolata_400Regular = require('./Inconsolata_400Regular.ttf');
