// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Ramabhadra_400Regular = require('./Ramabhadra_400Regular.ttf');
