/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const WixMadeforText_400Regular_Italic = require('./WixMadeforText_400Regular_Italic.ttf');
