// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaywriteDESAS_200ExtraLight = require('./PlaywriteDESAS_200ExtraLight.ttf');
