/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Archivo_Regular400: number;
export const Archivo_Regular400_Italic: number;
export const Archivo_Medium500: number;
export const Archivo_Medium500_Italic: number;
export const Archivo_SemiBold600: number;
export const Archivo_SemiBold600_Italic: number;
export const Archivo_Bold700: number;
export const Archivo_Bold700_Italic: number;
