/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const Carlito_400Regular = require('./Carlito_400Regular.ttf');
export const Carlito_400Regular_Italic = require('./Carlito_400Regular_Italic.ttf');
export const Carlito_700Bold = require('./Carlito_700Bold.ttf');
export const Carlito_700Bold_Italic = require('./Carlito_700Bold_Italic.ttf');
