// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const SourceSerif4_200ExtraLight: number;
export const SourceSerif4_300Light: number;
export const SourceSerif4_400Regular: number;
export const SourceSerif4_500Medium: number;
export const SourceSerif4_600SemiBold: number;
export const SourceSerif4_700Bold: number;
export const SourceSerif4_800ExtraBold: number;
export const SourceSerif4_900Black: number;
export const SourceSerif4_200ExtraLight_Italic: number;
export const SourceSerif4_300Light_Italic: number;
export const SourceSerif4_400Regular_Italic: number;
export const SourceSerif4_500Medium_Italic: number;
export const SourceSerif4_600SemiBold_Italic: number;
export const SourceSerif4_700Bold_Italic: number;
export const SourceSerif4_800ExtraBold_Italic: number;
export const SourceSerif4_900Black_Italic: number;
