/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteDEGrund_100Thin = require('./PlaywriteDEGrund_100Thin.ttf');
export const PlaywriteDEGrund_200ExtraLight = require('./PlaywriteDEGrund_200ExtraLight.ttf');
export const PlaywriteDEGrund_300Light = require('./PlaywriteDEGrund_300Light.ttf');
export const PlaywriteDEGrund_400Regular = require('./PlaywriteDEGrund_400Regular.ttf');
