// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const NotoSerifMalayalam_100Thin = require('./NotoSerifMalayalam_100Thin.ttf');
export const NotoSerifMalayalam_200ExtraLight = require('./NotoSerifMalayalam_200ExtraLight.ttf');
export const NotoSerifMalayalam_300Light = require('./NotoSerifMalayalam_300Light.ttf');
export const NotoSerifMalayalam_400Regular = require('./NotoSerifMalayalam_400Regular.ttf');
export const NotoSerifMalayalam_500Medium = require('./NotoSerifMalayalam_500Medium.ttf');
export const NotoSerifMalayalam_600SemiBold = require('./NotoSerifMalayalam_600SemiBold.ttf');
export const NotoSerifMalayalam_700Bold = require('./NotoSerifMalayalam_700Bold.ttf');
export const NotoSerifMalayalam_800ExtraBold = require('./NotoSerifMalayalam_800ExtraBold.ttf');
export const NotoSerifMalayalam_900Black = require('./NotoSerifMalayalam_900Black.ttf');
