// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const NotoSerifMalayalam_100Thin = require('./100Thin/NotoSerifMalayalam_100Thin.ttf');
export const NotoSerifMalayalam_200ExtraLight = require('./200ExtraLight/NotoSerifMalayalam_200ExtraLight.ttf');
export const NotoSerifMalayalam_300Light = require('./300Light/NotoSerifMalayalam_300Light.ttf');
export const NotoSerifMalayalam_400Regular = require('./400Regular/NotoSerifMalayalam_400Regular.ttf');
export const NotoSerifMalayalam_500Medium = require('./500Medium/NotoSerifMalayalam_500Medium.ttf');
export const NotoSerifMalayalam_600SemiBold = require('./600SemiBold/NotoSerifMalayalam_600SemiBold.ttf');
export const NotoSerifMalayalam_700Bold = require('./700Bold/NotoSerifMalayalam_700Bold.ttf');
export const NotoSerifMalayalam_800ExtraBold = require('./800ExtraBold/NotoSerifMalayalam_800ExtraBold.ttf');
export const NotoSerifMalayalam_900Black = require('./900Black/NotoSerifMalayalam_900Black.ttf');
