/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export const __fontFamilyName__ = 'Lexend Mega';
export const __fontFamilyVersion__ = 1;

export const LexendMega_Regular400 = require('./2a632f61e3b47867cf774fb3d70ed1a0007cf19ae44be394ea6b878c35648111.ttf');
