// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const IosevkaCharonMono_500Medium = require('./IosevkaCharonMono_500Medium.ttf');
