/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metdata__: Any;
export const Yrsa_300Light: number;
export const Yrsa_400Regular: number;
export const Yrsa_500Medium: number;
export const Yrsa_600SemiBold: number;
export const Yrsa_700Bold: number;
