// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Yrsa_300Light = require('./300Light/Yrsa_300Light.ttf');
export const Yrsa_400Regular = require('./400Regular/Yrsa_400Regular.ttf');
export const Yrsa_500Medium = require('./500Medium/Yrsa_500Medium.ttf');
export const Yrsa_600SemiBold = require('./600SemiBold/Yrsa_600SemiBold.ttf');
export const Yrsa_700Bold = require('./700Bold/Yrsa_700Bold.ttf');
export const Yrsa_300Light_Italic = require('./300Light_Italic/Yrsa_300Light_Italic.ttf');
export const Yrsa_400Regular_Italic = require('./400Regular_Italic/Yrsa_400Regular_Italic.ttf');
export const Yrsa_500Medium_Italic = require('./500Medium_Italic/Yrsa_500Medium_Italic.ttf');
export const Yrsa_600SemiBold_Italic = require('./600SemiBold_Italic/Yrsa_600SemiBold_Italic.ttf');
export const Yrsa_700Bold_Italic = require('./700Bold_Italic/Yrsa_700Bold_Italic.ttf');
