/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const Yrsa_300Light = require('./Yrsa_300Light.ttf');
export const Yrsa_400Regular = require('./Yrsa_400Regular.ttf');
export const Yrsa_500Medium = require('./Yrsa_500Medium.ttf');
export const Yrsa_600SemiBold = require('./Yrsa_600SemiBold.ttf');
export const Yrsa_700Bold = require('./Yrsa_700Bold.ttf');
export const Yrsa_300Light_Italic = require('./Yrsa_300Light_Italic.ttf');
export const Yrsa_400Regular_Italic = require('./Yrsa_400Regular_Italic.ttf');
export const Yrsa_500Medium_Italic = require('./Yrsa_500Medium_Italic.ttf');
export const Yrsa_600SemiBold_Italic = require('./Yrsa_600SemiBold_Italic.ttf');
export const Yrsa_700Bold_Italic = require('./Yrsa_700Bold_Italic.ttf');
