// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const LovedbytheKing_400Regular = require('./LovedbytheKing_400Regular.ttf');
