// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansAdlamUnjoined_400Regular = require('./NotoSansAdlamUnjoined_400Regular.ttf');
