// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Lekton_400Regular = require('./400Regular/Lekton_400Regular.ttf');
export const Lekton_400Regular_Italic = require('./400Regular_Italic/Lekton_400Regular_Italic.ttf');
export const Lekton_700Bold = require('./700Bold/Lekton_700Bold.ttf');
