// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaywriteZAGuides_400Regular = require('./PlaywriteZAGuides_400Regular.ttf');
