// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const AlumniSans_400Regular_Italic = require('./AlumniSans_400Regular_Italic.ttf');
