/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Martel_ExtraLight200: number;
export const Martel_Light300: number;
export const Martel_Regular400: number;
export const Martel_SemiBold600: number;
export const Martel_Bold700: number;
export const Martel_ExtraBold800: number;
export const Martel_Black900: number;
