/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export const __fontFamilyName__ = 'Bentham';
export const __fontFamilyVersion__ = 6;

export const Bentham_Regular400 = require('./36b9c399aae73bd09e01d76e51e8697f80e9e34f14e954b929a08d6cfbc5f697.ttf');
