// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const LoversQuarrel_400Regular = require('./LoversQuarrel_400Regular.ttf');
