/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const NotoSans_200ExtraLight_Italic = require('./NotoSans_200ExtraLight_Italic.ttf');
