// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Figtree_300Light = require('./300Light/Figtree_300Light.ttf');
export const Figtree_400Regular = require('./400Regular/Figtree_400Regular.ttf');
export const Figtree_500Medium = require('./500Medium/Figtree_500Medium.ttf');
export const Figtree_600SemiBold = require('./600SemiBold/Figtree_600SemiBold.ttf');
export const Figtree_700Bold = require('./700Bold/Figtree_700Bold.ttf');
export const Figtree_800ExtraBold = require('./800ExtraBold/Figtree_800ExtraBold.ttf');
export const Figtree_900Black = require('./900Black/Figtree_900Black.ttf');
export const Figtree_300Light_Italic = require('./300Light_Italic/Figtree_300Light_Italic.ttf');
export const Figtree_400Regular_Italic = require('./400Regular_Italic/Figtree_400Regular_Italic.ttf');
export const Figtree_500Medium_Italic = require('./500Medium_Italic/Figtree_500Medium_Italic.ttf');
export const Figtree_600SemiBold_Italic = require('./600SemiBold_Italic/Figtree_600SemiBold_Italic.ttf');
export const Figtree_700Bold_Italic = require('./700Bold_Italic/Figtree_700Bold_Italic.ttf');
export const Figtree_800ExtraBold_Italic = require('./800ExtraBold_Italic/Figtree_800ExtraBold_Italic.ttf');
export const Figtree_900Black_Italic = require('./900Black_Italic/Figtree_900Black_Italic.ttf');
