// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const BetaniaPatmos_400Regular = require('./BetaniaPatmos_400Regular.ttf');
