/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const TiroGurmukhi_400Regular_Italic = require('./TiroGurmukhi_400Regular_Italic.ttf');
