// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const BitcountGridSingleInk_800ExtraBold = require('./BitcountGridSingleInk_800ExtraBold.ttf');
