/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const FrancoisOne_Regular400 = require('./9732016aa4f374d99be54bb4dff92ffaa1133a4d293595c2bd7f621e01b38e85.ttf');
