/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const LifeSavers_Regular400 = require('./04d39ceac525bd7119947e50ca506cd62efc8803e38347a7b1d07e401463bcee.ttf');
export const LifeSavers_Bold700 = require('./362b7da392f70200e34ca8d939a7739b45fdd4cb54b9aee41f6a1db39d13a08b.ttf');
