// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const ShipporiMinchoB1_700Bold = require('./ShipporiMinchoB1_700Bold.ttf');
