// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const JetBrainsMono_400Regular = require('./JetBrainsMono_400Regular.ttf');
