// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Catamaran_200ExtraLight = require('./Catamaran_200ExtraLight.ttf');
