// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Almendra_700Bold_Italic = require('./Almendra_700Bold_Italic.ttf');
