// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const BitcountGridSingle_300Light = require('./BitcountGridSingle_300Light.ttf');
