// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const GreatVibes_400Regular = require('./GreatVibes_400Regular.ttf');
