/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const SofiaSansSemiCondensed_600SemiBold_Italic = require('./SofiaSansSemiCondensed_600SemiBold_Italic.ttf');
