// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const WixMadeforDisplay_400Regular = require('./400Regular/WixMadeforDisplay_400Regular.ttf');
export const WixMadeforDisplay_500Medium = require('./500Medium/WixMadeforDisplay_500Medium.ttf');
export const WixMadeforDisplay_600SemiBold = require('./600SemiBold/WixMadeforDisplay_600SemiBold.ttf');
export const WixMadeforDisplay_700Bold = require('./700Bold/WixMadeforDisplay_700Bold.ttf');
export const WixMadeforDisplay_800ExtraBold = require('./800ExtraBold/WixMadeforDisplay_800ExtraBold.ttf');
