// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansSoraSompeng_600SemiBold = require('./NotoSansSoraSompeng_600SemiBold.ttf');
