// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Linefont_200ExtraLight = require('./Linefont_200ExtraLight.ttf');
