// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaywriteSK_200ExtraLight = require('./PlaywriteSK_200ExtraLight.ttf');
