/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const HindMadurai_300Light: number;
export const HindMadurai_400Regular: number;
export const HindMadurai_500Medium: number;
export const HindMadurai_600SemiBold: number;
export const HindMadurai_700Bold: number;
