// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const HindMadurai_300Light: number;
export const HindMadurai_400Regular: number;
export const HindMadurai_500Medium: number;
export const HindMadurai_600SemiBold: number;
export const HindMadurai_700Bold: number;
