// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const PlaywriteAUVIC_100Thin = require('./100Thin/PlaywriteAUVIC_100Thin.ttf');
export const PlaywriteAUVIC_200ExtraLight = require('./200ExtraLight/PlaywriteAUVIC_200ExtraLight.ttf');
export const PlaywriteAUVIC_300Light = require('./300Light/PlaywriteAUVIC_300Light.ttf');
export const PlaywriteAUVIC_400Regular = require('./400Regular/PlaywriteAUVIC_400Regular.ttf');
