// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Menbere_100Thin = require('./100Thin/Menbere_100Thin.ttf');
export const Menbere_200ExtraLight = require('./200ExtraLight/Menbere_200ExtraLight.ttf');
export const Menbere_300Light = require('./300Light/Menbere_300Light.ttf');
export const Menbere_400Regular = require('./400Regular/Menbere_400Regular.ttf');
export const Menbere_500Medium = require('./500Medium/Menbere_500Medium.ttf');
export const Menbere_600SemiBold = require('./600SemiBold/Menbere_600SemiBold.ttf');
export const Menbere_700Bold = require('./700Bold/Menbere_700Bold.ttf');
