/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const BigShouldersInlineDisplay_100Thin = require('./BigShouldersInlineDisplay_100Thin.ttf');
export const BigShouldersInlineDisplay_200ExtraLight = require('./BigShouldersInlineDisplay_200ExtraLight.ttf');
export const BigShouldersInlineDisplay_300Light = require('./BigShouldersInlineDisplay_300Light.ttf');
export const BigShouldersInlineDisplay_400Regular = require('./BigShouldersInlineDisplay_400Regular.ttf');
export const BigShouldersInlineDisplay_500Medium = require('./BigShouldersInlineDisplay_500Medium.ttf');
export const BigShouldersInlineDisplay_600SemiBold = require('./BigShouldersInlineDisplay_600SemiBold.ttf');
export const BigShouldersInlineDisplay_700Bold = require('./BigShouldersInlineDisplay_700Bold.ttf');
export const BigShouldersInlineDisplay_800ExtraBold = require('./BigShouldersInlineDisplay_800ExtraBold.ttf');
export const BigShouldersInlineDisplay_900Black = require('./BigShouldersInlineDisplay_900Black.ttf');
