/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const NotoSerifGeorgian_800ExtraBold = require('./NotoSerifGeorgian_800ExtraBold.ttf');
