// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const MartianMono_800ExtraBold = require('./MartianMono_800ExtraBold.ttf');
