/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const AnekDevanagari_100Thin: number;
export const AnekDevanagari_200ExtraLight: number;
export const AnekDevanagari_300Light: number;
export const AnekDevanagari_400Regular: number;
export const AnekDevanagari_500Medium: number;
export const AnekDevanagari_600SemiBold: number;
export const AnekDevanagari_700Bold: number;
export const AnekDevanagari_800ExtraBold: number;
