// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const PlaywriteAT_100Thin: number;
export const PlaywriteAT_200ExtraLight: number;
export const PlaywriteAT_300Light: number;
export const PlaywriteAT_400Regular: number;
export const PlaywriteAT_100Thin_Italic: number;
export const PlaywriteAT_200ExtraLight_Italic: number;
export const PlaywriteAT_300Light_Italic: number;
export const PlaywriteAT_400Regular_Italic: number;
