/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export const __fontFamilyName__ = 'MedievalSharp';
export const __fontFamilyVersion__ = 8;

export const MedievalSharp_Regular400 = require('./93afbe692f662b93c6faf17b061d07ad7b343db38496d49e05bc31fcfaf585ae.ttf');
