// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Teachers_400Regular = require('./400Regular/Teachers_400Regular.ttf');
export const Teachers_500Medium = require('./500Medium/Teachers_500Medium.ttf');
export const Teachers_600SemiBold = require('./600SemiBold/Teachers_600SemiBold.ttf');
export const Teachers_700Bold = require('./700Bold/Teachers_700Bold.ttf');
export const Teachers_800ExtraBold = require('./800ExtraBold/Teachers_800ExtraBold.ttf');
export const Teachers_400Regular_Italic = require('./400Regular_Italic/Teachers_400Regular_Italic.ttf');
export const Teachers_500Medium_Italic = require('./500Medium_Italic/Teachers_500Medium_Italic.ttf');
export const Teachers_600SemiBold_Italic = require('./600SemiBold_Italic/Teachers_600SemiBold_Italic.ttf');
export const Teachers_700Bold_Italic = require('./700Bold_Italic/Teachers_700Bold_Italic.ttf');
export const Teachers_800ExtraBold_Italic = require('./800ExtraBold_Italic/Teachers_800ExtraBold_Italic.ttf');
