/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Mallanna_Regular400 = require('./81feb01d40b2b7875e496dde6320f6af4ca381b03d376608ba5d8f9a8eb72db4.ttf');
