// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const HindVadodara_400Regular = require('./HindVadodara_400Regular.ttf');
