/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const Platypi_300Light: number;
export const Platypi_400Regular: number;
export const Platypi_500Medium: number;
export const Platypi_600SemiBold: number;
export const Platypi_700Bold: number;
export const Platypi_800ExtraBold: number;
export const Platypi_300Light_Italic: number;
export const Platypi_400Regular_Italic: number;
export const Platypi_500Medium_Italic: number;
export const Platypi_600SemiBold_Italic: number;
export const Platypi_700Bold_Italic: number;
export const Platypi_800ExtraBold_Italic: number;
