/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Arsenal_Regular400 = require('./7b13a735c3c27289a74f4e934b380f078f89568b2633c5d8386e97a97d46158c.ttf');
export const Arsenal_Regular400_Italic = require('./f687cc6b9b17ac45aaf3391fbe649c2e1607804ce3ab85daddf9669f796d0a79.ttf');
export const Arsenal_Bold700 = require('./0ac62eb1c6ee28d30c2dacea06acdbec9c72bcbfdca1f76a873b8a2c18ac8ae6.ttf');
export const Arsenal_Bold700_Italic = require('./41b9ba2384a037e4ec361896e5868107cfa8535ab8befda2d9666584884aca80.ttf');
