/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Arsenal_Regular400: number;
export const Arsenal_Regular400_Italic: number;
export const Arsenal_Bold700: number;
export const Arsenal_Bold700_Italic: number;
