// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansSamaritan_400Regular = require('./NotoSansSamaritan_400Regular.ttf');
