// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansSyriac_100Thin = require('./NotoSansSyriac_100Thin.ttf');
