// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const BioRhyme_200ExtraLight = require('./BioRhyme_200ExtraLight.ttf');
export const BioRhyme_300Light = require('./BioRhyme_300Light.ttf');
export const BioRhyme_400Regular = require('./BioRhyme_400Regular.ttf');
export const BioRhyme_500Medium = require('./BioRhyme_500Medium.ttf');
export const BioRhyme_600SemiBold = require('./BioRhyme_600SemiBold.ttf');
export const BioRhyme_700Bold = require('./BioRhyme_700Bold.ttf');
export const BioRhyme_800ExtraBold = require('./BioRhyme_800ExtraBold.ttf');
