/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const BioRhyme_ExtraLight200: number;
export const BioRhyme_Light300: number;
export const BioRhyme_Regular400: number;
export const BioRhyme_Bold700: number;
export const BioRhyme_ExtraBold800: number;
