// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const Blinker_100Thin: number;
export const Blinker_200ExtraLight: number;
export const Blinker_300Light: number;
export const Blinker_400Regular: number;
export const Blinker_600SemiBold: number;
export const Blinker_700Bold: number;
export const Blinker_800ExtraBold: number;
export const Blinker_900Black: number;
