// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const LeagueSpartan_600SemiBold = require('./LeagueSpartan_600SemiBold.ttf');
