/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metdata__: Any;
export const CormorantUnicase_300Light: number;
export const CormorantUnicase_400Regular: number;
export const CormorantUnicase_500Medium: number;
export const CormorantUnicase_600SemiBold: number;
export const CormorantUnicase_700Bold: number;
