// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSerifEthiopic_700Bold = require('./NotoSerifEthiopic_700Bold.ttf');
