// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const BarlowCondensed_100Thin = require('./100Thin/BarlowCondensed_100Thin.ttf');
export const BarlowCondensed_100Thin_Italic = require('./100Thin_Italic/BarlowCondensed_100Thin_Italic.ttf');
export const BarlowCondensed_200ExtraLight = require('./200ExtraLight/BarlowCondensed_200ExtraLight.ttf');
export const BarlowCondensed_200ExtraLight_Italic = require('./200ExtraLight_Italic/BarlowCondensed_200ExtraLight_Italic.ttf');
export const BarlowCondensed_300Light = require('./300Light/BarlowCondensed_300Light.ttf');
export const BarlowCondensed_300Light_Italic = require('./300Light_Italic/BarlowCondensed_300Light_Italic.ttf');
export const BarlowCondensed_400Regular = require('./400Regular/BarlowCondensed_400Regular.ttf');
export const BarlowCondensed_400Regular_Italic = require('./400Regular_Italic/BarlowCondensed_400Regular_Italic.ttf');
export const BarlowCondensed_500Medium = require('./500Medium/BarlowCondensed_500Medium.ttf');
export const BarlowCondensed_500Medium_Italic = require('./500Medium_Italic/BarlowCondensed_500Medium_Italic.ttf');
export const BarlowCondensed_600SemiBold = require('./600SemiBold/BarlowCondensed_600SemiBold.ttf');
export const BarlowCondensed_600SemiBold_Italic = require('./600SemiBold_Italic/BarlowCondensed_600SemiBold_Italic.ttf');
export const BarlowCondensed_700Bold = require('./700Bold/BarlowCondensed_700Bold.ttf');
export const BarlowCondensed_700Bold_Italic = require('./700Bold_Italic/BarlowCondensed_700Bold_Italic.ttf');
export const BarlowCondensed_800ExtraBold = require('./800ExtraBold/BarlowCondensed_800ExtraBold.ttf');
export const BarlowCondensed_800ExtraBold_Italic = require('./800ExtraBold_Italic/BarlowCondensed_800ExtraBold_Italic.ttf');
export const BarlowCondensed_900Black = require('./900Black/BarlowCondensed_900Black.ttf');
export const BarlowCondensed_900Black_Italic = require('./900Black_Italic/BarlowCondensed_900Black_Italic.ttf');
