// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const JainiPurva_400Regular = require('./JainiPurva_400Regular.ttf');
