// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const Ubuntu_300Light: number;
export const Ubuntu_300Light_Italic: number;
export const Ubuntu_400Regular: number;
export const Ubuntu_400Regular_Italic: number;
export const Ubuntu_500Medium: number;
export const Ubuntu_500Medium_Italic: number;
export const Ubuntu_700Bold: number;
export const Ubuntu_700Bold_Italic: number;
