/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const PlaywriteHRLijeva_100Thin: number;
export const PlaywriteHRLijeva_200ExtraLight: number;
export const PlaywriteHRLijeva_300Light: number;
export const PlaywriteHRLijeva_400Regular: number;
