/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteHRLijeva_100Thin = require('./PlaywriteHRLijeva_100Thin.ttf');
export const PlaywriteHRLijeva_200ExtraLight = require('./PlaywriteHRLijeva_200ExtraLight.ttf');
export const PlaywriteHRLijeva_300Light = require('./PlaywriteHRLijeva_300Light.ttf');
export const PlaywriteHRLijeva_400Regular = require('./PlaywriteHRLijeva_400Regular.ttf');
