/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const ReadexPro_200ExtraLight = require('./ReadexPro_200ExtraLight.ttf');
export const ReadexPro_300Light = require('./ReadexPro_300Light.ttf');
export const ReadexPro_400Regular = require('./ReadexPro_400Regular.ttf');
export const ReadexPro_500Medium = require('./ReadexPro_500Medium.ttf');
export const ReadexPro_600SemiBold = require('./ReadexPro_600SemiBold.ttf');
export const ReadexPro_700Bold = require('./ReadexPro_700Bold.ttf');
