/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Boogaloo_Regular400 = require('./ecd8d89eafeb4669ce51f02cef4e529aa97180ed7c2a9cfcbad4714ed9ede46f.ttf');
