/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const Doto_100Thin: number;
export const Doto_200ExtraLight: number;
export const Doto_300Light: number;
export const Doto_400Regular: number;
export const Doto_500Medium: number;
export const Doto_600SemiBold: number;
export const Doto_700Bold: number;
export const Doto_800ExtraBold: number;
export const Doto_900Black: number;
