// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const CairoPlay_600SemiBold = require('./CairoPlay_600SemiBold.ttf');
