/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const PlusJakartaSans_200ExtraLight_Italic = require('./PlusJakartaSans_200ExtraLight_Italic.ttf');
