// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Inika_400Regular = require('./400Regular/Inika_400Regular.ttf');
export const Inika_700Bold = require('./700Bold/Inika_700Bold.ttf');
