// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const AlumniSansInlineOne_400Regular = require('./AlumniSansInlineOne_400Regular.ttf');
