/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const AlumniSansInlineOne_400Regular = require('./AlumniSansInlineOne_400Regular.ttf');
