/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const NotoSerifTibetan_800ExtraBold = require('./NotoSerifTibetan_800ExtraBold.ttf');
