// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const MuktaMalar_400Regular = require('./MuktaMalar_400Regular.ttf');
