/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const CedarvilleCursive_400Regular = require('./CedarvilleCursive_400Regular.ttf');
