// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const BIZUDMincho_400Regular = require('./400Regular/BIZUDMincho_400Regular.ttf');
export const BIZUDMincho_700Bold = require('./700Bold/BIZUDMincho_700Bold.ttf');
