// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const PalanquinDark_400Regular = require('./PalanquinDark_400Regular.ttf');
export const PalanquinDark_500Medium = require('./PalanquinDark_500Medium.ttf');
export const PalanquinDark_600SemiBold = require('./PalanquinDark_600SemiBold.ttf');
export const PalanquinDark_700Bold = require('./PalanquinDark_700Bold.ttf');
