// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const RubikBubbles_400Regular = require('./RubikBubbles_400Regular.ttf');
