/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const Skranji_400Regular = require('./Skranji_400Regular.ttf');
export const Skranji_700Bold = require('./Skranji_700Bold.ttf');
