/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const FuzzyBubbles_400Regular = require('./FuzzyBubbles_400Regular.ttf');
export const FuzzyBubbles_700Bold = require('./FuzzyBubbles_700Bold.ttf');
