// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const MonaSans_200ExtraLight = require('./200ExtraLight/MonaSans_200ExtraLight.ttf');
export const MonaSans_300Light = require('./300Light/MonaSans_300Light.ttf');
export const MonaSans_400Regular = require('./400Regular/MonaSans_400Regular.ttf');
export const MonaSans_500Medium = require('./500Medium/MonaSans_500Medium.ttf');
export const MonaSans_600SemiBold = require('./600SemiBold/MonaSans_600SemiBold.ttf');
export const MonaSans_700Bold = require('./700Bold/MonaSans_700Bold.ttf');
export const MonaSans_800ExtraBold = require('./800ExtraBold/MonaSans_800ExtraBold.ttf');
export const MonaSans_900Black = require('./900Black/MonaSans_900Black.ttf');
export const MonaSans_200ExtraLight_Italic = require('./200ExtraLight_Italic/MonaSans_200ExtraLight_Italic.ttf');
export const MonaSans_300Light_Italic = require('./300Light_Italic/MonaSans_300Light_Italic.ttf');
export const MonaSans_400Regular_Italic = require('./400Regular_Italic/MonaSans_400Regular_Italic.ttf');
export const MonaSans_500Medium_Italic = require('./500Medium_Italic/MonaSans_500Medium_Italic.ttf');
export const MonaSans_600SemiBold_Italic = require('./600SemiBold_Italic/MonaSans_600SemiBold_Italic.ttf');
export const MonaSans_700Bold_Italic = require('./700Bold_Italic/MonaSans_700Bold_Italic.ttf');
export const MonaSans_800ExtraBold_Italic = require('./800ExtraBold_Italic/MonaSans_800ExtraBold_Italic.ttf');
export const MonaSans_900Black_Italic = require('./900Black_Italic/MonaSans_900Black_Italic.ttf');
