// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaywriteDKLoopet_200ExtraLight = require('./PlaywriteDKLoopet_200ExtraLight.ttf');
