/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const Cuprum_400Regular = require('./Cuprum_400Regular.ttf');
export const Cuprum_400Regular_Italic = require('./Cuprum_400Regular_Italic.ttf');
export const Cuprum_700Bold = require('./Cuprum_700Bold.ttf');
export const Cuprum_700Bold_Italic = require('./Cuprum_700Bold_Italic.ttf');
