/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const NotoSansMedefaidrin_500Medium = require('./NotoSansMedefaidrin_500Medium.ttf');
