// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const AlumniSansCollegiateOne_400Regular = require('./AlumniSansCollegiateOne_400Regular.ttf');
