// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const SourceCodePro_200ExtraLight: number;
export const SourceCodePro_300Light: number;
export const SourceCodePro_400Regular: number;
export const SourceCodePro_500Medium: number;
export const SourceCodePro_600SemiBold: number;
export const SourceCodePro_700Bold: number;
export const SourceCodePro_800ExtraBold: number;
export const SourceCodePro_900Black: number;
export const SourceCodePro_200ExtraLight_Italic: number;
export const SourceCodePro_300Light_Italic: number;
export const SourceCodePro_400Regular_Italic: number;
export const SourceCodePro_500Medium_Italic: number;
export const SourceCodePro_600SemiBold_Italic: number;
export const SourceCodePro_700Bold_Italic: number;
export const SourceCodePro_800ExtraBold_Italic: number;
export const SourceCodePro_900Black_Italic: number;
