/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Changa_ExtraLight200: number;
export const Changa_Light300: number;
export const Changa_Regular400: number;
export const Changa_Medium500: number;
export const Changa_SemiBold600: number;
export const Changa_Bold700: number;
export const Changa_ExtraBold800: number;
