/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const SofadiOne_Regular400 = require('./bd2ee7258a722de3e36e84a9aadf3edfe4b91221f382e3e5bbe75b786119526f.ttf');
