/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Almarai_Light300: number;
export const Almarai_Regular400: number;
export const Almarai_Bold700: number;
export const Almarai_ExtraBold800: number;
