// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const Almarai_300Light: number;
export const Almarai_400Regular: number;
export const Almarai_700Bold: number;
export const Almarai_800ExtraBold: number;
