/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const Signika_300Light = require('./Signika_300Light.ttf');
export const Signika_400Regular = require('./Signika_400Regular.ttf');
export const Signika_500Medium = require('./Signika_500Medium.ttf');
export const Signika_600SemiBold = require('./Signika_600SemiBold.ttf');
export const Signika_700Bold = require('./Signika_700Bold.ttf');
