// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const RadioCanadaBig_400Regular = require('./RadioCanadaBig_400Regular.ttf');
export const RadioCanadaBig_500Medium = require('./RadioCanadaBig_500Medium.ttf');
export const RadioCanadaBig_600SemiBold = require('./RadioCanadaBig_600SemiBold.ttf');
export const RadioCanadaBig_700Bold = require('./RadioCanadaBig_700Bold.ttf');
export const RadioCanadaBig_400Regular_Italic = require('./RadioCanadaBig_400Regular_Italic.ttf');
export const RadioCanadaBig_500Medium_Italic = require('./RadioCanadaBig_500Medium_Italic.ttf');
export const RadioCanadaBig_600SemiBold_Italic = require('./RadioCanadaBig_600SemiBold_Italic.ttf');
export const RadioCanadaBig_700Bold_Italic = require('./RadioCanadaBig_700Bold_Italic.ttf');
