// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Grandstander_500Medium = require('./Grandstander_500Medium.ttf');
