// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const EncodeSansSemiExpanded_900Black = require('./EncodeSansSemiExpanded_900Black.ttf');
