/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const EncodeSansSemiExpanded_900Black = require('./EncodeSansSemiExpanded_900Black.ttf');
