// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const IBMPlexSansHebrew_200ExtraLight = require('./IBMPlexSansHebrew_200ExtraLight.ttf');
