// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansKaithi_400Regular = require('./NotoSansKaithi_400Regular.ttf');
