// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Radley_400Regular_Italic = require('./Radley_400Regular_Italic.ttf');
