// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Gwendolyn_400Regular = require('./Gwendolyn_400Regular.ttf');
export const Gwendolyn_700Bold = require('./Gwendolyn_700Bold.ttf');
