// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const BitcountPropDoubleInk_100Thin = require('./100Thin/BitcountPropDoubleInk_100Thin.ttf');
export const BitcountPropDoubleInk_200ExtraLight = require('./200ExtraLight/BitcountPropDoubleInk_200ExtraLight.ttf');
export const BitcountPropDoubleInk_300Light = require('./300Light/BitcountPropDoubleInk_300Light.ttf');
export const BitcountPropDoubleInk_400Regular = require('./400Regular/BitcountPropDoubleInk_400Regular.ttf');
export const BitcountPropDoubleInk_500Medium = require('./500Medium/BitcountPropDoubleInk_500Medium.ttf');
export const BitcountPropDoubleInk_600SemiBold = require('./600SemiBold/BitcountPropDoubleInk_600SemiBold.ttf');
export const BitcountPropDoubleInk_700Bold = require('./700Bold/BitcountPropDoubleInk_700Bold.ttf');
export const BitcountPropDoubleInk_800ExtraBold = require('./800ExtraBold/BitcountPropDoubleInk_800ExtraBold.ttf');
export const BitcountPropDoubleInk_900Black = require('./900Black/BitcountPropDoubleInk_900Black.ttf');
