/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const GentiumPlus_400Regular = require('./GentiumPlus_400Regular.ttf');
export const GentiumPlus_400Regular_Italic = require('./GentiumPlus_400Regular_Italic.ttf');
export const GentiumPlus_700Bold = require('./GentiumPlus_700Bold.ttf');
export const GentiumPlus_700Bold_Italic = require('./GentiumPlus_700Bold_Italic.ttf');
