// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const GentiumPlus_400Regular = require('./400Regular/GentiumPlus_400Regular.ttf');
export const GentiumPlus_400Regular_Italic = require('./400Regular_Italic/GentiumPlus_400Regular_Italic.ttf');
export const GentiumPlus_700Bold = require('./700Bold/GentiumPlus_700Bold.ttf');
export const GentiumPlus_700Bold_Italic = require('./700Bold_Italic/GentiumPlus_700Bold_Italic.ttf');
