/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const KaiseiOpti_400Regular = require('./KaiseiOpti_400Regular.ttf');
export const KaiseiOpti_500Medium = require('./KaiseiOpti_500Medium.ttf');
export const KaiseiOpti_700Bold = require('./KaiseiOpti_700Bold.ttf');
