/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const Akshar_300Light: number;
export const Akshar_400Regular: number;
export const Akshar_500Medium: number;
export const Akshar_600SemiBold: number;
export const Akshar_700Bold: number;
