// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const CrimsonPro_500Medium_Italic = require('./CrimsonPro_500Medium_Italic.ttf');
