// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const AdventPro_600SemiBold = require('./AdventPro_600SemiBold.ttf');
