// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export const __metadata__: any;
export const Raleway_100Thin: number;
export const Raleway_200ExtraLight: number;
export const Raleway_300Light: number;
export const Raleway_400Regular: number;
export const Raleway_500Medium: number;
export const Raleway_600SemiBold: number;
export const Raleway_700Bold: number;
export const Raleway_800ExtraBold: number;
export const Raleway_900Black: number;
export const Raleway_100Thin_Italic: number;
export const Raleway_200ExtraLight_Italic: number;
export const Raleway_300Light_Italic: number;
export const Raleway_400Regular_Italic: number;
export const Raleway_500Medium_Italic: number;
export const Raleway_600SemiBold_Italic: number;
export const Raleway_700Bold_Italic: number;
export const Raleway_800ExtraBold_Italic: number;
export const Raleway_900Black_Italic: number;
