// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansNewTaiLue_400Regular = require('./NotoSansNewTaiLue_400Regular.ttf');
