// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansCanadianAboriginal_900Black = require('./NotoSansCanadianAboriginal_900Black.ttf');
