// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansOlChiki_600SemiBold = require('./NotoSansOlChiki_600SemiBold.ttf');
