/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Kanit_Thin100: number;
export const Kanit_Thin100_Italic: number;
export const Kanit_ExtraLight200: number;
export const Kanit_ExtraLight200_Italic: number;
export const Kanit_Light300: number;
export const Kanit_Light300_Italic: number;
export const Kanit_Regular400: number;
export const Kanit_Regular400_Italic: number;
export const Kanit_Medium500: number;
export const Kanit_Medium500_Italic: number;
export const Kanit_SemiBold600: number;
export const Kanit_SemiBold600_Italic: number;
export const Kanit_Bold700: number;
export const Kanit_Bold700_Italic: number;
export const Kanit_ExtraBold800: number;
export const Kanit_ExtraBold800_Italic: number;
export const Kanit_Black900: number;
export const Kanit_Black900_Italic: number;
