/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Kanit_Thin100 = require('./9ae2534d6b4ec69c677d8c2cf336e1ba3c802e9e316c028c99a8db43ebb63f70.ttf');
export const Kanit_Thin100_Italic = require('./07d136289c506d3788ccbfcdf9e764427270b557b1b601d925bf997d002827ff.ttf');
export const Kanit_ExtraLight200 = require('./5a7bd784e91a9a006ec021a5f891a29ac3d867878f998bb1c2d7cdeac7dcb6b2.ttf');
export const Kanit_ExtraLight200_Italic = require('./4171f0d7fdb919ffe44d9fb9fcccb08610ca5646f6e1f258e62ebe1b237d40b7.ttf');
export const Kanit_Light300 = require('./af3df5dc97d26cade1367d07a411e2ce209ab130f0d0f22c73594f2f9488f231.ttf');
export const Kanit_Light300_Italic = require('./684fbd0330c7997a7aa6d6b72454ed7dbcaab91d2c54be50157988c9669ff845.ttf');
export const Kanit_Regular400 = require('./7996f53043acf5b6c782024a9c21ccd0bbab714f137cba3f64a2108709df989b.ttf');
export const Kanit_Regular400_Italic = require('./9367b66fe82713a777016d80d74986e22f272688d4fa1a7aaa2e8d999d31b0d4.ttf');
export const Kanit_Medium500 = require('./696301b8ecd45c7227d2c5ff3a308bbf701b05428b121fa43523622416c87e12.ttf');
export const Kanit_Medium500_Italic = require('./6dd4b995a1dde18512697195090fb6bee9d0f44b124e8deb55d8619204637957.ttf');
export const Kanit_SemiBold600 = require('./ccc6cb20ad4fe61a7cd12f4124476933985e5e8c105008bf5549dee46d671fcb.ttf');
export const Kanit_SemiBold600_Italic = require('./5f81f4c0eae984a4ba6dec488b4b74c2b72db9871111ee3b595473a73be34d5b.ttf');
export const Kanit_Bold700 = require('./9844297d29f6a9c9d97cfa435750cc2933cc8d47b30e9c380e080d665310aaad.ttf');
export const Kanit_Bold700_Italic = require('./84a74264e2a1b11040aa80b859501eb498938736938cc12e1838be482ca1681f.ttf');
export const Kanit_ExtraBold800 = require('./ac86afa00dd8b070dc0325ff6ee63daee98cd4004aacce60aab9a9f147d3151e.ttf');
export const Kanit_ExtraBold800_Italic = require('./0d3cf6f6f9f8952c9fbffa0fba60279f3b0fee229b846a4ff1d127732642c3c8.ttf');
export const Kanit_Black900 = require('./593120b5c1292664ccee5994d9936265b8372449097d70ce0cdc3737408f0c1f.ttf');
export const Kanit_Black900_Italic = require('./887e5a2586587398cc15672b3f3fef3e35836150f74ff4c8f80a34895effe69a.ttf');
