// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const StackSansNotch_600SemiBold = require('./StackSansNotch_600SemiBold.ttf');
