// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const GFSNeohellenic_700Bold = require('./GFSNeohellenic_700Bold.ttf');
