// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansDevanagari_200ExtraLight = require('./NotoSansDevanagari_200ExtraLight.ttf');
