/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metdata__: Any;
export const Domine_400Regular: number;
export const Domine_500Medium: number;
export const Domine_600SemiBold: number;
export const Domine_700Bold: number;
