// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSerifTamil_900Black = require('./NotoSerifTamil_900Black.ttf');
