// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const LifeSavers_800ExtraBold = require('./LifeSavers_800ExtraBold.ttf');
