/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const HostGrotesk_300Light = require('./HostGrotesk_300Light.ttf');
export const HostGrotesk_400Regular = require('./HostGrotesk_400Regular.ttf');
export const HostGrotesk_500Medium = require('./HostGrotesk_500Medium.ttf');
export const HostGrotesk_600SemiBold = require('./HostGrotesk_600SemiBold.ttf');
export const HostGrotesk_700Bold = require('./HostGrotesk_700Bold.ttf');
export const HostGrotesk_800ExtraBold = require('./HostGrotesk_800ExtraBold.ttf');
export const HostGrotesk_300Light_Italic = require('./HostGrotesk_300Light_Italic.ttf');
export const HostGrotesk_400Regular_Italic = require('./HostGrotesk_400Regular_Italic.ttf');
export const HostGrotesk_500Medium_Italic = require('./HostGrotesk_500Medium_Italic.ttf');
export const HostGrotesk_600SemiBold_Italic = require('./HostGrotesk_600SemiBold_Italic.ttf');
export const HostGrotesk_700Bold_Italic = require('./HostGrotesk_700Bold_Italic.ttf');
export const HostGrotesk_800ExtraBold_Italic = require('./HostGrotesk_800ExtraBold_Italic.ttf');
