// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const HostGrotesk_300Light: number;
export const HostGrotesk_400Regular: number;
export const HostGrotesk_500Medium: number;
export const HostGrotesk_600SemiBold: number;
export const HostGrotesk_700Bold: number;
export const HostGrotesk_800ExtraBold: number;
export const HostGrotesk_300Light_Italic: number;
export const HostGrotesk_400Regular_Italic: number;
export const HostGrotesk_500Medium_Italic: number;
export const HostGrotesk_600SemiBold_Italic: number;
export const HostGrotesk_700Bold_Italic: number;
export const HostGrotesk_800ExtraBold_Italic: number;
