// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansArmenian_200ExtraLight = require('./NotoSansArmenian_200ExtraLight.ttf');
