/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const NotoSansHebrew_100Thin = require('./NotoSansHebrew_100Thin.ttf');
export const NotoSansHebrew_200ExtraLight = require('./NotoSansHebrew_200ExtraLight.ttf');
export const NotoSansHebrew_300Light = require('./NotoSansHebrew_300Light.ttf');
export const NotoSansHebrew_400Regular = require('./NotoSansHebrew_400Regular.ttf');
export const NotoSansHebrew_500Medium = require('./NotoSansHebrew_500Medium.ttf');
export const NotoSansHebrew_600SemiBold = require('./NotoSansHebrew_600SemiBold.ttf');
export const NotoSansHebrew_700Bold = require('./NotoSansHebrew_700Bold.ttf');
export const NotoSansHebrew_800ExtraBold = require('./NotoSansHebrew_800ExtraBold.ttf');
export const NotoSansHebrew_900Black = require('./NotoSansHebrew_900Black.ttf');
