// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const SourceCodePro_700Bold = require('./SourceCodePro_700Bold.ttf');
