/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metdata__: Any;
export const Saira_100Thin: number;
export const Saira_200ExtraLight: number;
export const Saira_300Light: number;
export const Saira_400Regular: number;
export const Saira_500Medium: number;
export const Saira_600SemiBold: number;
export const Saira_700Bold: number;
export const Saira_800ExtraBold: number;
export const Saira_900Black: number;
