// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const RobotoCondensed_100Thin = require('./RobotoCondensed_100Thin.ttf');
