// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Platypi_300Light_Italic = require('./Platypi_300Light_Italic.ttf');
