// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const Foldit_100Thin: number;
export const Foldit_200ExtraLight: number;
export const Foldit_300Light: number;
export const Foldit_400Regular: number;
export const Foldit_500Medium: number;
export const Foldit_600SemiBold: number;
export const Foldit_700Bold: number;
export const Foldit_800ExtraBold: number;
export const Foldit_900Black: number;
