// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const NotoSansThaana_100Thin: number;
export const NotoSansThaana_200ExtraLight: number;
export const NotoSansThaana_300Light: number;
export const NotoSansThaana_400Regular: number;
export const NotoSansThaana_500Medium: number;
export const NotoSansThaana_600SemiBold: number;
export const NotoSansThaana_700Bold: number;
export const NotoSansThaana_800ExtraBold: number;
export const NotoSansThaana_900Black: number;
