// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const RubikGlitchPop_400Regular = require('./RubikGlitchPop_400Regular.ttf');
