// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const SofiaSansSemiCondensed_100Thin = require('./100Thin/SofiaSansSemiCondensed_100Thin.ttf');
export const SofiaSansSemiCondensed_200ExtraLight = require('./200ExtraLight/SofiaSansSemiCondensed_200ExtraLight.ttf');
export const SofiaSansSemiCondensed_300Light = require('./300Light/SofiaSansSemiCondensed_300Light.ttf');
export const SofiaSansSemiCondensed_400Regular = require('./400Regular/SofiaSansSemiCondensed_400Regular.ttf');
export const SofiaSansSemiCondensed_500Medium = require('./500Medium/SofiaSansSemiCondensed_500Medium.ttf');
export const SofiaSansSemiCondensed_600SemiBold = require('./600SemiBold/SofiaSansSemiCondensed_600SemiBold.ttf');
export const SofiaSansSemiCondensed_700Bold = require('./700Bold/SofiaSansSemiCondensed_700Bold.ttf');
export const SofiaSansSemiCondensed_800ExtraBold = require('./800ExtraBold/SofiaSansSemiCondensed_800ExtraBold.ttf');
export const SofiaSansSemiCondensed_900Black = require('./900Black/SofiaSansSemiCondensed_900Black.ttf');
export const SofiaSansSemiCondensed_100Thin_Italic = require('./100Thin_Italic/SofiaSansSemiCondensed_100Thin_Italic.ttf');
export const SofiaSansSemiCondensed_200ExtraLight_Italic = require('./200ExtraLight_Italic/SofiaSansSemiCondensed_200ExtraLight_Italic.ttf');
export const SofiaSansSemiCondensed_300Light_Italic = require('./300Light_Italic/SofiaSansSemiCondensed_300Light_Italic.ttf');
export const SofiaSansSemiCondensed_400Regular_Italic = require('./400Regular_Italic/SofiaSansSemiCondensed_400Regular_Italic.ttf');
export const SofiaSansSemiCondensed_500Medium_Italic = require('./500Medium_Italic/SofiaSansSemiCondensed_500Medium_Italic.ttf');
export const SofiaSansSemiCondensed_600SemiBold_Italic = require('./600SemiBold_Italic/SofiaSansSemiCondensed_600SemiBold_Italic.ttf');
export const SofiaSansSemiCondensed_700Bold_Italic = require('./700Bold_Italic/SofiaSansSemiCondensed_700Bold_Italic.ttf');
export const SofiaSansSemiCondensed_800ExtraBold_Italic = require('./800ExtraBold_Italic/SofiaSansSemiCondensed_800ExtraBold_Italic.ttf');
export const SofiaSansSemiCondensed_900Black_Italic = require('./900Black_Italic/SofiaSansSemiCondensed_900Black_Italic.ttf');
