// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Play_400Regular = require('./400Regular/Play_400Regular.ttf');
export const Play_700Bold = require('./700Bold/Play_700Bold.ttf');
