// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const BitcountSingle_600SemiBold = require('./BitcountSingle_600SemiBold.ttf');
