/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export const __fontFamilyName__ = 'Oxygen Mono';
export const __fontFamilyVersion__ = 4;

export const OxygenMono_Regular400 = require('./4a8f20c04bb875a24603d2f13aa59fa112316075b0d8531e06a1212759450a20.ttf');
