/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const GentiumBasic_400Regular = require('./GentiumBasic_400Regular.ttf');
export const GentiumBasic_400Regular_Italic = require('./GentiumBasic_400Regular_Italic.ttf');
export const GentiumBasic_700Bold = require('./GentiumBasic_700Bold.ttf');
export const GentiumBasic_700Bold_Italic = require('./GentiumBasic_700Bold_Italic.ttf');
