// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const IBMPlexSansThai_400Regular = require('./IBMPlexSansThai_400Regular.ttf');
