// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansMalayalam_300Light = require('./NotoSansMalayalam_300Light.ttf');
