/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const STIXTwoText_400Regular: number;
export const STIXTwoText_500Medium: number;
export const STIXTwoText_600SemiBold: number;
export const STIXTwoText_700Bold: number;
export const STIXTwoText_400Regular_Italic: number;
export const STIXTwoText_500Medium_Italic: number;
export const STIXTwoText_600SemiBold_Italic: number;
export const STIXTwoText_700Bold_Italic: number;
