// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Overlock_900Black_Italic = require('./Overlock_900Black_Italic.ttf');
