// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const RopaSans_400Regular_Italic = require('./RopaSans_400Regular_Italic.ttf');
