/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Montserrat_800ExtraBold_Italic = require('./Montserrat_800ExtraBold_Italic.ttf');
