// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const NotoSansKannada_100Thin = require('./100Thin/NotoSansKannada_100Thin.ttf');
export const NotoSansKannada_200ExtraLight = require('./200ExtraLight/NotoSansKannada_200ExtraLight.ttf');
export const NotoSansKannada_300Light = require('./300Light/NotoSansKannada_300Light.ttf');
export const NotoSansKannada_400Regular = require('./400Regular/NotoSansKannada_400Regular.ttf');
export const NotoSansKannada_500Medium = require('./500Medium/NotoSansKannada_500Medium.ttf');
export const NotoSansKannada_600SemiBold = require('./600SemiBold/NotoSansKannada_600SemiBold.ttf');
export const NotoSansKannada_700Bold = require('./700Bold/NotoSansKannada_700Bold.ttf');
export const NotoSansKannada_800ExtraBold = require('./800ExtraBold/NotoSansKannada_800ExtraBold.ttf');
export const NotoSansKannada_900Black = require('./900Black/NotoSansKannada_900Black.ttf');
