// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Chivo_100Thin = require('./100Thin/Chivo_100Thin.ttf');
export const Chivo_200ExtraLight = require('./200ExtraLight/Chivo_200ExtraLight.ttf');
export const Chivo_300Light = require('./300Light/Chivo_300Light.ttf');
export const Chivo_400Regular = require('./400Regular/Chivo_400Regular.ttf');
export const Chivo_500Medium = require('./500Medium/Chivo_500Medium.ttf');
export const Chivo_600SemiBold = require('./600SemiBold/Chivo_600SemiBold.ttf');
export const Chivo_700Bold = require('./700Bold/Chivo_700Bold.ttf');
export const Chivo_800ExtraBold = require('./800ExtraBold/Chivo_800ExtraBold.ttf');
export const Chivo_900Black = require('./900Black/Chivo_900Black.ttf');
export const Chivo_100Thin_Italic = require('./100Thin_Italic/Chivo_100Thin_Italic.ttf');
export const Chivo_200ExtraLight_Italic = require('./200ExtraLight_Italic/Chivo_200ExtraLight_Italic.ttf');
export const Chivo_300Light_Italic = require('./300Light_Italic/Chivo_300Light_Italic.ttf');
export const Chivo_400Regular_Italic = require('./400Regular_Italic/Chivo_400Regular_Italic.ttf');
export const Chivo_500Medium_Italic = require('./500Medium_Italic/Chivo_500Medium_Italic.ttf');
export const Chivo_600SemiBold_Italic = require('./600SemiBold_Italic/Chivo_600SemiBold_Italic.ttf');
export const Chivo_700Bold_Italic = require('./700Bold_Italic/Chivo_700Bold_Italic.ttf');
export const Chivo_800ExtraBold_Italic = require('./800ExtraBold_Italic/Chivo_800ExtraBold_Italic.ttf');
export const Chivo_900Black_Italic = require('./900Black_Italic/Chivo_900Black_Italic.ttf');
