// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const CrimsonPro_200ExtraLight = require('./CrimsonPro_200ExtraLight.ttf');
