/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Mali_ExtraLight200: number;
export const Mali_ExtraLight200_Italic: number;
export const Mali_Light300: number;
export const Mali_Light300_Italic: number;
export const Mali_Regular400: number;
export const Mali_Regular400_Italic: number;
export const Mali_Medium500: number;
export const Mali_Medium500_Italic: number;
export const Mali_SemiBold600: number;
export const Mali_SemiBold600_Italic: number;
export const Mali_Bold700: number;
export const Mali_Bold700_Italic: number;
