// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const ZenMaruGothic_300Light = require('./ZenMaruGothic_300Light.ttf');
export const ZenMaruGothic_400Regular = require('./ZenMaruGothic_400Regular.ttf');
export const ZenMaruGothic_500Medium = require('./ZenMaruGothic_500Medium.ttf');
export const ZenMaruGothic_700Bold = require('./ZenMaruGothic_700Bold.ttf');
export const ZenMaruGothic_900Black = require('./ZenMaruGothic_900Black.ttf');
