// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const RedditMono_200ExtraLight = require('./RedditMono_200ExtraLight.ttf');
export const RedditMono_300Light = require('./RedditMono_300Light.ttf');
export const RedditMono_400Regular = require('./RedditMono_400Regular.ttf');
export const RedditMono_500Medium = require('./RedditMono_500Medium.ttf');
export const RedditMono_600SemiBold = require('./RedditMono_600SemiBold.ttf');
export const RedditMono_700Bold = require('./RedditMono_700Bold.ttf');
export const RedditMono_800ExtraBold = require('./RedditMono_800ExtraBold.ttf');
export const RedditMono_900Black = require('./RedditMono_900Black.ttf');
