// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const NotoSansNKoUnjoined_400Regular = require('./NotoSansNKoUnjoined_400Regular.ttf');
export const NotoSansNKoUnjoined_500Medium = require('./NotoSansNKoUnjoined_500Medium.ttf');
export const NotoSansNKoUnjoined_600SemiBold = require('./NotoSansNKoUnjoined_600SemiBold.ttf');
export const NotoSansNKoUnjoined_700Bold = require('./NotoSansNKoUnjoined_700Bold.ttf');
