// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const FiraSansExtraCondensed_900Black = require('./FiraSansExtraCondensed_900Black.ttf');
