/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const AnekTamil_100Thin: number;
export const AnekTamil_200ExtraLight: number;
export const AnekTamil_300Light: number;
export const AnekTamil_400Regular: number;
export const AnekTamil_500Medium: number;
export const AnekTamil_600SemiBold: number;
export const AnekTamil_700Bold: number;
export const AnekTamil_800ExtraBold: number;
