/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const KiwiMaru_300Light: number;
export const KiwiMaru_400Regular: number;
export const KiwiMaru_500Medium: number;
