// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const KiwiMaru_300Light: number;
export const KiwiMaru_400Regular: number;
export const KiwiMaru_500Medium: number;
