/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteNZ_100Thin = require('./PlaywriteNZ_100Thin.ttf');
export const PlaywriteNZ_200ExtraLight = require('./PlaywriteNZ_200ExtraLight.ttf');
export const PlaywriteNZ_300Light = require('./PlaywriteNZ_300Light.ttf');
export const PlaywriteNZ_400Regular = require('./PlaywriteNZ_400Regular.ttf');
