// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const PlaywriteNZ_100Thin: number;
export const PlaywriteNZ_200ExtraLight: number;
export const PlaywriteNZ_300Light: number;
export const PlaywriteNZ_400Regular: number;
