/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const GentiumBookPlus_400Regular_Italic = require('./GentiumBookPlus_400Regular_Italic.ttf');
