// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansHebrew_900Black = require('./NotoSansHebrew_900Black.ttf');
