// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansInscriptionalParthian_400Regular = require('./NotoSansInscriptionalParthian_400Regular.ttf');
