// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const AzeretMono_600SemiBold = require('./AzeretMono_600SemiBold.ttf');
