// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const PlaywriteNO_100Thin: number;
export const PlaywriteNO_200ExtraLight: number;
export const PlaywriteNO_300Light: number;
export const PlaywriteNO_400Regular: number;
