/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export const __fontFamilyName__ = 'Chelsea Market';
export const __fontFamilyVersion__ = 4;

export const ChelseaMarket_Regular400 = require('./7841b0525f53772efeff1353b0297e9faa176874f84319d11057dfa3d129147b.ttf');
