/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const MonsieurLaDoulaise_Regular400 = require('./def26258142aeeb4021fb91331bd0a7dae943c48caa8b09211393a16ed3c53c9.ttf');
