/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const PlaywriteDESAS_100Thin: number;
export const PlaywriteDESAS_200ExtraLight: number;
export const PlaywriteDESAS_300Light: number;
export const PlaywriteDESAS_400Regular: number;
