// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansMeeteiMayek_600SemiBold = require('./NotoSansMeeteiMayek_600SemiBold.ttf');
