// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansCham_500Medium = require('./NotoSansCham_500Medium.ttf');
