// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const BaskervvilleSC_400Regular = require('./BaskervvilleSC_400Regular.ttf');
