// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const PlaywritePT_100Thin = require('./PlaywritePT_100Thin.ttf');
export const PlaywritePT_200ExtraLight = require('./PlaywritePT_200ExtraLight.ttf');
export const PlaywritePT_300Light = require('./PlaywritePT_300Light.ttf');
export const PlaywritePT_400Regular = require('./PlaywritePT_400Regular.ttf');
