/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Shrikhand_Regular400 = require('./aacb9e67a15ab34c2c3cc3a314bd696f3ef409963bd74b25e61727a3b1414ffc.ttf');
