// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export const __metadata__: any;
export const StackSansNotch_200ExtraLight: number;
export const StackSansNotch_300Light: number;
export const StackSansNotch_400Regular: number;
export const StackSansNotch_500Medium: number;
export const StackSansNotch_600SemiBold: number;
export const StackSansNotch_700Bold: number;
