/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Voltaire_Regular400 = require('./8e446b1dcde5e45745bd6e82bfacf76b313042b232e4fceaa22d745f13e176d3.ttf');
