/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const PlaywriteFRTrad_100Thin: number;
export const PlaywriteFRTrad_200ExtraLight: number;
export const PlaywriteFRTrad_300Light: number;
export const PlaywriteFRTrad_400Regular: number;
