// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansThai_800ExtraBold = require('./NotoSansThai_800ExtraBold.ttf');
