/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Armata_Regular400 = require('./7631b4ae2fae472da8b9d0b46acfec928c9c550e82dbee1685e72f389ab890d9.ttf');
