// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const BitcountGridSingle_100Thin = require('./BitcountGridSingle_100Thin.ttf');
