// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const SchibstedGrotesk_400Regular = require('./400Regular/SchibstedGrotesk_400Regular.ttf');
export const SchibstedGrotesk_500Medium = require('./500Medium/SchibstedGrotesk_500Medium.ttf');
export const SchibstedGrotesk_600SemiBold = require('./600SemiBold/SchibstedGrotesk_600SemiBold.ttf');
export const SchibstedGrotesk_700Bold = require('./700Bold/SchibstedGrotesk_700Bold.ttf');
export const SchibstedGrotesk_800ExtraBold = require('./800ExtraBold/SchibstedGrotesk_800ExtraBold.ttf');
export const SchibstedGrotesk_900Black = require('./900Black/SchibstedGrotesk_900Black.ttf');
export const SchibstedGrotesk_400Regular_Italic = require('./400Regular_Italic/SchibstedGrotesk_400Regular_Italic.ttf');
export const SchibstedGrotesk_500Medium_Italic = require('./500Medium_Italic/SchibstedGrotesk_500Medium_Italic.ttf');
export const SchibstedGrotesk_600SemiBold_Italic = require('./600SemiBold_Italic/SchibstedGrotesk_600SemiBold_Italic.ttf');
export const SchibstedGrotesk_700Bold_Italic = require('./700Bold_Italic/SchibstedGrotesk_700Bold_Italic.ttf');
export const SchibstedGrotesk_800ExtraBold_Italic = require('./800ExtraBold_Italic/SchibstedGrotesk_800ExtraBold_Italic.ttf');
export const SchibstedGrotesk_900Black_Italic = require('./900Black_Italic/SchibstedGrotesk_900Black_Italic.ttf');
