// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSerifDisplay_700Bold = require('./NotoSerifDisplay_700Bold.ttf');
