// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const KodeMono_400Regular = require('./400Regular/KodeMono_400Regular.ttf');
export const KodeMono_500Medium = require('./500Medium/KodeMono_500Medium.ttf');
export const KodeMono_600SemiBold = require('./600SemiBold/KodeMono_600SemiBold.ttf');
export const KodeMono_700Bold = require('./700Bold/KodeMono_700Bold.ttf');
