/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Assistant_ExtraLight200: number;
export const Assistant_Light300: number;
export const Assistant_Regular400: number;
export const Assistant_SemiBold600: number;
export const Assistant_Bold700: number;
export const Assistant_ExtraBold800: number;
