// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const SairaSemiCondensed_400Regular = require('./SairaSemiCondensed_400Regular.ttf');
