// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const FamiljenGrotesk_400Regular = require('./FamiljenGrotesk_400Regular.ttf');
