/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteITTrad_100Thin = require('./PlaywriteITTrad_100Thin.ttf');
export const PlaywriteITTrad_200ExtraLight = require('./PlaywriteITTrad_200ExtraLight.ttf');
export const PlaywriteITTrad_300Light = require('./PlaywriteITTrad_300Light.ttf');
export const PlaywriteITTrad_400Regular = require('./PlaywriteITTrad_400Regular.ttf');
