/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const MuktaMalar_ExtraLight200: number;
export const MuktaMalar_Light300: number;
export const MuktaMalar_Regular400: number;
export const MuktaMalar_Medium500: number;
export const MuktaMalar_SemiBold600: number;
export const MuktaMalar_Bold700: number;
export const MuktaMalar_ExtraBold800: number;
