/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const NotoSansJavanese_400Regular: number;
export const NotoSansJavanese_500Medium: number;
export const NotoSansJavanese_600SemiBold: number;
export const NotoSansJavanese_700Bold: number;
