// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaywriteDEVA_200ExtraLight = require('./PlaywriteDEVA_200ExtraLight.ttf');
