// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const AnekMalayalam_100Thin = require('./AnekMalayalam_100Thin.ttf');
export const AnekMalayalam_200ExtraLight = require('./AnekMalayalam_200ExtraLight.ttf');
export const AnekMalayalam_300Light = require('./AnekMalayalam_300Light.ttf');
export const AnekMalayalam_400Regular = require('./AnekMalayalam_400Regular.ttf');
export const AnekMalayalam_500Medium = require('./AnekMalayalam_500Medium.ttf');
export const AnekMalayalam_600SemiBold = require('./AnekMalayalam_600SemiBold.ttf');
export const AnekMalayalam_700Bold = require('./AnekMalayalam_700Bold.ttf');
export const AnekMalayalam_800ExtraBold = require('./AnekMalayalam_800ExtraBold.ttf');
