// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const Truculenta_100Thin: number;
export const Truculenta_200ExtraLight: number;
export const Truculenta_300Light: number;
export const Truculenta_400Regular: number;
export const Truculenta_500Medium: number;
export const Truculenta_600SemiBold: number;
export const Truculenta_700Bold: number;
export const Truculenta_800ExtraBold: number;
export const Truculenta_900Black: number;
