// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaywriteSKGuides_400Regular = require('./PlaywriteSKGuides_400Regular.ttf');
