// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaywriteUSModernGuides_400Regular = require('./PlaywriteUSModernGuides_400Regular.ttf');
