// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const AtkinsonHyperlegibleNext_400Regular = require('./AtkinsonHyperlegibleNext_400Regular.ttf');
