// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Rufina_400Regular = require('./Rufina_400Regular.ttf');
export const Rufina_700Bold = require('./Rufina_700Bold.ttf');
