// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const TASAExplorer_800ExtraBold = require('./TASAExplorer_800ExtraBold.ttf');
