/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const BigShouldersStencilDisplay_100Thin: number;
export const BigShouldersStencilDisplay_200ExtraLight: number;
export const BigShouldersStencilDisplay_300Light: number;
export const BigShouldersStencilDisplay_400Regular: number;
export const BigShouldersStencilDisplay_500Medium: number;
export const BigShouldersStencilDisplay_600SemiBold: number;
export const BigShouldersStencilDisplay_700Bold: number;
export const BigShouldersStencilDisplay_800ExtraBold: number;
export const BigShouldersStencilDisplay_900Black: number;
