// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const RadioCanada_300Light: number;
export const RadioCanada_400Regular: number;
export const RadioCanada_500Medium: number;
export const RadioCanada_600SemiBold: number;
export const RadioCanada_700Bold: number;
export const RadioCanada_300Light_Italic: number;
export const RadioCanada_400Regular_Italic: number;
export const RadioCanada_500Medium_Italic: number;
export const RadioCanada_600SemiBold_Italic: number;
export const RadioCanada_700Bold_Italic: number;
