// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Oranienbaum_400Regular = require('./Oranienbaum_400Regular.ttf');
