// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Ojuju_200ExtraLight = require('./200ExtraLight/Ojuju_200ExtraLight.ttf');
export const Ojuju_300Light = require('./300Light/Ojuju_300Light.ttf');
export const Ojuju_400Regular = require('./400Regular/Ojuju_400Regular.ttf');
export const Ojuju_500Medium = require('./500Medium/Ojuju_500Medium.ttf');
export const Ojuju_600SemiBold = require('./600SemiBold/Ojuju_600SemiBold.ttf');
export const Ojuju_700Bold = require('./700Bold/Ojuju_700Bold.ttf');
export const Ojuju_800ExtraBold = require('./800ExtraBold/Ojuju_800ExtraBold.ttf');
