/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Telex_Regular400 = require('./75d35766aa0cce57bcd40915972194111fc782787321d3eed8813c7c8d1e9e39.ttf');
