// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansMayanNumerals_400Regular = require('./NotoSansMayanNumerals_400Regular.ttf');
