/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metdata__: Any;
export const Rokkitt_100Thin: number;
export const Rokkitt_200ExtraLight: number;
export const Rokkitt_300Light: number;
export const Rokkitt_400Regular: number;
export const Rokkitt_500Medium: number;
export const Rokkitt_600SemiBold: number;
export const Rokkitt_700Bold: number;
export const Rokkitt_800ExtraBold: number;
export const Rokkitt_900Black: number;
