// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Karla_200ExtraLight = require('./200ExtraLight/Karla_200ExtraLight.ttf');
export const Karla_300Light = require('./300Light/Karla_300Light.ttf');
export const Karla_400Regular = require('./400Regular/Karla_400Regular.ttf');
export const Karla_500Medium = require('./500Medium/Karla_500Medium.ttf');
export const Karla_600SemiBold = require('./600SemiBold/Karla_600SemiBold.ttf');
export const Karla_700Bold = require('./700Bold/Karla_700Bold.ttf');
export const Karla_800ExtraBold = require('./800ExtraBold/Karla_800ExtraBold.ttf');
export const Karla_200ExtraLight_Italic = require('./200ExtraLight_Italic/Karla_200ExtraLight_Italic.ttf');
export const Karla_300Light_Italic = require('./300Light_Italic/Karla_300Light_Italic.ttf');
export const Karla_400Regular_Italic = require('./400Regular_Italic/Karla_400Regular_Italic.ttf');
export const Karla_500Medium_Italic = require('./500Medium_Italic/Karla_500Medium_Italic.ttf');
export const Karla_600SemiBold_Italic = require('./600SemiBold_Italic/Karla_600SemiBold_Italic.ttf');
export const Karla_700Bold_Italic = require('./700Bold_Italic/Karla_700Bold_Italic.ttf');
export const Karla_800ExtraBold_Italic = require('./800ExtraBold_Italic/Karla_800ExtraBold_Italic.ttf');
