// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaywriteFRModerneGuides_400Regular = require('./PlaywriteFRModerneGuides_400Regular.ttf');
