/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const NotoSansAdlamUnjoined_600SemiBold = require('./NotoSansAdlamUnjoined_600SemiBold.ttf');
