// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Baskervville_400Regular = require('./400Regular/Baskervville_400Regular.ttf');
export const Baskervville_400Regular_Italic = require('./400Regular_Italic/Baskervville_400Regular_Italic.ttf');
