/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const MerriweatherSans_300Light_Italic = require('./MerriweatherSans_300Light_Italic.ttf');
