// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Namdhinggo_400Regular = require('./Namdhinggo_400Regular.ttf');
export const Namdhinggo_500Medium = require('./Namdhinggo_500Medium.ttf');
export const Namdhinggo_600SemiBold = require('./Namdhinggo_600SemiBold.ttf');
export const Namdhinggo_700Bold = require('./Namdhinggo_700Bold.ttf');
export const Namdhinggo_800ExtraBold = require('./Namdhinggo_800ExtraBold.ttf');
