/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const DonegalOne_Regular400 = require('./75cadf3ba9559e8ba497b68a3e7695d2c733b4ce2264119f7f181974902025ba.ttf');
