// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const YsabeauOffice_500Medium_Italic = require('./YsabeauOffice_500Medium_Italic.ttf');
