/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const YsabeauOffice_500Medium_Italic = require('./YsabeauOffice_500Medium_Italic.ttf');
