// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const RedHatMono_400Regular = require('./RedHatMono_400Regular.ttf');
