// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Trirong_100Thin_Italic = require('./Trirong_100Thin_Italic.ttf');
