/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const PlaywriteCO_100Thin: number;
export const PlaywriteCO_200ExtraLight: number;
export const PlaywriteCO_300Light: number;
export const PlaywriteCO_400Regular: number;
