/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Carme_Regular400 = require('./79973fb109b078d0e49d90287e9f6527dc8829c6076c878ed07743d78cfb988b.ttf');
