/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const IBMPlexSansCondensed_100Thin = require('./IBMPlexSansCondensed_100Thin.ttf');
