// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansMono_500Medium = require('./NotoSansMono_500Medium.ttf');
