// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const BitcountGridDouble_400Regular = require('./BitcountGridDouble_400Regular.ttf');
