// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const EpundaSans_900Black_Italic = require('./EpundaSans_900Black_Italic.ttf');
