// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Scada_400Regular = require('./Scada_400Regular.ttf');
export const Scada_400Regular_Italic = require('./Scada_400Regular_Italic.ttf');
export const Scada_700Bold = require('./Scada_700Bold.ttf');
export const Scada_700Bold_Italic = require('./Scada_700Bold_Italic.ttf');
