// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Scada_400Regular = require('./400Regular/Scada_400Regular.ttf');
export const Scada_400Regular_Italic = require('./400Regular_Italic/Scada_400Regular_Italic.ttf');
export const Scada_700Bold = require('./700Bold/Scada_700Bold.ttf');
export const Scada_700Bold_Italic = require('./700Bold_Italic/Scada_700Bold_Italic.ttf');
