/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Niramit_ExtraLight200: number;
export const Niramit_ExtraLight200_Italic: number;
export const Niramit_Light300: number;
export const Niramit_Light300_Italic: number;
export const Niramit_Regular400: number;
export const Niramit_Regular400_Italic: number;
export const Niramit_Medium500: number;
export const Niramit_Medium500_Italic: number;
export const Niramit_SemiBold600: number;
export const Niramit_SemiBold600_Italic: number;
export const Niramit_Bold700: number;
export const Niramit_Bold700_Italic: number;
