// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const CormorantSC_300Light = require('./300Light/CormorantSC_300Light.ttf');
export const CormorantSC_400Regular = require('./400Regular/CormorantSC_400Regular.ttf');
export const CormorantSC_500Medium = require('./500Medium/CormorantSC_500Medium.ttf');
export const CormorantSC_600SemiBold = require('./600SemiBold/CormorantSC_600SemiBold.ttf');
export const CormorantSC_700Bold = require('./700Bold/CormorantSC_700Bold.ttf');
