/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const CormorantSC_300Light: number;
export const CormorantSC_400Regular: number;
export const CormorantSC_500Medium: number;
export const CormorantSC_600SemiBold: number;
export const CormorantSC_700Bold: number;
