// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const KohSantepheap_100Thin = require('./KohSantepheap_100Thin.ttf');
