// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const KleeOne_400Regular = require('./KleeOne_400Regular.ttf');
export const KleeOne_600SemiBold = require('./KleeOne_600SemiBold.ttf');
