/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const BalooChettan2_400Regular = require('./BalooChettan2_400Regular.ttf');
export const BalooChettan2_500Medium = require('./BalooChettan2_500Medium.ttf');
export const BalooChettan2_600SemiBold = require('./BalooChettan2_600SemiBold.ttf');
export const BalooChettan2_700Bold = require('./BalooChettan2_700Bold.ttf');
export const BalooChettan2_800ExtraBold = require('./BalooChettan2_800ExtraBold.ttf');
