// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const AtkinsonHyperlegibleMono_800ExtraBold_Italic = require('./AtkinsonHyperlegibleMono_800ExtraBold_Italic.ttf');
