// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const TsukimiRounded_300Light = require('./TsukimiRounded_300Light.ttf');
export const TsukimiRounded_400Regular = require('./TsukimiRounded_400Regular.ttf');
export const TsukimiRounded_500Medium = require('./TsukimiRounded_500Medium.ttf');
export const TsukimiRounded_600SemiBold = require('./TsukimiRounded_600SemiBold.ttf');
export const TsukimiRounded_700Bold = require('./TsukimiRounded_700Bold.ttf');
