// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const SansitaSwashed_800ExtraBold = require('./SansitaSwashed_800ExtraBold.ttf');
