// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Tagesschrift_400Regular = require('./Tagesschrift_400Regular.ttf');
