// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaywriteAUSA_400Regular = require('./PlaywriteAUSA_400Regular.ttf');
