// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const SourceSerif4_600SemiBold = require('./SourceSerif4_600SemiBold.ttf');
