// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const WixMadeforText_800ExtraBold = require('./WixMadeforText_800ExtraBold.ttf');
