/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const NotoSansSymbols_200ExtraLight = require('./NotoSansSymbols_200ExtraLight.ttf');
