// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansOlChiki_500Medium = require('./NotoSansOlChiki_500Medium.ttf');
