// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const ChocolateClassicalSans_400Regular = require('./ChocolateClassicalSans_400Regular.ttf');
