// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Fraunces_700Bold_Italic = require('./Fraunces_700Bold_Italic.ttf');
