// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansKannada_700Bold = require('./NotoSansKannada_700Bold.ttf');
