/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const NotoSerifArmenian_400Regular = require('./NotoSerifArmenian_400Regular.ttf');
