/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const PlaywriteDESASGuides_400Regular = require('./PlaywriteDESASGuides_400Regular.ttf');
