// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const Labrada_100Thin: number;
export const Labrada_200ExtraLight: number;
export const Labrada_300Light: number;
export const Labrada_400Regular: number;
export const Labrada_500Medium: number;
export const Labrada_600SemiBold: number;
export const Labrada_700Bold: number;
export const Labrada_800ExtraBold: number;
export const Labrada_900Black: number;
export const Labrada_100Thin_Italic: number;
export const Labrada_200ExtraLight_Italic: number;
export const Labrada_300Light_Italic: number;
export const Labrada_400Regular_Italic: number;
export const Labrada_500Medium_Italic: number;
export const Labrada_600SemiBold_Italic: number;
export const Labrada_700Bold_Italic: number;
export const Labrada_800ExtraBold_Italic: number;
export const Labrada_900Black_Italic: number;
