// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Labrada_100Thin = require('./Labrada_100Thin.ttf');
export const Labrada_200ExtraLight = require('./Labrada_200ExtraLight.ttf');
export const Labrada_300Light = require('./Labrada_300Light.ttf');
export const Labrada_400Regular = require('./Labrada_400Regular.ttf');
export const Labrada_500Medium = require('./Labrada_500Medium.ttf');
export const Labrada_600SemiBold = require('./Labrada_600SemiBold.ttf');
export const Labrada_700Bold = require('./Labrada_700Bold.ttf');
export const Labrada_800ExtraBold = require('./Labrada_800ExtraBold.ttf');
export const Labrada_900Black = require('./Labrada_900Black.ttf');
export const Labrada_100Thin_Italic = require('./Labrada_100Thin_Italic.ttf');
export const Labrada_200ExtraLight_Italic = require('./Labrada_200ExtraLight_Italic.ttf');
export const Labrada_300Light_Italic = require('./Labrada_300Light_Italic.ttf');
export const Labrada_400Regular_Italic = require('./Labrada_400Regular_Italic.ttf');
export const Labrada_500Medium_Italic = require('./Labrada_500Medium_Italic.ttf');
export const Labrada_600SemiBold_Italic = require('./Labrada_600SemiBold_Italic.ttf');
export const Labrada_700Bold_Italic = require('./Labrada_700Bold_Italic.ttf');
export const Labrada_800ExtraBold_Italic = require('./Labrada_800ExtraBold_Italic.ttf');
export const Labrada_900Black_Italic = require('./Labrada_900Black_Italic.ttf');
