// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Alyamama_300Light = require('./300Light/Alyamama_300Light.ttf');
export const Alyamama_400Regular = require('./400Regular/Alyamama_400Regular.ttf');
export const Alyamama_500Medium = require('./500Medium/Alyamama_500Medium.ttf');
export const Alyamama_600SemiBold = require('./600SemiBold/Alyamama_600SemiBold.ttf');
export const Alyamama_700Bold = require('./700Bold/Alyamama_700Bold.ttf');
export const Alyamama_800ExtraBold = require('./800ExtraBold/Alyamama_800ExtraBold.ttf');
export const Alyamama_900Black = require('./900Black/Alyamama_900Black.ttf');
