/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const Athiti_200ExtraLight: number;
export const Athiti_300Light: number;
export const Athiti_400Regular: number;
export const Athiti_500Medium: number;
export const Athiti_600SemiBold: number;
export const Athiti_700Bold: number;
