/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Athiti_ExtraLight200: number;
export const Athiti_Light300: number;
export const Athiti_Regular400: number;
export const Athiti_Medium500: number;
export const Athiti_SemiBold600: number;
export const Athiti_Bold700: number;
