/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const NotoSansMedefaidrin_400Regular = require('./NotoSansMedefaidrin_400Regular.ttf');
export const NotoSansMedefaidrin_500Medium = require('./NotoSansMedefaidrin_500Medium.ttf');
export const NotoSansMedefaidrin_600SemiBold = require('./NotoSansMedefaidrin_600SemiBold.ttf');
export const NotoSansMedefaidrin_700Bold = require('./NotoSansMedefaidrin_700Bold.ttf');
