// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Pliant_200ExtraLight_Italic = require('./Pliant_200ExtraLight_Italic.ttf');
