// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const PixelifySans_400Regular = require('./PixelifySans_400Regular.ttf');
export const PixelifySans_500Medium = require('./PixelifySans_500Medium.ttf');
export const PixelifySans_600SemiBold = require('./PixelifySans_600SemiBold.ttf');
export const PixelifySans_700Bold = require('./PixelifySans_700Bold.ttf');
