// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const ScoutieSans_600SemiBold = require('./ScoutieSans_600SemiBold.ttf');
