// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Farro_300Light = require('./300Light/Farro_300Light.ttf');
export const Farro_400Regular = require('./400Regular/Farro_400Regular.ttf');
export const Farro_500Medium = require('./500Medium/Farro_500Medium.ttf');
export const Farro_700Bold = require('./700Bold/Farro_700Bold.ttf');
