// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const RobotoCondensed_800ExtraBold = require('./RobotoCondensed_800ExtraBold.ttf');
