/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const AtkinsonHyperlegibleMono_600SemiBold = require('./AtkinsonHyperlegibleMono_600SemiBold.ttf');
