/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const BalooBhaijaan2_400Regular = require('./BalooBhaijaan2_400Regular.ttf');
export const BalooBhaijaan2_500Medium = require('./BalooBhaijaan2_500Medium.ttf');
export const BalooBhaijaan2_600SemiBold = require('./BalooBhaijaan2_600SemiBold.ttf');
export const BalooBhaijaan2_700Bold = require('./BalooBhaijaan2_700Bold.ttf');
export const BalooBhaijaan2_800ExtraBold = require('./BalooBhaijaan2_800ExtraBold.ttf');
