// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const ChakraPetch_300Light_Italic = require('./ChakraPetch_300Light_Italic.ttf');
