/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const PTSerif_Regular400: number;
export const PTSerif_Regular400_Italic: number;
export const PTSerif_Bold700: number;
export const PTSerif_Bold700_Italic: number;
