// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const Belanosima_400Regular: number;
export const Belanosima_600SemiBold: number;
export const Belanosima_700Bold: number;
