// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const PontanoSans_300Light: number;
export const PontanoSans_400Regular: number;
export const PontanoSans_500Medium: number;
export const PontanoSans_600SemiBold: number;
export const PontanoSans_700Bold: number;
