/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Sansita_Regular400: number;
export const Sansita_Regular400_Italic: number;
export const Sansita_Bold700: number;
export const Sansita_Bold700_Italic: number;
export const Sansita_ExtraBold800: number;
export const Sansita_ExtraBold800_Italic: number;
export const Sansita_Black900: number;
export const Sansita_Black900_Italic: number;
