// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Baskervville_400Regular = require('./Baskervville_400Regular.ttf');
