// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const LibreFranklin_200ExtraLight = require('./LibreFranklin_200ExtraLight.ttf');
