// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const LexendExa_100Thin = require('./100Thin/LexendExa_100Thin.ttf');
export const LexendExa_200ExtraLight = require('./200ExtraLight/LexendExa_200ExtraLight.ttf');
export const LexendExa_300Light = require('./300Light/LexendExa_300Light.ttf');
export const LexendExa_400Regular = require('./400Regular/LexendExa_400Regular.ttf');
export const LexendExa_500Medium = require('./500Medium/LexendExa_500Medium.ttf');
export const LexendExa_600SemiBold = require('./600SemiBold/LexendExa_600SemiBold.ttf');
export const LexendExa_700Bold = require('./700Bold/LexendExa_700Bold.ttf');
export const LexendExa_800ExtraBold = require('./800ExtraBold/LexendExa_800ExtraBold.ttf');
export const LexendExa_900Black = require('./900Black/LexendExa_900Black.ttf');
