// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const LexendExa_100Thin: number;
export const LexendExa_200ExtraLight: number;
export const LexendExa_300Light: number;
export const LexendExa_400Regular: number;
export const LexendExa_500Medium: number;
export const LexendExa_600SemiBold: number;
export const LexendExa_700Bold: number;
export const LexendExa_800ExtraBold: number;
export const LexendExa_900Black: number;
