// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const CinzelDecorative_400Regular = require('./CinzelDecorative_400Regular.ttf');
