// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const AnekDevanagari_200ExtraLight = require('./AnekDevanagari_200ExtraLight.ttf');
