// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const NotoSerifKhojki_400Regular = require('./NotoSerifKhojki_400Regular.ttf');
export const NotoSerifKhojki_500Medium = require('./NotoSerifKhojki_500Medium.ttf');
export const NotoSerifKhojki_600SemiBold = require('./NotoSerifKhojki_600SemiBold.ttf');
export const NotoSerifKhojki_700Bold = require('./NotoSerifKhojki_700Bold.ttf');
