// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const SourceSans3_200ExtraLight = require('./SourceSans3_200ExtraLight.ttf');
