/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const DarkerGrotesque_Light300: number;
export const DarkerGrotesque_Regular400: number;
export const DarkerGrotesque_Medium500: number;
export const DarkerGrotesque_SemiBold600: number;
export const DarkerGrotesque_Bold700: number;
export const DarkerGrotesque_ExtraBold800: number;
export const DarkerGrotesque_Black900: number;
