// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const AzeretMono_100Thin = require('./100Thin/AzeretMono_100Thin.ttf');
export const AzeretMono_200ExtraLight = require('./200ExtraLight/AzeretMono_200ExtraLight.ttf');
export const AzeretMono_300Light = require('./300Light/AzeretMono_300Light.ttf');
export const AzeretMono_400Regular = require('./400Regular/AzeretMono_400Regular.ttf');
export const AzeretMono_500Medium = require('./500Medium/AzeretMono_500Medium.ttf');
export const AzeretMono_600SemiBold = require('./600SemiBold/AzeretMono_600SemiBold.ttf');
export const AzeretMono_700Bold = require('./700Bold/AzeretMono_700Bold.ttf');
export const AzeretMono_800ExtraBold = require('./800ExtraBold/AzeretMono_800ExtraBold.ttf');
export const AzeretMono_900Black = require('./900Black/AzeretMono_900Black.ttf');
export const AzeretMono_100Thin_Italic = require('./100Thin_Italic/AzeretMono_100Thin_Italic.ttf');
export const AzeretMono_200ExtraLight_Italic = require('./200ExtraLight_Italic/AzeretMono_200ExtraLight_Italic.ttf');
export const AzeretMono_300Light_Italic = require('./300Light_Italic/AzeretMono_300Light_Italic.ttf');
export const AzeretMono_400Regular_Italic = require('./400Regular_Italic/AzeretMono_400Regular_Italic.ttf');
export const AzeretMono_500Medium_Italic = require('./500Medium_Italic/AzeretMono_500Medium_Italic.ttf');
export const AzeretMono_600SemiBold_Italic = require('./600SemiBold_Italic/AzeretMono_600SemiBold_Italic.ttf');
export const AzeretMono_700Bold_Italic = require('./700Bold_Italic/AzeretMono_700Bold_Italic.ttf');
export const AzeretMono_800ExtraBold_Italic = require('./800ExtraBold_Italic/AzeretMono_800ExtraBold_Italic.ttf');
export const AzeretMono_900Black_Italic = require('./900Black_Italic/AzeretMono_900Black_Italic.ttf');
