// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const StackSansText_400Regular = require('./StackSansText_400Regular.ttf');
