/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const DynaPuff_400Regular = require('./DynaPuff_400Regular.ttf');
export const DynaPuff_500Medium = require('./DynaPuff_500Medium.ttf');
export const DynaPuff_600SemiBold = require('./DynaPuff_600SemiBold.ttf');
export const DynaPuff_700Bold = require('./DynaPuff_700Bold.ttf');
