/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const NotoSansZanabazarSquare_400Regular = require('./NotoSansZanabazarSquare_400Regular.ttf');
