/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const EduVICWANTBeginner_600SemiBold = require('./EduVICWANTBeginner_600SemiBold.ttf');
