/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const NotoSansCherokee_600SemiBold = require('./NotoSansCherokee_600SemiBold.ttf');
