// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansMeeteiMayek_400Regular = require('./NotoSansMeeteiMayek_400Regular.ttf');
