// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const PlaywriteMX_100Thin = require('./PlaywriteMX_100Thin.ttf');
export const PlaywriteMX_200ExtraLight = require('./PlaywriteMX_200ExtraLight.ttf');
export const PlaywriteMX_300Light = require('./PlaywriteMX_300Light.ttf');
export const PlaywriteMX_400Regular = require('./PlaywriteMX_400Regular.ttf');
