// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NewTegomin_400Regular = require('./NewTegomin_400Regular.ttf');
