// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSerifThai_300Light = require('./NotoSerifThai_300Light.ttf');
