/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const DMSerifDisplay_Regular400: number;
export const DMSerifDisplay_Regular400_Italic: number;
