// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const NotoSerifBengali_100Thin = require('./NotoSerifBengali_100Thin.ttf');
export const NotoSerifBengali_200ExtraLight = require('./NotoSerifBengali_200ExtraLight.ttf');
export const NotoSerifBengali_300Light = require('./NotoSerifBengali_300Light.ttf');
export const NotoSerifBengali_400Regular = require('./NotoSerifBengali_400Regular.ttf');
export const NotoSerifBengali_500Medium = require('./NotoSerifBengali_500Medium.ttf');
export const NotoSerifBengali_600SemiBold = require('./NotoSerifBengali_600SemiBold.ttf');
export const NotoSerifBengali_700Bold = require('./NotoSerifBengali_700Bold.ttf');
export const NotoSerifBengali_800ExtraBold = require('./NotoSerifBengali_800ExtraBold.ttf');
export const NotoSerifBengali_900Black = require('./NotoSerifBengali_900Black.ttf');
