// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Jacquard12_400Regular = require('./Jacquard12_400Regular.ttf');
