// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const AlumniSans_100Thin = require('./100Thin/AlumniSans_100Thin.ttf');
export const AlumniSans_200ExtraLight = require('./200ExtraLight/AlumniSans_200ExtraLight.ttf');
export const AlumniSans_300Light = require('./300Light/AlumniSans_300Light.ttf');
export const AlumniSans_400Regular = require('./400Regular/AlumniSans_400Regular.ttf');
export const AlumniSans_500Medium = require('./500Medium/AlumniSans_500Medium.ttf');
export const AlumniSans_600SemiBold = require('./600SemiBold/AlumniSans_600SemiBold.ttf');
export const AlumniSans_700Bold = require('./700Bold/AlumniSans_700Bold.ttf');
export const AlumniSans_800ExtraBold = require('./800ExtraBold/AlumniSans_800ExtraBold.ttf');
export const AlumniSans_900Black = require('./900Black/AlumniSans_900Black.ttf');
export const AlumniSans_100Thin_Italic = require('./100Thin_Italic/AlumniSans_100Thin_Italic.ttf');
export const AlumniSans_200ExtraLight_Italic = require('./200ExtraLight_Italic/AlumniSans_200ExtraLight_Italic.ttf');
export const AlumniSans_300Light_Italic = require('./300Light_Italic/AlumniSans_300Light_Italic.ttf');
export const AlumniSans_400Regular_Italic = require('./400Regular_Italic/AlumniSans_400Regular_Italic.ttf');
export const AlumniSans_500Medium_Italic = require('./500Medium_Italic/AlumniSans_500Medium_Italic.ttf');
export const AlumniSans_600SemiBold_Italic = require('./600SemiBold_Italic/AlumniSans_600SemiBold_Italic.ttf');
export const AlumniSans_700Bold_Italic = require('./700Bold_Italic/AlumniSans_700Bold_Italic.ttf');
export const AlumniSans_800ExtraBold_Italic = require('./800ExtraBold_Italic/AlumniSans_800ExtraBold_Italic.ttf');
export const AlumniSans_900Black_Italic = require('./900Black_Italic/AlumniSans_900Black_Italic.ttf');
