/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const AlumniSans_100Thin: number;
export const AlumniSans_200ExtraLight: number;
export const AlumniSans_300Light: number;
export const AlumniSans_400Regular: number;
export const AlumniSans_500Medium: number;
export const AlumniSans_600SemiBold: number;
export const AlumniSans_700Bold: number;
export const AlumniSans_800ExtraBold: number;
export const AlumniSans_900Black: number;
export const AlumniSans_100Thin_Italic: number;
export const AlumniSans_200ExtraLight_Italic: number;
export const AlumniSans_300Light_Italic: number;
export const AlumniSans_400Regular_Italic: number;
export const AlumniSans_500Medium_Italic: number;
export const AlumniSans_600SemiBold_Italic: number;
export const AlumniSans_700Bold_Italic: number;
export const AlumniSans_800ExtraBold_Italic: number;
export const AlumniSans_900Black_Italic: number;
