// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const AROneSans_400Regular = require('./AROneSans_400Regular.ttf');
export const AROneSans_500Medium = require('./AROneSans_500Medium.ttf');
export const AROneSans_600SemiBold = require('./AROneSans_600SemiBold.ttf');
export const AROneSans_700Bold = require('./AROneSans_700Bold.ttf');
