// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const BIZUDGothic_400Regular = require('./BIZUDGothic_400Regular.ttf');
