/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const TaiHeritagePro_400Regular = require('./TaiHeritagePro_400Regular.ttf');
export const TaiHeritagePro_700Bold = require('./TaiHeritagePro_700Bold.ttf');
