/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteVN_100Thin = require('./PlaywriteVN_100Thin.ttf');
export const PlaywriteVN_200ExtraLight = require('./PlaywriteVN_200ExtraLight.ttf');
export const PlaywriteVN_300Light = require('./PlaywriteVN_300Light.ttf');
export const PlaywriteVN_400Regular = require('./PlaywriteVN_400Regular.ttf');
