/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const DaiBannaSIL_300Light: number;
export const DaiBannaSIL_300Light_Italic: number;
export const DaiBannaSIL_400Regular: number;
export const DaiBannaSIL_400Regular_Italic: number;
export const DaiBannaSIL_500Medium: number;
export const DaiBannaSIL_500Medium_Italic: number;
export const DaiBannaSIL_600SemiBold: number;
export const DaiBannaSIL_600SemiBold_Italic: number;
export const DaiBannaSIL_700Bold: number;
export const DaiBannaSIL_700Bold_Italic: number;
