// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const DancingScript_700Bold = require('./DancingScript_700Bold.ttf');
