/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const FanwoodText_Regular400: number;
export const FanwoodText_Regular400_Italic: number;
