// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const FanwoodText_400Regular = require('./FanwoodText_400Regular.ttf');
export const FanwoodText_400Regular_Italic = require('./FanwoodText_400Regular_Italic.ttf');
