// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const NotoSansThaiLooped_100Thin: number;
export const NotoSansThaiLooped_200ExtraLight: number;
export const NotoSansThaiLooped_300Light: number;
export const NotoSansThaiLooped_400Regular: number;
export const NotoSansThaiLooped_500Medium: number;
export const NotoSansThaiLooped_600SemiBold: number;
export const NotoSansThaiLooped_700Bold: number;
export const NotoSansThaiLooped_800ExtraBold: number;
export const NotoSansThaiLooped_900Black: number;
