/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const MuseoModerno_900Black_Italic = require('./MuseoModerno_900Black_Italic.ttf');
