/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Candal_Regular400 = require('./2e16795a5489340834dda623038868a2e7f48f4bc0f154f98c1a1962894a2598.ttf');
