// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const FascinateInline_400Regular = require('./FascinateInline_400Regular.ttf');
