// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSerifEthiopic_300Light = require('./NotoSerifEthiopic_300Light.ttf');
