// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansJavanese_600SemiBold = require('./NotoSansJavanese_600SemiBold.ttf');
