/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const NotoSansKayahLi_400Regular: number;
export const NotoSansKayahLi_500Medium: number;
export const NotoSansKayahLi_600SemiBold: number;
export const NotoSansKayahLi_700Bold: number;
