/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export const __fontFamilyName__ = 'Delius Swash Caps';
export const __fontFamilyVersion__ = 8;

export const DeliusSwashCaps_Regular400 = require('./8a724c6c792da2cb102b6583bf9f9ed02312ab78bbeeb3c6a6efb9ddb096ae29.ttf');
