/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const GeostarFill_Regular400 = require('./4be1af95d7c9c5f412f0bd7ca965a79a3691840d102dc4d542068f95fc8a04ac.ttf');
