/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const Srisakdi_400Regular = require('./Srisakdi_400Regular.ttf');
export const Srisakdi_700Bold = require('./Srisakdi_700Bold.ttf');
