/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const NotoSerifSC_200ExtraLight: number;
export const NotoSerifSC_300Light: number;
export const NotoSerifSC_400Regular: number;
export const NotoSerifSC_500Medium: number;
export const NotoSerifSC_600SemiBold: number;
export const NotoSerifSC_700Bold: number;
export const NotoSerifSC_900Black: number;
