/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const OleoScript_400Regular = require('./OleoScript_400Regular.ttf');
export const OleoScript_700Bold = require('./OleoScript_700Bold.ttf');
