// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const FiraSansExtraCondensed_300Light = require('./FiraSansExtraCondensed_300Light.ttf');
