/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const NotoSansMono_100Thin: number;
export const NotoSansMono_200ExtraLight: number;
export const NotoSansMono_300Light: number;
export const NotoSansMono_400Regular: number;
export const NotoSansMono_500Medium: number;
export const NotoSansMono_600SemiBold: number;
export const NotoSansMono_700Bold: number;
export const NotoSansMono_800ExtraBold: number;
export const NotoSansMono_900Black: number;
