// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Kufam_600SemiBold_Italic = require('./Kufam_600SemiBold_Italic.ttf');
