// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Cousine_700Bold_Italic = require('./Cousine_700Bold_Italic.ttf');
