/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const RugeBoogie_Regular400 = require('./91717da896d2b742035d5a0b0ba8e6e4eb616fa3040d3ba55be14c2e92b1aa8f.ttf');
