/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metdata__: Any;
export const RedHatText_400Regular: number;
export const RedHatText_400Regular_Italic: number;
export const RedHatText_500Medium: number;
export const RedHatText_500Medium_Italic: number;
export const RedHatText_700Bold: number;
export const RedHatText_700Bold_Italic: number;
