// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaywriteUSTrad_200ExtraLight = require('./PlaywriteUSTrad_200ExtraLight.ttf');
