// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const SpectralSC_800ExtraBold = require('./SpectralSC_800ExtraBold.ttf');
