// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const LexendPeta_100Thin = require('./100Thin/LexendPeta_100Thin.ttf');
export const LexendPeta_200ExtraLight = require('./200ExtraLight/LexendPeta_200ExtraLight.ttf');
export const LexendPeta_300Light = require('./300Light/LexendPeta_300Light.ttf');
export const LexendPeta_400Regular = require('./400Regular/LexendPeta_400Regular.ttf');
export const LexendPeta_500Medium = require('./500Medium/LexendPeta_500Medium.ttf');
export const LexendPeta_600SemiBold = require('./600SemiBold/LexendPeta_600SemiBold.ttf');
export const LexendPeta_700Bold = require('./700Bold/LexendPeta_700Bold.ttf');
export const LexendPeta_800ExtraBold = require('./800ExtraBold/LexendPeta_800ExtraBold.ttf');
export const LexendPeta_900Black = require('./900Black/LexendPeta_900Black.ttf');
