/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const NotoSansGujarati_200ExtraLight = require('./NotoSansGujarati_200ExtraLight.ttf');
