// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Jost_100Thin = require('./100Thin/Jost_100Thin.ttf');
export const Jost_200ExtraLight = require('./200ExtraLight/Jost_200ExtraLight.ttf');
export const Jost_300Light = require('./300Light/Jost_300Light.ttf');
export const Jost_400Regular = require('./400Regular/Jost_400Regular.ttf');
export const Jost_500Medium = require('./500Medium/Jost_500Medium.ttf');
export const Jost_600SemiBold = require('./600SemiBold/Jost_600SemiBold.ttf');
export const Jost_700Bold = require('./700Bold/Jost_700Bold.ttf');
export const Jost_800ExtraBold = require('./800ExtraBold/Jost_800ExtraBold.ttf');
export const Jost_900Black = require('./900Black/Jost_900Black.ttf');
export const Jost_100Thin_Italic = require('./100Thin_Italic/Jost_100Thin_Italic.ttf');
export const Jost_200ExtraLight_Italic = require('./200ExtraLight_Italic/Jost_200ExtraLight_Italic.ttf');
export const Jost_300Light_Italic = require('./300Light_Italic/Jost_300Light_Italic.ttf');
export const Jost_400Regular_Italic = require('./400Regular_Italic/Jost_400Regular_Italic.ttf');
export const Jost_500Medium_Italic = require('./500Medium_Italic/Jost_500Medium_Italic.ttf');
export const Jost_600SemiBold_Italic = require('./600SemiBold_Italic/Jost_600SemiBold_Italic.ttf');
export const Jost_700Bold_Italic = require('./700Bold_Italic/Jost_700Bold_Italic.ttf');
export const Jost_800ExtraBold_Italic = require('./800ExtraBold_Italic/Jost_800ExtraBold_Italic.ttf');
export const Jost_900Black_Italic = require('./900Black_Italic/Jost_900Black_Italic.ttf');
