// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NovaSquare_400Regular = require('./NovaSquare_400Regular.ttf');
