/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const NunitoSans_600SemiBold_Italic = require('./NunitoSans_600SemiBold_Italic.ttf');
