/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Amaranth_Regular400 = require('./4b8c69a7d5f0b230b1b010da8da3ad4ccb84f4dff4a1247a14af83392c9ecf64.ttf');
export const Amaranth_Regular400_Italic = require('./359639014bf096771cbebb373f2d347f8e1b44a2ef2b48556e1a21289dbc7eb5.ttf');
export const Amaranth_Bold700 = require('./9b35625ebc301f471cd70df7575f4fc81597a8ab27dc321418707c40d8a99616.ttf');
export const Amaranth_Bold700_Italic = require('./48c74968a6ddedd92d0c4d4e05959d24a1ae124fce3ab60c793c5a331dddee10.ttf');
