// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaywriteITModerna_200ExtraLight = require('./PlaywriteITModerna_200ExtraLight.ttf');
