// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSerifGeorgian_600SemiBold = require('./NotoSerifGeorgian_600SemiBold.ttf');
