// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const MarckScript_400Regular = require('./MarckScript_400Regular.ttf');
