/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const Exo_100Thin = require('./Exo_100Thin.ttf');
export const Exo_200ExtraLight = require('./Exo_200ExtraLight.ttf');
export const Exo_300Light = require('./Exo_300Light.ttf');
export const Exo_400Regular = require('./Exo_400Regular.ttf');
export const Exo_500Medium = require('./Exo_500Medium.ttf');
export const Exo_600SemiBold = require('./Exo_600SemiBold.ttf');
export const Exo_700Bold = require('./Exo_700Bold.ttf');
export const Exo_800ExtraBold = require('./Exo_800ExtraBold.ttf');
export const Exo_900Black = require('./Exo_900Black.ttf');
export const Exo_100Thin_Italic = require('./Exo_100Thin_Italic.ttf');
export const Exo_200ExtraLight_Italic = require('./Exo_200ExtraLight_Italic.ttf');
export const Exo_300Light_Italic = require('./Exo_300Light_Italic.ttf');
export const Exo_400Regular_Italic = require('./Exo_400Regular_Italic.ttf');
export const Exo_500Medium_Italic = require('./Exo_500Medium_Italic.ttf');
export const Exo_600SemiBold_Italic = require('./Exo_600SemiBold_Italic.ttf');
export const Exo_700Bold_Italic = require('./Exo_700Bold_Italic.ttf');
export const Exo_800ExtraBold_Italic = require('./Exo_800ExtraBold_Italic.ttf');
export const Exo_900Black_Italic = require('./Exo_900Black_Italic.ttf');
