// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const Exo_100Thin: number;
export const Exo_200ExtraLight: number;
export const Exo_300Light: number;
export const Exo_400Regular: number;
export const Exo_500Medium: number;
export const Exo_600SemiBold: number;
export const Exo_700Bold: number;
export const Exo_800ExtraBold: number;
export const Exo_900Black: number;
export const Exo_100Thin_Italic: number;
export const Exo_200ExtraLight_Italic: number;
export const Exo_300Light_Italic: number;
export const Exo_400Regular_Italic: number;
export const Exo_500Medium_Italic: number;
export const Exo_600SemiBold_Italic: number;
export const Exo_700Bold_Italic: number;
export const Exo_800ExtraBold_Italic: number;
export const Exo_900Black_Italic: number;
