/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Exo_Thin100: number;
export const Exo_Thin100_Italic: number;
export const Exo_ExtraLight200: number;
export const Exo_ExtraLight200_Italic: number;
export const Exo_Light300: number;
export const Exo_Light300_Italic: number;
export const Exo_Regular400: number;
export const Exo_Regular400_Italic: number;
export const Exo_Medium500: number;
export const Exo_Medium500_Italic: number;
export const Exo_SemiBold600: number;
export const Exo_SemiBold600_Italic: number;
export const Exo_Bold700: number;
export const Exo_Bold700_Italic: number;
export const Exo_ExtraBold800: number;
export const Exo_ExtraBold800_Italic: number;
export const Exo_Black900: number;
export const Exo_Black900_Italic: number;
