// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const MaterialSymbolsOutlined_100Thin = require('./100Thin/MaterialSymbolsOutlined_100Thin.ttf');
export const MaterialSymbolsOutlined_200ExtraLight = require('./200ExtraLight/MaterialSymbolsOutlined_200ExtraLight.ttf');
export const MaterialSymbolsOutlined_300Light = require('./300Light/MaterialSymbolsOutlined_300Light.ttf');
export const MaterialSymbolsOutlined_400Regular = require('./400Regular/MaterialSymbolsOutlined_400Regular.ttf');
export const MaterialSymbolsOutlined_500Medium = require('./500Medium/MaterialSymbolsOutlined_500Medium.ttf');
export const MaterialSymbolsOutlined_600SemiBold = require('./600SemiBold/MaterialSymbolsOutlined_600SemiBold.ttf');
export const MaterialSymbolsOutlined_700Bold = require('./700Bold/MaterialSymbolsOutlined_700Bold.ttf');
export const MaterialSymbolsOutlined_100Thin_Filled = require('./100Thin_Filled/MaterialSymbolsOutlined_100Thin_Filled.ttf');
export const MaterialSymbolsOutlined_200ExtraLight_Filled = require('./200ExtraLight_Filled/MaterialSymbolsOutlined_200ExtraLight_Filled.ttf');
export const MaterialSymbolsOutlined_300Light_Filled = require('./300Light_Filled/MaterialSymbolsOutlined_300Light_Filled.ttf');
export const MaterialSymbolsOutlined_400Regular_Filled = require('./400Regular_Filled/MaterialSymbolsOutlined_400Regular_Filled.ttf');
export const MaterialSymbolsOutlined_500Medium_Filled = require('./500Medium_Filled/MaterialSymbolsOutlined_500Medium_Filled.ttf');
export const MaterialSymbolsOutlined_600SemiBold_Filled = require('./600SemiBold_Filled/MaterialSymbolsOutlined_600SemiBold_Filled.ttf');
export const MaterialSymbolsOutlined_700Bold_Filled = require('./700Bold_Filled/MaterialSymbolsOutlined_700Bold_Filled.ttf');
