/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const PlaywriteCZ_100Thin: number;
export const PlaywriteCZ_200ExtraLight: number;
export const PlaywriteCZ_300Light: number;
export const PlaywriteCZ_400Regular: number;
