// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const SofiaSansCondensed_400Regular_Italic = require('./SofiaSansCondensed_400Regular_Italic.ttf');
