// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansOlChiki_400Regular = require('./NotoSansOlChiki_400Regular.ttf');
