/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export const __fontFamilyName__ = 'Song Myung';
export const __fontFamilyVersion__ = 4;

export const SongMyung_Regular400 = require('./45407348eb54e83212eddfa7ad22cd18d0f75783316406f08beb532a835bc3f4.ttf');
