// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaywriteAUQLD_400Regular = require('./PlaywriteAUQLD_400Regular.ttf');
