// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const PTSansNarrow_400Regular = require('./PTSansNarrow_400Regular.ttf');
export const PTSansNarrow_700Bold = require('./PTSansNarrow_700Bold.ttf');
