// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const EncodeSansExpanded_400Regular = require('./EncodeSansExpanded_400Regular.ttf');
