// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const Orbitron_400Regular: number;
export const Orbitron_500Medium: number;
export const Orbitron_600SemiBold: number;
export const Orbitron_700Bold: number;
export const Orbitron_800ExtraBold: number;
export const Orbitron_900Black: number;
