// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const StickNoBills_300Light = require('./StickNoBills_300Light.ttf');
