// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const IMFellEnglish_400Regular = require('./IMFellEnglish_400Regular.ttf');
