/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const PlaywriteAUNSWGuides_400Regular = require('./PlaywriteAUNSWGuides_400Regular.ttf');
