// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const ComingSoon_400Regular = require('./ComingSoon_400Regular.ttf');
