// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSerifTelugu_200ExtraLight = require('./NotoSerifTelugu_200ExtraLight.ttf');
