// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PublicSans_200ExtraLight = require('./PublicSans_200ExtraLight.ttf');
