// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export const __metadata__: any;
export const NataSans_100Thin: number;
export const NataSans_200ExtraLight: number;
export const NataSans_300Light: number;
export const NataSans_400Regular: number;
export const NataSans_500Medium: number;
export const NataSans_600SemiBold: number;
export const NataSans_700Bold: number;
export const NataSans_800ExtraBold: number;
export const NataSans_900Black: number;
