// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansSyriacWestern_300Light = require('./NotoSansSyriacWestern_300Light.ttf');
