/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const Caudex_400Regular = require('./Caudex_400Regular.ttf');
export const Caudex_400Regular_Italic = require('./Caudex_400Regular_Italic.ttf');
export const Caudex_700Bold = require('./Caudex_700Bold.ttf');
export const Caudex_700Bold_Italic = require('./Caudex_700Bold_Italic.ttf');
