// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoNaskhArabic_600SemiBold = require('./NotoNaskhArabic_600SemiBold.ttf');
