// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const NotoEmoji_300Light: number;
export const NotoEmoji_400Regular: number;
export const NotoEmoji_500Medium: number;
export const NotoEmoji_600SemiBold: number;
export const NotoEmoji_700Bold: number;
