/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const Enriqueta_400Regular: number;
export const Enriqueta_500Medium: number;
export const Enriqueta_600SemiBold: number;
export const Enriqueta_700Bold: number;
