// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const RedditSansCondensed_800ExtraBold = require('./RedditSansCondensed_800ExtraBold.ttf');
