// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansMono_200ExtraLight = require('./NotoSansMono_200ExtraLight.ttf');
