/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const NotoSerifKhmer_200ExtraLight = require('./NotoSerifKhmer_200ExtraLight.ttf');
