/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const NotoSansMalayalam_100Thin: number;
export const NotoSansMalayalam_200ExtraLight: number;
export const NotoSansMalayalam_300Light: number;
export const NotoSansMalayalam_400Regular: number;
export const NotoSansMalayalam_500Medium: number;
export const NotoSansMalayalam_600SemiBold: number;
export const NotoSansMalayalam_700Bold: number;
export const NotoSansMalayalam_800ExtraBold: number;
export const NotoSansMalayalam_900Black: number;
