// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const BalooBhai2_400Regular: number;
export const BalooBhai2_500Medium: number;
export const BalooBhai2_600SemiBold: number;
export const BalooBhai2_700Bold: number;
export const BalooBhai2_800ExtraBold: number;
