// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const VictorMono_100Thin: number;
export const VictorMono_200ExtraLight: number;
export const VictorMono_300Light: number;
export const VictorMono_400Regular: number;
export const VictorMono_500Medium: number;
export const VictorMono_600SemiBold: number;
export const VictorMono_700Bold: number;
export const VictorMono_100Thin_Italic: number;
export const VictorMono_200ExtraLight_Italic: number;
export const VictorMono_300Light_Italic: number;
export const VictorMono_400Regular_Italic: number;
export const VictorMono_500Medium_Italic: number;
export const VictorMono_600SemiBold_Italic: number;
export const VictorMono_700Bold_Italic: number;
