// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Charm_400Regular = require('./400Regular/Charm_400Regular.ttf');
export const Charm_700Bold = require('./700Bold/Charm_700Bold.ttf');
