// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const ArsenalSC_400Regular = require('./400Regular/ArsenalSC_400Regular.ttf');
export const ArsenalSC_400Regular_Italic = require('./400Regular_Italic/ArsenalSC_400Regular_Italic.ttf');
export const ArsenalSC_700Bold = require('./700Bold/ArsenalSC_700Bold.ttf');
export const ArsenalSC_700Bold_Italic = require('./700Bold_Italic/ArsenalSC_700Bold_Italic.ttf');
