// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansBengali_500Medium = require('./NotoSansBengali_500Medium.ttf');
