// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const ZalandoSansExpanded_400Regular_Italic = require('./ZalandoSansExpanded_400Regular_Italic.ttf');
