/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const NotoSansEthiopic_100Thin = require('./NotoSansEthiopic_100Thin.ttf');
export const NotoSansEthiopic_200ExtraLight = require('./NotoSansEthiopic_200ExtraLight.ttf');
export const NotoSansEthiopic_300Light = require('./NotoSansEthiopic_300Light.ttf');
export const NotoSansEthiopic_400Regular = require('./NotoSansEthiopic_400Regular.ttf');
export const NotoSansEthiopic_500Medium = require('./NotoSansEthiopic_500Medium.ttf');
export const NotoSansEthiopic_600SemiBold = require('./NotoSansEthiopic_600SemiBold.ttf');
export const NotoSansEthiopic_700Bold = require('./NotoSansEthiopic_700Bold.ttf');
export const NotoSansEthiopic_800ExtraBold = require('./NotoSansEthiopic_800ExtraBold.ttf');
export const NotoSansEthiopic_900Black = require('./NotoSansEthiopic_900Black.ttf');
