// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const NotoSerifThai_100Thin = require('./NotoSerifThai_100Thin.ttf');
export const NotoSerifThai_200ExtraLight = require('./NotoSerifThai_200ExtraLight.ttf');
export const NotoSerifThai_300Light = require('./NotoSerifThai_300Light.ttf');
export const NotoSerifThai_400Regular = require('./NotoSerifThai_400Regular.ttf');
export const NotoSerifThai_500Medium = require('./NotoSerifThai_500Medium.ttf');
export const NotoSerifThai_600SemiBold = require('./NotoSerifThai_600SemiBold.ttf');
export const NotoSerifThai_700Bold = require('./NotoSerifThai_700Bold.ttf');
export const NotoSerifThai_800ExtraBold = require('./NotoSerifThai_800ExtraBold.ttf');
export const NotoSerifThai_900Black = require('./NotoSerifThai_900Black.ttf');
