// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const NotoSansLaoLooped_100Thin: number;
export const NotoSansLaoLooped_200ExtraLight: number;
export const NotoSansLaoLooped_300Light: number;
export const NotoSansLaoLooped_400Regular: number;
export const NotoSansLaoLooped_500Medium: number;
export const NotoSansLaoLooped_600SemiBold: number;
export const NotoSansLaoLooped_700Bold: number;
export const NotoSansLaoLooped_800ExtraBold: number;
export const NotoSansLaoLooped_900Black: number;
