// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const NotoSansKR_100Thin = require('./100Thin/NotoSansKR_100Thin.ttf');
export const NotoSansKR_200ExtraLight = require('./200ExtraLight/NotoSansKR_200ExtraLight.ttf');
export const NotoSansKR_300Light = require('./300Light/NotoSansKR_300Light.ttf');
export const NotoSansKR_400Regular = require('./400Regular/NotoSansKR_400Regular.ttf');
export const NotoSansKR_500Medium = require('./500Medium/NotoSansKR_500Medium.ttf');
export const NotoSansKR_600SemiBold = require('./600SemiBold/NotoSansKR_600SemiBold.ttf');
export const NotoSansKR_700Bold = require('./700Bold/NotoSansKR_700Bold.ttf');
export const NotoSansKR_800ExtraBold = require('./800ExtraBold/NotoSansKR_800ExtraBold.ttf');
export const NotoSansKR_900Black = require('./900Black/NotoSansKR_900Black.ttf');
