/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export const __fontFamilyName__ = 'Slabo 13px';
export const __fontFamilyVersion__ = 3;

export const Slabo13px_Regular400 = require('./55c7ef45e832252817233d906300e1087c565a52b4cedecffcf03d7edb86f694.ttf');
