// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const NotoSansTaiTham_400Regular = require('./400Regular/NotoSansTaiTham_400Regular.ttf');
export const NotoSansTaiTham_500Medium = require('./500Medium/NotoSansTaiTham_500Medium.ttf');
export const NotoSansTaiTham_600SemiBold = require('./600SemiBold/NotoSansTaiTham_600SemiBold.ttf');
export const NotoSansTaiTham_700Bold = require('./700Bold/NotoSansTaiTham_700Bold.ttf');
