/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const FrankRuhlLibre_Light300: number;
export const FrankRuhlLibre_Regular400: number;
export const FrankRuhlLibre_Medium500: number;
export const FrankRuhlLibre_Bold700: number;
export const FrankRuhlLibre_Black900: number;
