// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const MonomaniacOne_400Regular = require('./MonomaniacOne_400Regular.ttf');
