/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Amarante_Regular400 = require('./f11a52c1a0f3e94f81dde8d9c60832c688c1d9b01c5bb1098c3ea30daac8ad29.ttf');
