// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Kadwa_400Regular = require('./400Regular/Kadwa_400Regular.ttf');
export const Kadwa_700Bold = require('./700Bold/Kadwa_700Bold.ttf');
