/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const AveriaSerifLibre_Light300 = require('./605722d0534e8b2a7a4ce36ebc7ecfa14868d5aeae52ba3419e14a19e67c92ba.ttf');
export const AveriaSerifLibre_Light300_Italic = require('./4b675f9e2f2962fb69b7145f35ea9df241cdc9b91744abeac3cdfbf7aca1740b.ttf');
export const AveriaSerifLibre_Regular400 = require('./1939fc59e6192c78872b151f71d328c64c84552c1f8f7548f3278d3db023959f.ttf');
export const AveriaSerifLibre_Regular400_Italic = require('./383c63d8878e96726e26c44d5a631030fcf28d4abdcb9bdadd86dbb01a623de9.ttf');
export const AveriaSerifLibre_Bold700 = require('./19af7d57b5ea32ff5df3f2405e0d51759fdbab503fa4cfd420a5eb4943805fcc.ttf');
export const AveriaSerifLibre_Bold700_Italic = require('./164c3a01088756eebd948641705d6759b2fc7dabfd77d6e36490aa39befa0028.ttf');
