/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const NotoSansNewTaiLue_400Regular = require('./NotoSansNewTaiLue_400Regular.ttf');
export const NotoSansNewTaiLue_500Medium = require('./NotoSansNewTaiLue_500Medium.ttf');
export const NotoSansNewTaiLue_600SemiBold = require('./NotoSansNewTaiLue_600SemiBold.ttf');
export const NotoSansNewTaiLue_700Bold = require('./NotoSansNewTaiLue_700Bold.ttf');
