// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const NotoSansNewTaiLue_400Regular = require('./400Regular/NotoSansNewTaiLue_400Regular.ttf');
export const NotoSansNewTaiLue_500Medium = require('./500Medium/NotoSansNewTaiLue_500Medium.ttf');
export const NotoSansNewTaiLue_600SemiBold = require('./600SemiBold/NotoSansNewTaiLue_600SemiBold.ttf');
export const NotoSansNewTaiLue_700Bold = require('./700Bold/NotoSansNewTaiLue_700Bold.ttf');
