/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const NotoSansNewTaiLue_400Regular: number;
export const NotoSansNewTaiLue_500Medium: number;
export const NotoSansNewTaiLue_600SemiBold: number;
export const NotoSansNewTaiLue_700Bold: number;
