/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metdata__: Any;
export const Taviraj_100Thin: number;
export const Taviraj_100Thin_Italic: number;
export const Taviraj_200ExtraLight: number;
export const Taviraj_200ExtraLight_Italic: number;
export const Taviraj_300Light: number;
export const Taviraj_300Light_Italic: number;
export const Taviraj_400Regular: number;
export const Taviraj_400Regular_Italic: number;
export const Taviraj_500Medium: number;
export const Taviraj_500Medium_Italic: number;
export const Taviraj_600SemiBold: number;
export const Taviraj_600SemiBold_Italic: number;
export const Taviraj_700Bold: number;
export const Taviraj_700Bold_Italic: number;
export const Taviraj_800ExtraBold: number;
export const Taviraj_800ExtraBold_Italic: number;
export const Taviraj_900Black: number;
export const Taviraj_900Black_Italic: number;
