// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoNastaliqUrdu_700Bold = require('./NotoNastaliqUrdu_700Bold.ttf');
