// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Zain_200ExtraLight = require('./200ExtraLight/Zain_200ExtraLight.ttf');
export const Zain_300Light = require('./300Light/Zain_300Light.ttf');
export const Zain_300Light_Italic = require('./300Light_Italic/Zain_300Light_Italic.ttf');
export const Zain_400Regular = require('./400Regular/Zain_400Regular.ttf');
export const Zain_400Regular_Italic = require('./400Regular_Italic/Zain_400Regular_Italic.ttf');
export const Zain_700Bold = require('./700Bold/Zain_700Bold.ttf');
export const Zain_800ExtraBold = require('./800ExtraBold/Zain_800ExtraBold.ttf');
export const Zain_900Black = require('./900Black/Zain_900Black.ttf');
