// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const InstrumentSans_400Regular: number;
export const InstrumentSans_500Medium: number;
export const InstrumentSans_600SemiBold: number;
export const InstrumentSans_700Bold: number;
export const InstrumentSans_400Regular_Italic: number;
export const InstrumentSans_500Medium_Italic: number;
export const InstrumentSans_600SemiBold_Italic: number;
export const InstrumentSans_700Bold_Italic: number;
