// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Kanit_500Medium_Italic = require('./Kanit_500Medium_Italic.ttf');
