/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const MacondoSwashCaps_Regular400 = require('./4143af0ceceb156b80e5e2055d178d84cfca13b39056f49121b05c6b3843f1fd.ttf');
