// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Gaegu_300Light = require('./Gaegu_300Light.ttf');
export const Gaegu_400Regular = require('./Gaegu_400Regular.ttf');
export const Gaegu_700Bold = require('./Gaegu_700Bold.ttf');
