// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Alegreya_400Regular = require('./Alegreya_400Regular.ttf');
export const Alegreya_500Medium = require('./Alegreya_500Medium.ttf');
export const Alegreya_600SemiBold = require('./Alegreya_600SemiBold.ttf');
export const Alegreya_700Bold = require('./Alegreya_700Bold.ttf');
export const Alegreya_800ExtraBold = require('./Alegreya_800ExtraBold.ttf');
export const Alegreya_900Black = require('./Alegreya_900Black.ttf');
export const Alegreya_400Regular_Italic = require('./Alegreya_400Regular_Italic.ttf');
export const Alegreya_500Medium_Italic = require('./Alegreya_500Medium_Italic.ttf');
export const Alegreya_600SemiBold_Italic = require('./Alegreya_600SemiBold_Italic.ttf');
export const Alegreya_700Bold_Italic = require('./Alegreya_700Bold_Italic.ttf');
export const Alegreya_800ExtraBold_Italic = require('./Alegreya_800ExtraBold_Italic.ttf');
export const Alegreya_900Black_Italic = require('./Alegreya_900Black_Italic.ttf');
