// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Alegreya_400Regular = require('./400Regular/Alegreya_400Regular.ttf');
export const Alegreya_500Medium = require('./500Medium/Alegreya_500Medium.ttf');
export const Alegreya_600SemiBold = require('./600SemiBold/Alegreya_600SemiBold.ttf');
export const Alegreya_700Bold = require('./700Bold/Alegreya_700Bold.ttf');
export const Alegreya_800ExtraBold = require('./800ExtraBold/Alegreya_800ExtraBold.ttf');
export const Alegreya_900Black = require('./900Black/Alegreya_900Black.ttf');
export const Alegreya_400Regular_Italic = require('./400Regular_Italic/Alegreya_400Regular_Italic.ttf');
export const Alegreya_500Medium_Italic = require('./500Medium_Italic/Alegreya_500Medium_Italic.ttf');
export const Alegreya_600SemiBold_Italic = require('./600SemiBold_Italic/Alegreya_600SemiBold_Italic.ttf');
export const Alegreya_700Bold_Italic = require('./700Bold_Italic/Alegreya_700Bold_Italic.ttf');
export const Alegreya_800ExtraBold_Italic = require('./800ExtraBold_Italic/Alegreya_800ExtraBold_Italic.ttf');
export const Alegreya_900Black_Italic = require('./900Black_Italic/Alegreya_900Black_Italic.ttf');
