/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const NotoSerifHentaigana_500Medium = require('./NotoSerifHentaigana_500Medium.ttf');
