// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaywriteESDeco_100Thin = require('./PlaywriteESDeco_100Thin.ttf');
