// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const AlbertSans_900Black_Italic = require('./AlbertSans_900Black_Italic.ttf');
