// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSerifTamil_800ExtraBold_Italic = require('./NotoSerifTamil_800ExtraBold_Italic.ttf');
