// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaywriteHRLijeva_300Light = require('./PlaywriteHRLijeva_300Light.ttf');
