/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const ElMessiri_Regular400: number;
export const ElMessiri_Medium500: number;
export const ElMessiri_SemiBold600: number;
export const ElMessiri_Bold700: number;
