// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Anybody_100Thin = require('./100Thin/Anybody_100Thin.ttf');
export const Anybody_200ExtraLight = require('./200ExtraLight/Anybody_200ExtraLight.ttf');
export const Anybody_300Light = require('./300Light/Anybody_300Light.ttf');
export const Anybody_400Regular = require('./400Regular/Anybody_400Regular.ttf');
export const Anybody_500Medium = require('./500Medium/Anybody_500Medium.ttf');
export const Anybody_600SemiBold = require('./600SemiBold/Anybody_600SemiBold.ttf');
export const Anybody_700Bold = require('./700Bold/Anybody_700Bold.ttf');
export const Anybody_800ExtraBold = require('./800ExtraBold/Anybody_800ExtraBold.ttf');
export const Anybody_900Black = require('./900Black/Anybody_900Black.ttf');
export const Anybody_100Thin_Italic = require('./100Thin_Italic/Anybody_100Thin_Italic.ttf');
export const Anybody_200ExtraLight_Italic = require('./200ExtraLight_Italic/Anybody_200ExtraLight_Italic.ttf');
export const Anybody_300Light_Italic = require('./300Light_Italic/Anybody_300Light_Italic.ttf');
export const Anybody_400Regular_Italic = require('./400Regular_Italic/Anybody_400Regular_Italic.ttf');
export const Anybody_500Medium_Italic = require('./500Medium_Italic/Anybody_500Medium_Italic.ttf');
export const Anybody_600SemiBold_Italic = require('./600SemiBold_Italic/Anybody_600SemiBold_Italic.ttf');
export const Anybody_700Bold_Italic = require('./700Bold_Italic/Anybody_700Bold_Italic.ttf');
export const Anybody_800ExtraBold_Italic = require('./800ExtraBold_Italic/Anybody_800ExtraBold_Italic.ttf');
export const Anybody_900Black_Italic = require('./900Black_Italic/Anybody_900Black_Italic.ttf');
