// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const MaterialSymbolsSharp_700Bold_Filled = require('./MaterialSymbolsSharp_700Bold_Filled.ttf');
