// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const HeptaSlab_100Thin = require('./100Thin/HeptaSlab_100Thin.ttf');
export const HeptaSlab_200ExtraLight = require('./200ExtraLight/HeptaSlab_200ExtraLight.ttf');
export const HeptaSlab_300Light = require('./300Light/HeptaSlab_300Light.ttf');
export const HeptaSlab_400Regular = require('./400Regular/HeptaSlab_400Regular.ttf');
export const HeptaSlab_500Medium = require('./500Medium/HeptaSlab_500Medium.ttf');
export const HeptaSlab_600SemiBold = require('./600SemiBold/HeptaSlab_600SemiBold.ttf');
export const HeptaSlab_700Bold = require('./700Bold/HeptaSlab_700Bold.ttf');
export const HeptaSlab_800ExtraBold = require('./800ExtraBold/HeptaSlab_800ExtraBold.ttf');
export const HeptaSlab_900Black = require('./900Black/HeptaSlab_900Black.ttf');
