// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const BitcountSingleInk_500Medium = require('./BitcountSingleInk_500Medium.ttf');
