/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const CactusClassicalSerif_400Regular = require('./CactusClassicalSerif_400Regular.ttf');
