// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Belanosima_600SemiBold = require('./Belanosima_600SemiBold.ttf');
