/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Limelight_Regular400 = require('./ba79f57019c587202d831e35a7e10e6dc9ab23546f46ec9da01aa4d25d509913.ttf');
