// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const CourierPrime_400Regular = require('./CourierPrime_400Regular.ttf');
export const CourierPrime_400Regular_Italic = require('./CourierPrime_400Regular_Italic.ttf');
export const CourierPrime_700Bold = require('./CourierPrime_700Bold.ttf');
export const CourierPrime_700Bold_Italic = require('./CourierPrime_700Bold_Italic.ttf');
