/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const NotoSerifBengali_600SemiBold = require('./NotoSerifBengali_600SemiBold.ttf');
