// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const RibeyeMarrow_400Regular = require('./RibeyeMarrow_400Regular.ttf');
