// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const AnekGujarati_500Medium = require('./AnekGujarati_500Medium.ttf');
