/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const SairaExtraCondensed_100Thin: number;
export const SairaExtraCondensed_200ExtraLight: number;
export const SairaExtraCondensed_300Light: number;
export const SairaExtraCondensed_400Regular: number;
export const SairaExtraCondensed_500Medium: number;
export const SairaExtraCondensed_600SemiBold: number;
export const SairaExtraCondensed_700Bold: number;
export const SairaExtraCondensed_800ExtraBold: number;
export const SairaExtraCondensed_900Black: number;
