// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const SairaExtraCondensed_100Thin: number;
export const SairaExtraCondensed_200ExtraLight: number;
export const SairaExtraCondensed_300Light: number;
export const SairaExtraCondensed_400Regular: number;
export const SairaExtraCondensed_500Medium: number;
export const SairaExtraCondensed_600SemiBold: number;
export const SairaExtraCondensed_700Bold: number;
export const SairaExtraCondensed_800ExtraBold: number;
export const SairaExtraCondensed_900Black: number;
