// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Cormorant_700Bold_Italic = require('./Cormorant_700Bold_Italic.ttf');
