// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const CrimsonText_600SemiBold = require('./CrimsonText_600SemiBold.ttf');
