// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansKannada_200ExtraLight = require('./NotoSansKannada_200ExtraLight.ttf');
