// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansTaiViet_400Regular = require('./NotoSansTaiViet_400Regular.ttf');
