// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const KarlaTamilUpright_400Regular = require('./KarlaTamilUpright_400Regular.ttf');
export const KarlaTamilUpright_700Bold = require('./KarlaTamilUpright_700Bold.ttf');
