/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const CairoPlay_200ExtraLight: number;
export const CairoPlay_300Light: number;
export const CairoPlay_400Regular: number;
export const CairoPlay_500Medium: number;
export const CairoPlay_600SemiBold: number;
export const CairoPlay_700Bold: number;
export const CairoPlay_800ExtraBold: number;
export const CairoPlay_900Black: number;
