// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const QwitcherGrypen_400Regular = require('./QwitcherGrypen_400Regular.ttf');
export const QwitcherGrypen_700Bold = require('./QwitcherGrypen_700Bold.ttf');
