// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export const __metadata__: any;
export const IosevkaCharonMono_300Light: number;
export const IosevkaCharonMono_300Light_Italic: number;
export const IosevkaCharonMono_400Regular: number;
export const IosevkaCharonMono_400Regular_Italic: number;
export const IosevkaCharonMono_500Medium: number;
export const IosevkaCharonMono_500Medium_Italic: number;
export const IosevkaCharonMono_700Bold: number;
export const IosevkaCharonMono_700Bold_Italic: number;
