// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const SairaSemiCondensed_700Bold = require('./SairaSemiCondensed_700Bold.ttf');
