// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Gelasio_700Bold_Italic = require('./Gelasio_700Bold_Italic.ttf');
