// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const MonaSans_200ExtraLight = require('./MonaSans_200ExtraLight.ttf');
