/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const BigShouldersInlineDisplay_100Thin: number;
export const BigShouldersInlineDisplay_200ExtraLight: number;
export const BigShouldersInlineDisplay_300Light: number;
export const BigShouldersInlineDisplay_400Regular: number;
export const BigShouldersInlineDisplay_500Medium: number;
export const BigShouldersInlineDisplay_600SemiBold: number;
export const BigShouldersInlineDisplay_700Bold: number;
export const BigShouldersInlineDisplay_800ExtraBold: number;
export const BigShouldersInlineDisplay_900Black: number;
