/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const IBMPlexSansThaiLooped_100Thin: number;
export const IBMPlexSansThaiLooped_200ExtraLight: number;
export const IBMPlexSansThaiLooped_300Light: number;
export const IBMPlexSansThaiLooped_400Regular: number;
export const IBMPlexSansThaiLooped_500Medium: number;
export const IBMPlexSansThaiLooped_600SemiBold: number;
export const IBMPlexSansThaiLooped_700Bold: number;
