// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const NotoSerifHebrew_100Thin = require('./NotoSerifHebrew_100Thin.ttf');
export const NotoSerifHebrew_200ExtraLight = require('./NotoSerifHebrew_200ExtraLight.ttf');
export const NotoSerifHebrew_300Light = require('./NotoSerifHebrew_300Light.ttf');
export const NotoSerifHebrew_400Regular = require('./NotoSerifHebrew_400Regular.ttf');
export const NotoSerifHebrew_500Medium = require('./NotoSerifHebrew_500Medium.ttf');
export const NotoSerifHebrew_600SemiBold = require('./NotoSerifHebrew_600SemiBold.ttf');
export const NotoSerifHebrew_700Bold = require('./NotoSerifHebrew_700Bold.ttf');
export const NotoSerifHebrew_800ExtraBold = require('./NotoSerifHebrew_800ExtraBold.ttf');
export const NotoSerifHebrew_900Black = require('./NotoSerifHebrew_900Black.ttf');
