// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const CossetteTexte_400Regular = require('./CossetteTexte_400Regular.ttf');
