// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const EduVICWANTHandPre_400Regular = require('./400Regular/EduVICWANTHandPre_400Regular.ttf');
export const EduVICWANTHandPre_500Medium = require('./500Medium/EduVICWANTHandPre_500Medium.ttf');
export const EduVICWANTHandPre_600SemiBold = require('./600SemiBold/EduVICWANTHandPre_600SemiBold.ttf');
export const EduVICWANTHandPre_700Bold = require('./700Bold/EduVICWANTHandPre_700Bold.ttf');
