/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const Onest_100Thin: number;
export const Onest_200ExtraLight: number;
export const Onest_300Light: number;
export const Onest_400Regular: number;
export const Onest_500Medium: number;
export const Onest_600SemiBold: number;
export const Onest_700Bold: number;
export const Onest_800ExtraBold: number;
export const Onest_900Black: number;
