// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const Tourney_100Thin: number;
export const Tourney_200ExtraLight: number;
export const Tourney_300Light: number;
export const Tourney_400Regular: number;
export const Tourney_500Medium: number;
export const Tourney_600SemiBold: number;
export const Tourney_700Bold: number;
export const Tourney_800ExtraBold: number;
export const Tourney_900Black: number;
export const Tourney_100Thin_Italic: number;
export const Tourney_200ExtraLight_Italic: number;
export const Tourney_300Light_Italic: number;
export const Tourney_400Regular_Italic: number;
export const Tourney_500Medium_Italic: number;
export const Tourney_600SemiBold_Italic: number;
export const Tourney_700Bold_Italic: number;
export const Tourney_800ExtraBold_Italic: number;
export const Tourney_900Black_Italic: number;
