/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const MPLUS1p_100Thin: number;
export const MPLUS1p_300Light: number;
export const MPLUS1p_400Regular: number;
export const MPLUS1p_500Medium: number;
export const MPLUS1p_700Bold: number;
export const MPLUS1p_800ExtraBold: number;
export const MPLUS1p_900Black: number;
