/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const MPLUS1p_Thin100: number;
export const MPLUS1p_Light300: number;
export const MPLUS1p_Regular400: number;
export const MPLUS1p_Medium500: number;
export const MPLUS1p_Bold700: number;
export const MPLUS1p_ExtraBold800: number;
export const MPLUS1p_Black900: number;
