/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const Hanuman_100Thin: number;
export const Hanuman_300Light: number;
export const Hanuman_400Regular: number;
export const Hanuman_700Bold: number;
export const Hanuman_900Black: number;
