// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaywriteGBJ_200ExtraLight = require('./PlaywriteGBJ_200ExtraLight.ttf');
