// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const NotoSerifDevanagari_100Thin = require('./100Thin/NotoSerifDevanagari_100Thin.ttf');
export const NotoSerifDevanagari_200ExtraLight = require('./200ExtraLight/NotoSerifDevanagari_200ExtraLight.ttf');
export const NotoSerifDevanagari_300Light = require('./300Light/NotoSerifDevanagari_300Light.ttf');
export const NotoSerifDevanagari_400Regular = require('./400Regular/NotoSerifDevanagari_400Regular.ttf');
export const NotoSerifDevanagari_500Medium = require('./500Medium/NotoSerifDevanagari_500Medium.ttf');
export const NotoSerifDevanagari_600SemiBold = require('./600SemiBold/NotoSerifDevanagari_600SemiBold.ttf');
export const NotoSerifDevanagari_700Bold = require('./700Bold/NotoSerifDevanagari_700Bold.ttf');
export const NotoSerifDevanagari_800ExtraBold = require('./800ExtraBold/NotoSerifDevanagari_800ExtraBold.ttf');
export const NotoSerifDevanagari_900Black = require('./900Black/NotoSerifDevanagari_900Black.ttf');
