// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansCherokee_300Light = require('./NotoSansCherokee_300Light.ttf');
