// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Aleo_400Regular_Italic = require('./Aleo_400Regular_Italic.ttf');
