// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const Imbue_100Thin: number;
export const Imbue_200ExtraLight: number;
export const Imbue_300Light: number;
export const Imbue_400Regular: number;
export const Imbue_500Medium: number;
export const Imbue_600SemiBold: number;
export const Imbue_700Bold: number;
export const Imbue_800ExtraBold: number;
export const Imbue_900Black: number;
