// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Tektur_400Regular = require('./400Regular/Tektur_400Regular.ttf');
export const Tektur_500Medium = require('./500Medium/Tektur_500Medium.ttf');
export const Tektur_600SemiBold = require('./600SemiBold/Tektur_600SemiBold.ttf');
export const Tektur_700Bold = require('./700Bold/Tektur_700Bold.ttf');
export const Tektur_800ExtraBold = require('./800ExtraBold/Tektur_800ExtraBold.ttf');
export const Tektur_900Black = require('./900Black/Tektur_900Black.ttf');
