// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const PlaywriteCL_100Thin: number;
export const PlaywriteCL_200ExtraLight: number;
export const PlaywriteCL_300Light: number;
export const PlaywriteCL_400Regular: number;
