// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const Gluten_100Thin: number;
export const Gluten_200ExtraLight: number;
export const Gluten_300Light: number;
export const Gluten_400Regular: number;
export const Gluten_500Medium: number;
export const Gluten_600SemiBold: number;
export const Gluten_700Bold: number;
export const Gluten_800ExtraBold: number;
export const Gluten_900Black: number;
