/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const NotoSerifNPHmong_400Regular = require('./NotoSerifNPHmong_400Regular.ttf');
export const NotoSerifNPHmong_500Medium = require('./NotoSerifNPHmong_500Medium.ttf');
export const NotoSerifNPHmong_600SemiBold = require('./NotoSerifNPHmong_600SemiBold.ttf');
export const NotoSerifNPHmong_700Bold = require('./NotoSerifNPHmong_700Bold.ttf');
