// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const Arima_100Thin: number;
export const Arima_200ExtraLight: number;
export const Arima_300Light: number;
export const Arima_400Regular: number;
export const Arima_500Medium: number;
export const Arima_600SemiBold: number;
export const Arima_700Bold: number;
