// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const SignikaNegative_300Light = require('./300Light/SignikaNegative_300Light.ttf');
export const SignikaNegative_400Regular = require('./400Regular/SignikaNegative_400Regular.ttf');
export const SignikaNegative_500Medium = require('./500Medium/SignikaNegative_500Medium.ttf');
export const SignikaNegative_600SemiBold = require('./600SemiBold/SignikaNegative_600SemiBold.ttf');
export const SignikaNegative_700Bold = require('./700Bold/SignikaNegative_700Bold.ttf');
