/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metdata__: Any;
export const SignikaNegative_300Light: number;
export const SignikaNegative_400Regular: number;
export const SignikaNegative_600SemiBold: number;
export const SignikaNegative_700Bold: number;
