/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const CrimsonPro_200ExtraLight = require('./CrimsonPro_200ExtraLight.ttf');
export const CrimsonPro_300Light = require('./CrimsonPro_300Light.ttf');
export const CrimsonPro_400Regular = require('./CrimsonPro_400Regular.ttf');
export const CrimsonPro_500Medium = require('./CrimsonPro_500Medium.ttf');
export const CrimsonPro_600SemiBold = require('./CrimsonPro_600SemiBold.ttf');
export const CrimsonPro_700Bold = require('./CrimsonPro_700Bold.ttf');
export const CrimsonPro_800ExtraBold = require('./CrimsonPro_800ExtraBold.ttf');
export const CrimsonPro_900Black = require('./CrimsonPro_900Black.ttf');
export const CrimsonPro_200ExtraLight_Italic = require('./CrimsonPro_200ExtraLight_Italic.ttf');
export const CrimsonPro_300Light_Italic = require('./CrimsonPro_300Light_Italic.ttf');
export const CrimsonPro_400Regular_Italic = require('./CrimsonPro_400Regular_Italic.ttf');
export const CrimsonPro_500Medium_Italic = require('./CrimsonPro_500Medium_Italic.ttf');
export const CrimsonPro_600SemiBold_Italic = require('./CrimsonPro_600SemiBold_Italic.ttf');
export const CrimsonPro_700Bold_Italic = require('./CrimsonPro_700Bold_Italic.ttf');
export const CrimsonPro_800ExtraBold_Italic = require('./CrimsonPro_800ExtraBold_Italic.ttf');
export const CrimsonPro_900Black_Italic = require('./CrimsonPro_900Black_Italic.ttf');
