// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const BitcountPropSingleInk_100Thin = require('./100Thin/BitcountPropSingleInk_100Thin.ttf');
export const BitcountPropSingleInk_200ExtraLight = require('./200ExtraLight/BitcountPropSingleInk_200ExtraLight.ttf');
export const BitcountPropSingleInk_300Light = require('./300Light/BitcountPropSingleInk_300Light.ttf');
export const BitcountPropSingleInk_400Regular = require('./400Regular/BitcountPropSingleInk_400Regular.ttf');
export const BitcountPropSingleInk_500Medium = require('./500Medium/BitcountPropSingleInk_500Medium.ttf');
export const BitcountPropSingleInk_600SemiBold = require('./600SemiBold/BitcountPropSingleInk_600SemiBold.ttf');
export const BitcountPropSingleInk_700Bold = require('./700Bold/BitcountPropSingleInk_700Bold.ttf');
export const BitcountPropSingleInk_800ExtraBold = require('./800ExtraBold/BitcountPropSingleInk_800ExtraBold.ttf');
export const BitcountPropSingleInk_900Black = require('./900Black/BitcountPropSingleInk_900Black.ttf');
