/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const NotoSans_Regular400: number;
export const NotoSans_Regular400_Italic: number;
export const NotoSans_Bold700: number;
export const NotoSans_Bold700_Italic: number;
