/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const HindMysuru_300Light: number;
export const HindMysuru_400Regular: number;
export const HindMysuru_500Medium: number;
export const HindMysuru_600SemiBold: number;
export const HindMysuru_700Bold: number;
