/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const MontserratAlternates_300Light = require('./MontserratAlternates_300Light.ttf');
