// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSerif_200ExtraLight = require('./NotoSerif_200ExtraLight.ttf');
