/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const IMFellFrenchCanon_400Regular = require('./IMFellFrenchCanon_400Regular.ttf');
export const IMFellFrenchCanon_400Regular_Italic = require('./IMFellFrenchCanon_400Regular_Italic.ttf');
