// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Allan_400Regular = require('./Allan_400Regular.ttf');
export const Allan_700Bold = require('./Allan_700Bold.ttf');
