// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansAdlamUnjoined_500Medium = require('./NotoSansAdlamUnjoined_500Medium.ttf');
