// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const PlaywriteGBS_100Thin: number;
export const PlaywriteGBS_200ExtraLight: number;
export const PlaywriteGBS_300Light: number;
export const PlaywriteGBS_400Regular: number;
export const PlaywriteGBS_100Thin_Italic: number;
export const PlaywriteGBS_200ExtraLight_Italic: number;
export const PlaywriteGBS_300Light_Italic: number;
export const PlaywriteGBS_400Regular_Italic: number;
