// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const NotoSerifTelugu_100Thin = require('./100Thin/NotoSerifTelugu_100Thin.ttf');
export const NotoSerifTelugu_200ExtraLight = require('./200ExtraLight/NotoSerifTelugu_200ExtraLight.ttf');
export const NotoSerifTelugu_300Light = require('./300Light/NotoSerifTelugu_300Light.ttf');
export const NotoSerifTelugu_400Regular = require('./400Regular/NotoSerifTelugu_400Regular.ttf');
export const NotoSerifTelugu_500Medium = require('./500Medium/NotoSerifTelugu_500Medium.ttf');
export const NotoSerifTelugu_600SemiBold = require('./600SemiBold/NotoSerifTelugu_600SemiBold.ttf');
export const NotoSerifTelugu_700Bold = require('./700Bold/NotoSerifTelugu_700Bold.ttf');
export const NotoSerifTelugu_800ExtraBold = require('./800ExtraBold/NotoSerifTelugu_800ExtraBold.ttf');
export const NotoSerifTelugu_900Black = require('./900Black/NotoSerifTelugu_900Black.ttf');
