/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const BalooBhaijaan_Regular400 = require('./52b00fb70a18a89da089a7492d3d97836ec7bd211288d3ec4ad6a60914db3dd3.ttf');
