// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const OxygenMono_400Regular = require('./OxygenMono_400Regular.ttf');
