// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const LibertinusSerif_400Regular = require('./400Regular/LibertinusSerif_400Regular.ttf');
export const LibertinusSerif_400Regular_Italic = require('./400Regular_Italic/LibertinusSerif_400Regular_Italic.ttf');
export const LibertinusSerif_600SemiBold = require('./600SemiBold/LibertinusSerif_600SemiBold.ttf');
export const LibertinusSerif_600SemiBold_Italic = require('./600SemiBold_Italic/LibertinusSerif_600SemiBold_Italic.ttf');
export const LibertinusSerif_700Bold = require('./700Bold/LibertinusSerif_700Bold.ttf');
export const LibertinusSerif_700Bold_Italic = require('./700Bold_Italic/LibertinusSerif_700Bold_Italic.ttf');
