// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Piazzolla_100Thin = require('./100Thin/Piazzolla_100Thin.ttf');
export const Piazzolla_200ExtraLight = require('./200ExtraLight/Piazzolla_200ExtraLight.ttf');
export const Piazzolla_300Light = require('./300Light/Piazzolla_300Light.ttf');
export const Piazzolla_400Regular = require('./400Regular/Piazzolla_400Regular.ttf');
export const Piazzolla_500Medium = require('./500Medium/Piazzolla_500Medium.ttf');
export const Piazzolla_600SemiBold = require('./600SemiBold/Piazzolla_600SemiBold.ttf');
export const Piazzolla_700Bold = require('./700Bold/Piazzolla_700Bold.ttf');
export const Piazzolla_800ExtraBold = require('./800ExtraBold/Piazzolla_800ExtraBold.ttf');
export const Piazzolla_900Black = require('./900Black/Piazzolla_900Black.ttf');
export const Piazzolla_100Thin_Italic = require('./100Thin_Italic/Piazzolla_100Thin_Italic.ttf');
export const Piazzolla_200ExtraLight_Italic = require('./200ExtraLight_Italic/Piazzolla_200ExtraLight_Italic.ttf');
export const Piazzolla_300Light_Italic = require('./300Light_Italic/Piazzolla_300Light_Italic.ttf');
export const Piazzolla_400Regular_Italic = require('./400Regular_Italic/Piazzolla_400Regular_Italic.ttf');
export const Piazzolla_500Medium_Italic = require('./500Medium_Italic/Piazzolla_500Medium_Italic.ttf');
export const Piazzolla_600SemiBold_Italic = require('./600SemiBold_Italic/Piazzolla_600SemiBold_Italic.ttf');
export const Piazzolla_700Bold_Italic = require('./700Bold_Italic/Piazzolla_700Bold_Italic.ttf');
export const Piazzolla_800ExtraBold_Italic = require('./800ExtraBold_Italic/Piazzolla_800ExtraBold_Italic.ttf');
export const Piazzolla_900Black_Italic = require('./900Black_Italic/Piazzolla_900Black_Italic.ttf');
