// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const NotoSansArmenian_100Thin = require('./100Thin/NotoSansArmenian_100Thin.ttf');
export const NotoSansArmenian_200ExtraLight = require('./200ExtraLight/NotoSansArmenian_200ExtraLight.ttf');
export const NotoSansArmenian_300Light = require('./300Light/NotoSansArmenian_300Light.ttf');
export const NotoSansArmenian_400Regular = require('./400Regular/NotoSansArmenian_400Regular.ttf');
export const NotoSansArmenian_500Medium = require('./500Medium/NotoSansArmenian_500Medium.ttf');
export const NotoSansArmenian_600SemiBold = require('./600SemiBold/NotoSansArmenian_600SemiBold.ttf');
export const NotoSansArmenian_700Bold = require('./700Bold/NotoSansArmenian_700Bold.ttf');
export const NotoSansArmenian_800ExtraBold = require('./800ExtraBold/NotoSansArmenian_800ExtraBold.ttf');
export const NotoSansArmenian_900Black = require('./900Black/NotoSansArmenian_900Black.ttf');
