// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSerifBengali_800ExtraBold = require('./NotoSerifBengali_800ExtraBold.ttf');
