// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const BioRhymeExpanded_200ExtraLight: number;
export const BioRhymeExpanded_300Light: number;
export const BioRhymeExpanded_400Regular: number;
export const BioRhymeExpanded_700Bold: number;
export const BioRhymeExpanded_800ExtraBold: number;
