// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Finlandica_400Regular = require('./400Regular/Finlandica_400Regular.ttf');
export const Finlandica_500Medium = require('./500Medium/Finlandica_500Medium.ttf');
export const Finlandica_600SemiBold = require('./600SemiBold/Finlandica_600SemiBold.ttf');
export const Finlandica_700Bold = require('./700Bold/Finlandica_700Bold.ttf');
export const Finlandica_400Regular_Italic = require('./400Regular_Italic/Finlandica_400Regular_Italic.ttf');
export const Finlandica_500Medium_Italic = require('./500Medium_Italic/Finlandica_500Medium_Italic.ttf');
export const Finlandica_600SemiBold_Italic = require('./600SemiBold_Italic/Finlandica_600SemiBold_Italic.ttf');
export const Finlandica_700Bold_Italic = require('./700Bold_Italic/Finlandica_700Bold_Italic.ttf');
