// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const Nobile_400Regular: number;
export const Nobile_400Regular_Italic: number;
export const Nobile_500Medium: number;
export const Nobile_500Medium_Italic: number;
export const Nobile_700Bold: number;
export const Nobile_700Bold_Italic: number;
