/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const YanoneKaffeesatz_200ExtraLight: number;
export const YanoneKaffeesatz_300Light: number;
export const YanoneKaffeesatz_400Regular: number;
export const YanoneKaffeesatz_500Medium: number;
export const YanoneKaffeesatz_600SemiBold: number;
export const YanoneKaffeesatz_700Bold: number;
