/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const MontserratUnderline_100Thin = require('./MontserratUnderline_100Thin.ttf');
export const MontserratUnderline_200ExtraLight = require('./MontserratUnderline_200ExtraLight.ttf');
export const MontserratUnderline_300Light = require('./MontserratUnderline_300Light.ttf');
export const MontserratUnderline_400Regular = require('./MontserratUnderline_400Regular.ttf');
export const MontserratUnderline_500Medium = require('./MontserratUnderline_500Medium.ttf');
export const MontserratUnderline_600SemiBold = require('./MontserratUnderline_600SemiBold.ttf');
export const MontserratUnderline_700Bold = require('./MontserratUnderline_700Bold.ttf');
export const MontserratUnderline_800ExtraBold = require('./MontserratUnderline_800ExtraBold.ttf');
export const MontserratUnderline_900Black = require('./MontserratUnderline_900Black.ttf');
export const MontserratUnderline_100Thin_Italic = require('./MontserratUnderline_100Thin_Italic.ttf');
export const MontserratUnderline_200ExtraLight_Italic = require('./MontserratUnderline_200ExtraLight_Italic.ttf');
export const MontserratUnderline_300Light_Italic = require('./MontserratUnderline_300Light_Italic.ttf');
export const MontserratUnderline_400Regular_Italic = require('./MontserratUnderline_400Regular_Italic.ttf');
export const MontserratUnderline_500Medium_Italic = require('./MontserratUnderline_500Medium_Italic.ttf');
export const MontserratUnderline_600SemiBold_Italic = require('./MontserratUnderline_600SemiBold_Italic.ttf');
export const MontserratUnderline_700Bold_Italic = require('./MontserratUnderline_700Bold_Italic.ttf');
export const MontserratUnderline_800ExtraBold_Italic = require('./MontserratUnderline_800ExtraBold_Italic.ttf');
export const MontserratUnderline_900Black_Italic = require('./MontserratUnderline_900Black_Italic.ttf');
