/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const PublicSans_Thin100 = require('./bbeb9408fbfe9d5d9ce8fbafbfc03c6b6cdf568002d0617c5ba2e7a7ed4e2927.ttf');
export const PublicSans_ExtraLight200 = require('./c5315eae10703301b7f62e88a7de796fcf6d0e22ce0484906b2a75717045d602.ttf');
export const PublicSans_Light300 = require('./c24444db34cbde1fe26eee9e01a5aeecaa2d5d04d760b016effb1efaaeca1eab.ttf');
export const PublicSans_Regular400 = require('./a43ba20728262f80018c0f9cb41348b11a7a0f7ce4cec9524908f09a1ba9fc10.ttf');
export const PublicSans_Medium500 = require('./3bd3b338d1c2daf799f2856f74a39cee09cfc8dd65a08a77dae77e3fdcee5516.ttf');
export const PublicSans_SemiBold600 = require('./1ba049c8f5505f644eeedde917f31244fbce5797f1daa0bc6ad7dee626cdd493.ttf');
export const PublicSans_Bold700 = require('./b64cde6ef854e50377acd226084a3b56da54c708c4b6b56b0e6efdbd6725e2eb.ttf');
export const PublicSans_ExtraBold800 = require('./a88f82d3a4c9ff1ef0ddd06d1f62a10636942fb2461837a8555c5a0c6c362c84.ttf');
export const PublicSans_Black900 = require('./d59239c8e796e666d395620e22b7a4456496e2593b03448fca6ea8d8fc7697df.ttf');
export const PublicSans_Thin100_Italic = require('./b7e9ab1ba3ba765f5775306a4f4f66df2fc253782bdca66c44b36e09b4a65ced.ttf');
export const PublicSans_ExtraLight200_Italic = require('./ce8d4637dcc7693ff3984ca3de2859af73e35a18142f87dff9fb8c3e2f9e8fa3.ttf');
export const PublicSans_Light300_Italic = require('./1c6bac423bb2503db975062139990578c28e1b744fdf169b762f0ae69e4f5ad2.ttf');
export const PublicSans_Regular400_Italic = require('./ed1d4975a041ddce0d086e9b30feb0d85236d1e95edeed6848841f480af24a49.ttf');
export const PublicSans_Medium500_Italic = require('./a66352215ff1f71f3e0c04d07175608a1992529cf83d389cea2e601a72d4e90f.ttf');
export const PublicSans_SemiBold600_Italic = require('./b2bdd1391e967996ae11ed929fa55e3811b4928bcdd356295d10ae67cef03949.ttf');
export const PublicSans_Bold700_Italic = require('./056bab577fca8b802ca1629b53e48d0b66c5e0d7568553c4c85bc0107d87c865.ttf');
export const PublicSans_ExtraBold800_Italic = require('./9e40fa8d8ef6e8979ff49e3f9220489c0961ca308a318f3400b176a6594877e9.ttf');
export const PublicSans_Black900_Italic = require('./0b536907db7c2710ae92a77a16a1a413f3527e60b0fcc442d4f74513b6249e69.ttf');
