// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const BIZUDPMincho_400Regular = require('./BIZUDPMincho_400Regular.ttf');
export const BIZUDPMincho_700Bold = require('./BIZUDPMincho_700Bold.ttf');
