// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const BIZUDPMincho_400Regular = require('./400Regular/BIZUDPMincho_400Regular.ttf');
export const BIZUDPMincho_700Bold = require('./700Bold/BIZUDPMincho_700Bold.ttf');
