// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const AveriaSerifLibre_300Light = require('./AveriaSerifLibre_300Light.ttf');
