/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const PTMono_Regular400 = require('./76d11b0f53258fdd742b27fc7e194046840c2fc0cafe1246aa0c27718a5f031a.ttf');
