// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const TikTokSans_300Light = require('./300Light/TikTokSans_300Light.ttf');
export const TikTokSans_400Regular = require('./400Regular/TikTokSans_400Regular.ttf');
export const TikTokSans_500Medium = require('./500Medium/TikTokSans_500Medium.ttf');
export const TikTokSans_600SemiBold = require('./600SemiBold/TikTokSans_600SemiBold.ttf');
export const TikTokSans_700Bold = require('./700Bold/TikTokSans_700Bold.ttf');
export const TikTokSans_800ExtraBold = require('./800ExtraBold/TikTokSans_800ExtraBold.ttf');
export const TikTokSans_900Black = require('./900Black/TikTokSans_900Black.ttf');
