/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const NotoSansJP_100Thin: number;
export const NotoSansJP_300Light: number;
export const NotoSansJP_400Regular: number;
export const NotoSansJP_500Medium: number;
export const NotoSansJP_700Bold: number;
export const NotoSansJP_900Black: number;
