// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const OldStandardTT_700Bold = require('./OldStandardTT_700Bold.ttf');
