// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const SairaStencil_600SemiBold_Italic = require('./SairaStencil_600SemiBold_Italic.ttf');
