/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Belgrano_Regular400 = require('./4b66b889e699bfe12ea9cc04621e48eed308f79ef2955cd4f20d0e7ddbcbaeab.ttf');
