/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Oswald_ExtraLight200: number;
export const Oswald_Light300: number;
export const Oswald_Regular400: number;
export const Oswald_Medium500: number;
export const Oswald_SemiBold600: number;
export const Oswald_Bold700: number;
