// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Truculenta_600SemiBold = require('./Truculenta_600SemiBold.ttf');
