/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metdata__: Any;
export const Manuale_400Regular: number;
export const Manuale_500Medium: number;
export const Manuale_600SemiBold: number;
export const Manuale_700Bold: number;
export const Manuale_400Regular_Italic: number;
export const Manuale_500Medium_Italic: number;
export const Manuale_600SemiBold_Italic: number;
export const Manuale_700Bold_Italic: number;
