/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const IBMPlexSansThai_100Thin: number;
export const IBMPlexSansThai_200ExtraLight: number;
export const IBMPlexSansThai_300Light: number;
export const IBMPlexSansThai_400Regular: number;
export const IBMPlexSansThai_500Medium: number;
export const IBMPlexSansThai_600SemiBold: number;
export const IBMPlexSansThai_700Bold: number;
