// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Sarala_400Regular = require('./400Regular/Sarala_400Regular.ttf');
export const Sarala_700Bold = require('./700Bold/Sarala_700Bold.ttf');
