// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const FinlandicaHeadline_300Light = require('./FinlandicaHeadline_300Light.ttf');
