// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSerifYezidi_700Bold = require('./NotoSerifYezidi_700Bold.ttf');
