// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansHanifiRohingya_700Bold = require('./NotoSansHanifiRohingya_700Bold.ttf');
