// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const LisuBosa_300Light_Italic = require('./LisuBosa_300Light_Italic.ttf');
