// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSerifBengali_300Light = require('./NotoSerifBengali_300Light.ttf');
