/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metdata__: Any;
export const Trochut_400Regular: number;
export const Trochut_400Regular_Italic: number;
export const Trochut_700Bold: number;
