/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Prociono_Regular400 = require('./61f885124a2a2bbcb15f757f4ac96bf9509c0c1869f1efaa3c4cc6ce99d01f16.ttf');
