// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Trispace_800ExtraBold = require('./Trispace_800ExtraBold.ttf');
