/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const SairaSemiCondensed_600SemiBold = require('./SairaSemiCondensed_600SemiBold.ttf');
