/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const Fredoka_300Light = require('./Fredoka_300Light.ttf');
export const Fredoka_400Regular = require('./Fredoka_400Regular.ttf');
export const Fredoka_500Medium = require('./Fredoka_500Medium.ttf');
export const Fredoka_600SemiBold = require('./Fredoka_600SemiBold.ttf');
export const Fredoka_700Bold = require('./Fredoka_700Bold.ttf');
