/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const Fredoka_300Light: number;
export const Fredoka_400Regular: number;
export const Fredoka_500Medium: number;
export const Fredoka_600SemiBold: number;
export const Fredoka_700Bold: number;
