/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const EduTASBeginner_400Regular: number;
export const EduTASBeginner_500Medium: number;
export const EduTASBeginner_600SemiBold: number;
export const EduTASBeginner_700Bold: number;
