/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const NotoSerifGujarati_400Regular = require('./NotoSerifGujarati_400Regular.ttf');
