// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const Ruda_400Regular: number;
export const Ruda_500Medium: number;
export const Ruda_600SemiBold: number;
export const Ruda_700Bold: number;
export const Ruda_800ExtraBold: number;
export const Ruda_900Black: number;
