// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const VesperLibre_400Regular = require('./VesperLibre_400Regular.ttf');
export const VesperLibre_500Medium = require('./VesperLibre_500Medium.ttf');
export const VesperLibre_700Bold = require('./VesperLibre_700Bold.ttf');
export const VesperLibre_900Black = require('./VesperLibre_900Black.ttf');
