/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const PlaywriteNL_100Thin: number;
export const PlaywriteNL_200ExtraLight: number;
export const PlaywriteNL_300Light: number;
export const PlaywriteNL_400Regular: number;
