// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const PlaywriteNL_100Thin: number;
export const PlaywriteNL_200ExtraLight: number;
export const PlaywriteNL_300Light: number;
export const PlaywriteNL_400Regular: number;
