// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const BitcountSingle_500Medium = require('./BitcountSingle_500Medium.ttf');
