// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const DaiBannaSIL_400Regular_Italic = require('./DaiBannaSIL_400Regular_Italic.ttf');
