// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const PragatiNarrow_400Regular = require('./PragatiNarrow_400Regular.ttf');
export const PragatiNarrow_700Bold = require('./PragatiNarrow_700Bold.ttf');
