/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const PragatiNarrow_Regular400: number;
export const PragatiNarrow_Bold700: number;
