/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Ranchers_Regular400 = require('./ee03833b1756509c106b58261df85478f7bd82ff2fd7ca6b4d5890de33cae655.ttf');
