// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const AlegreyaSC_400Regular: number;
export const AlegreyaSC_400Regular_Italic: number;
export const AlegreyaSC_500Medium: number;
export const AlegreyaSC_500Medium_Italic: number;
export const AlegreyaSC_700Bold: number;
export const AlegreyaSC_700Bold_Italic: number;
export const AlegreyaSC_800ExtraBold: number;
export const AlegreyaSC_800ExtraBold_Italic: number;
export const AlegreyaSC_900Black: number;
export const AlegreyaSC_900Black_Italic: number;
