// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const MartelSans_800ExtraBold = require('./MartelSans_800ExtraBold.ttf');
