// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const PlaywriteFRModerne_100Thin: number;
export const PlaywriteFRModerne_200ExtraLight: number;
export const PlaywriteFRModerne_300Light: number;
export const PlaywriteFRModerne_400Regular: number;
