// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const IBMPlexSansHebrew_100Thin = require('./100Thin/IBMPlexSansHebrew_100Thin.ttf');
export const IBMPlexSansHebrew_200ExtraLight = require('./200ExtraLight/IBMPlexSansHebrew_200ExtraLight.ttf');
export const IBMPlexSansHebrew_300Light = require('./300Light/IBMPlexSansHebrew_300Light.ttf');
export const IBMPlexSansHebrew_400Regular = require('./400Regular/IBMPlexSansHebrew_400Regular.ttf');
export const IBMPlexSansHebrew_500Medium = require('./500Medium/IBMPlexSansHebrew_500Medium.ttf');
export const IBMPlexSansHebrew_600SemiBold = require('./600SemiBold/IBMPlexSansHebrew_600SemiBold.ttf');
export const IBMPlexSansHebrew_700Bold = require('./700Bold/IBMPlexSansHebrew_700Bold.ttf');
