/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metdata__: Any;
export const EncodeSansSemiCondensed_100Thin: number;
export const EncodeSansSemiCondensed_200ExtraLight: number;
export const EncodeSansSemiCondensed_300Light: number;
export const EncodeSansSemiCondensed_400Regular: number;
export const EncodeSansSemiCondensed_500Medium: number;
export const EncodeSansSemiCondensed_600SemiBold: number;
export const EncodeSansSemiCondensed_700Bold: number;
export const EncodeSansSemiCondensed_800ExtraBold: number;
export const EncodeSansSemiCondensed_900Black: number;
