// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const IBMPlexSansDevanagari_700Bold = require('./IBMPlexSansDevanagari_700Bold.ttf');
