/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const IBMPlexSansDevanagari_700Bold = require('./IBMPlexSansDevanagari_700Bold.ttf');
