// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const BalooPaaji2_400Regular = require('./BalooPaaji2_400Regular.ttf');
