/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const EncodeSansCondensed_400Regular = require('./EncodeSansCondensed_400Regular.ttf');
