/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const AlegreyaSansSC_100Thin = require('./AlegreyaSansSC_100Thin.ttf');
export const AlegreyaSansSC_100Thin_Italic = require('./AlegreyaSansSC_100Thin_Italic.ttf');
export const AlegreyaSansSC_300Light = require('./AlegreyaSansSC_300Light.ttf');
export const AlegreyaSansSC_300Light_Italic = require('./AlegreyaSansSC_300Light_Italic.ttf');
export const AlegreyaSansSC_400Regular = require('./AlegreyaSansSC_400Regular.ttf');
export const AlegreyaSansSC_400Regular_Italic = require('./AlegreyaSansSC_400Regular_Italic.ttf');
export const AlegreyaSansSC_500Medium = require('./AlegreyaSansSC_500Medium.ttf');
export const AlegreyaSansSC_500Medium_Italic = require('./AlegreyaSansSC_500Medium_Italic.ttf');
export const AlegreyaSansSC_700Bold = require('./AlegreyaSansSC_700Bold.ttf');
export const AlegreyaSansSC_700Bold_Italic = require('./AlegreyaSansSC_700Bold_Italic.ttf');
export const AlegreyaSansSC_800ExtraBold = require('./AlegreyaSansSC_800ExtraBold.ttf');
export const AlegreyaSansSC_800ExtraBold_Italic = require('./AlegreyaSansSC_800ExtraBold_Italic.ttf');
export const AlegreyaSansSC_900Black = require('./AlegreyaSansSC_900Black.ttf');
export const AlegreyaSansSC_900Black_Italic = require('./AlegreyaSansSC_900Black_Italic.ttf');
