// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const TitilliumWeb_200ExtraLight: number;
export const TitilliumWeb_200ExtraLight_Italic: number;
export const TitilliumWeb_300Light: number;
export const TitilliumWeb_300Light_Italic: number;
export const TitilliumWeb_400Regular: number;
export const TitilliumWeb_400Regular_Italic: number;
export const TitilliumWeb_600SemiBold: number;
export const TitilliumWeb_600SemiBold_Italic: number;
export const TitilliumWeb_700Bold: number;
export const TitilliumWeb_700Bold_Italic: number;
export const TitilliumWeb_900Black: number;
