// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const DMMono_500Medium_Italic = require('./DMMono_500Medium_Italic.ttf');
