// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export const __metadata__: any;
export const Idiqlat_200ExtraLight: number;
export const Idiqlat_300Light: number;
export const Idiqlat_400Regular: number;
