/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const FiraSansExtraCondensed_800ExtraBold = require('./FiraSansExtraCondensed_800ExtraBold.ttf');
