// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Sirivennela_400Regular = require('./Sirivennela_400Regular.ttf');
