// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const NotoSansBassaVah_400Regular = require('./NotoSansBassaVah_400Regular.ttf');
export const NotoSansBassaVah_500Medium = require('./NotoSansBassaVah_500Medium.ttf');
export const NotoSansBassaVah_600SemiBold = require('./NotoSansBassaVah_600SemiBold.ttf');
export const NotoSansBassaVah_700Bold = require('./NotoSansBassaVah_700Bold.ttf');
