// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const BigShoulders_100Thin: number;
export const BigShoulders_200ExtraLight: number;
export const BigShoulders_300Light: number;
export const BigShoulders_400Regular: number;
export const BigShoulders_500Medium: number;
export const BigShoulders_600SemiBold: number;
export const BigShoulders_700Bold: number;
export const BigShoulders_800ExtraBold: number;
export const BigShoulders_900Black: number;
