// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Unkempt_400Regular = require('./Unkempt_400Regular.ttf');
export const Unkempt_700Bold = require('./Unkempt_700Bold.ttf');
