/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const ADLaMDisplay_400Regular = require('./ADLaMDisplay_400Regular.ttf');
