/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const PlaywriteNGModernGuides_400Regular = require('./PlaywriteNGModernGuides_400Regular.ttf');
