// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaywriteNGModernGuides_400Regular = require('./PlaywriteNGModernGuides_400Regular.ttf');
