/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const MeieScript_Regular400 = require('./aefe23d9bdd07bdf03debfd770abb2ea2f50634e5b0803593abf3eb0b9a784c4.ttf');
