// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const LondrinaOutline_400Regular = require('./LondrinaOutline_400Regular.ttf');
