/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const IBMPlexSansArabic_100Thin = require('./IBMPlexSansArabic_100Thin.ttf');
export const IBMPlexSansArabic_200ExtraLight = require('./IBMPlexSansArabic_200ExtraLight.ttf');
export const IBMPlexSansArabic_300Light = require('./IBMPlexSansArabic_300Light.ttf');
export const IBMPlexSansArabic_400Regular = require('./IBMPlexSansArabic_400Regular.ttf');
export const IBMPlexSansArabic_500Medium = require('./IBMPlexSansArabic_500Medium.ttf');
export const IBMPlexSansArabic_600SemiBold = require('./IBMPlexSansArabic_600SemiBold.ttf');
export const IBMPlexSansArabic_700Bold = require('./IBMPlexSansArabic_700Bold.ttf');
