/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const RubikDoodleTriangles_400Regular = require('./RubikDoodleTriangles_400Regular.ttf');
