// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansDevanagari_500Medium = require('./NotoSansDevanagari_500Medium.ttf');
