// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const ChironGoRoundTC_600SemiBold = require('./ChironGoRoundTC_600SemiBold.ttf');
