// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaywriteAUSA_300Light = require('./PlaywriteAUSA_300Light.ttf');
