// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const Neuton_200ExtraLight: number;
export const Neuton_300Light: number;
export const Neuton_400Regular: number;
export const Neuton_400Regular_Italic: number;
export const Neuton_700Bold: number;
export const Neuton_800ExtraBold: number;
