// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const RethinkSans_400Regular = require('./400Regular/RethinkSans_400Regular.ttf');
export const RethinkSans_500Medium = require('./500Medium/RethinkSans_500Medium.ttf');
export const RethinkSans_600SemiBold = require('./600SemiBold/RethinkSans_600SemiBold.ttf');
export const RethinkSans_700Bold = require('./700Bold/RethinkSans_700Bold.ttf');
export const RethinkSans_800ExtraBold = require('./800ExtraBold/RethinkSans_800ExtraBold.ttf');
export const RethinkSans_400Regular_Italic = require('./400Regular_Italic/RethinkSans_400Regular_Italic.ttf');
export const RethinkSans_500Medium_Italic = require('./500Medium_Italic/RethinkSans_500Medium_Italic.ttf');
export const RethinkSans_600SemiBold_Italic = require('./600SemiBold_Italic/RethinkSans_600SemiBold_Italic.ttf');
export const RethinkSans_700Bold_Italic = require('./700Bold_Italic/RethinkSans_700Bold_Italic.ttf');
export const RethinkSans_800ExtraBold_Italic = require('./800ExtraBold_Italic/RethinkSans_800ExtraBold_Italic.ttf');
