// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const MPLUSCodeLatin_300Light = require('./MPLUSCodeLatin_300Light.ttf');
