// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Moderustic_300Light = require('./Moderustic_300Light.ttf');
export const Moderustic_400Regular = require('./Moderustic_400Regular.ttf');
export const Moderustic_500Medium = require('./Moderustic_500Medium.ttf');
export const Moderustic_600SemiBold = require('./Moderustic_600SemiBold.ttf');
export const Moderustic_700Bold = require('./Moderustic_700Bold.ttf');
export const Moderustic_800ExtraBold = require('./Moderustic_800ExtraBold.ttf');
