/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Englebert_Regular400 = require('./5ceab7490f339b83c9f46a3baf7274203de3e060802b185fbd65c2aa9f5ec76c.ttf');
