/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Chango_Regular400 = require('./66d5dcae03b7a0d59f38640d05bb920cc6d3b4e2a1cdb176628330e20ab9a6ca.ttf');
