// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const Laila_300Light: number;
export const Laila_400Regular: number;
export const Laila_500Medium: number;
export const Laila_600SemiBold: number;
export const Laila_700Bold: number;
