/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const Quicksand_300Light = require('./Quicksand_300Light.ttf');
export const Quicksand_400Regular = require('./Quicksand_400Regular.ttf');
export const Quicksand_500Medium = require('./Quicksand_500Medium.ttf');
export const Quicksand_600SemiBold = require('./Quicksand_600SemiBold.ttf');
export const Quicksand_700Bold = require('./Quicksand_700Bold.ttf');
