/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Oxanium_ExtraLight200: number;
export const Oxanium_Light300: number;
export const Oxanium_Regular400: number;
export const Oxanium_Medium500: number;
export const Oxanium_SemiBold600: number;
export const Oxanium_Bold700: number;
export const Oxanium_ExtraBold800: number;
