// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const Cinzel_400Regular: number;
export const Cinzel_500Medium: number;
export const Cinzel_600SemiBold: number;
export const Cinzel_700Bold: number;
export const Cinzel_800ExtraBold: number;
export const Cinzel_900Black: number;
