/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metdata__: Any;
export const Cinzel_400Regular: number;
export const Cinzel_700Bold: number;
export const Cinzel_900Black: number;
