// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Ranga_400Regular = require('./400Regular/Ranga_400Regular.ttf');
export const Ranga_700Bold = require('./700Bold/Ranga_700Bold.ttf');
