/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const NotoSansAdlamUnjoined_700Bold = require('./NotoSansAdlamUnjoined_700Bold.ttf');
