// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const JosefinSans_200ExtraLight = require('./JosefinSans_200ExtraLight.ttf');
