/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Mandali_Regular400 = require('./bf8fcb272aa15d749c2b5a6660a64af1b0014a47b0fe3ed3394e761ce7637f1d.ttf');
