/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export const __fontFamilyName__ = 'Lobster';
export const __fontFamilyVersion__ = 18;

export const Lobster_Regular400 = require('./ce455bfe5094ab723cf0b59871eb112f9f9acbe6d58811590b3d22a7236fa435.ttf');
