// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Glory_100Thin = require('./Glory_100Thin.ttf');
export const Glory_200ExtraLight = require('./Glory_200ExtraLight.ttf');
export const Glory_300Light = require('./Glory_300Light.ttf');
export const Glory_400Regular = require('./Glory_400Regular.ttf');
export const Glory_500Medium = require('./Glory_500Medium.ttf');
export const Glory_600SemiBold = require('./Glory_600SemiBold.ttf');
export const Glory_700Bold = require('./Glory_700Bold.ttf');
export const Glory_800ExtraBold = require('./Glory_800ExtraBold.ttf');
export const Glory_100Thin_Italic = require('./Glory_100Thin_Italic.ttf');
export const Glory_200ExtraLight_Italic = require('./Glory_200ExtraLight_Italic.ttf');
export const Glory_300Light_Italic = require('./Glory_300Light_Italic.ttf');
export const Glory_400Regular_Italic = require('./Glory_400Regular_Italic.ttf');
export const Glory_500Medium_Italic = require('./Glory_500Medium_Italic.ttf');
export const Glory_600SemiBold_Italic = require('./Glory_600SemiBold_Italic.ttf');
export const Glory_700Bold_Italic = require('./Glory_700Bold_Italic.ttf');
export const Glory_800ExtraBold_Italic = require('./Glory_800ExtraBold_Italic.ttf');
