// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const Glory_100Thin: number;
export const Glory_200ExtraLight: number;
export const Glory_300Light: number;
export const Glory_400Regular: number;
export const Glory_500Medium: number;
export const Glory_600SemiBold: number;
export const Glory_700Bold: number;
export const Glory_800ExtraBold: number;
export const Glory_100Thin_Italic: number;
export const Glory_200ExtraLight_Italic: number;
export const Glory_300Light_Italic: number;
export const Glory_400Regular_Italic: number;
export const Glory_500Medium_Italic: number;
export const Glory_600SemiBold_Italic: number;
export const Glory_700Bold_Italic: number;
export const Glory_800ExtraBold_Italic: number;
