// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const FunnelSans_300Light = require('./300Light/FunnelSans_300Light.ttf');
export const FunnelSans_400Regular = require('./400Regular/FunnelSans_400Regular.ttf');
export const FunnelSans_500Medium = require('./500Medium/FunnelSans_500Medium.ttf');
export const FunnelSans_600SemiBold = require('./600SemiBold/FunnelSans_600SemiBold.ttf');
export const FunnelSans_700Bold = require('./700Bold/FunnelSans_700Bold.ttf');
export const FunnelSans_800ExtraBold = require('./800ExtraBold/FunnelSans_800ExtraBold.ttf');
export const FunnelSans_300Light_Italic = require('./300Light_Italic/FunnelSans_300Light_Italic.ttf');
export const FunnelSans_400Regular_Italic = require('./400Regular_Italic/FunnelSans_400Regular_Italic.ttf');
export const FunnelSans_500Medium_Italic = require('./500Medium_Italic/FunnelSans_500Medium_Italic.ttf');
export const FunnelSans_600SemiBold_Italic = require('./600SemiBold_Italic/FunnelSans_600SemiBold_Italic.ttf');
export const FunnelSans_700Bold_Italic = require('./700Bold_Italic/FunnelSans_700Bold_Italic.ttf');
export const FunnelSans_800ExtraBold_Italic = require('./800ExtraBold_Italic/FunnelSans_800ExtraBold_Italic.ttf');
