// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const MPLUSCodeLatin_100Thin = require('./100Thin/MPLUSCodeLatin_100Thin.ttf');
export const MPLUSCodeLatin_200ExtraLight = require('./200ExtraLight/MPLUSCodeLatin_200ExtraLight.ttf');
export const MPLUSCodeLatin_300Light = require('./300Light/MPLUSCodeLatin_300Light.ttf');
export const MPLUSCodeLatin_400Regular = require('./400Regular/MPLUSCodeLatin_400Regular.ttf');
export const MPLUSCodeLatin_500Medium = require('./500Medium/MPLUSCodeLatin_500Medium.ttf');
export const MPLUSCodeLatin_600SemiBold = require('./600SemiBold/MPLUSCodeLatin_600SemiBold.ttf');
export const MPLUSCodeLatin_700Bold = require('./700Bold/MPLUSCodeLatin_700Bold.ttf');
