// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const NotoSerifTC_200ExtraLight: number;
export const NotoSerifTC_300Light: number;
export const NotoSerifTC_400Regular: number;
export const NotoSerifTC_500Medium: number;
export const NotoSerifTC_600SemiBold: number;
export const NotoSerifTC_700Bold: number;
export const NotoSerifTC_800ExtraBold: number;
export const NotoSerifTC_900Black: number;
