// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansKhojki_400Regular = require('./NotoSansKhojki_400Regular.ttf');
