/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metdata__: Any;
export const OpenSans_300Light: number;
export const OpenSans_300Light_Italic: number;
export const OpenSans_400Regular: number;
export const OpenSans_400Regular_Italic: number;
export const OpenSans_600SemiBold: number;
export const OpenSans_600SemiBold_Italic: number;
export const OpenSans_700Bold: number;
export const OpenSans_700Bold_Italic: number;
export const OpenSans_800ExtraBold: number;
export const OpenSans_800ExtraBold_Italic: number;
