// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const NotoSerif_100Thin = require('./100Thin/NotoSerif_100Thin.ttf');
export const NotoSerif_200ExtraLight = require('./200ExtraLight/NotoSerif_200ExtraLight.ttf');
export const NotoSerif_300Light = require('./300Light/NotoSerif_300Light.ttf');
export const NotoSerif_400Regular = require('./400Regular/NotoSerif_400Regular.ttf');
export const NotoSerif_500Medium = require('./500Medium/NotoSerif_500Medium.ttf');
export const NotoSerif_600SemiBold = require('./600SemiBold/NotoSerif_600SemiBold.ttf');
export const NotoSerif_700Bold = require('./700Bold/NotoSerif_700Bold.ttf');
export const NotoSerif_800ExtraBold = require('./800ExtraBold/NotoSerif_800ExtraBold.ttf');
export const NotoSerif_900Black = require('./900Black/NotoSerif_900Black.ttf');
export const NotoSerif_100Thin_Italic = require('./100Thin_Italic/NotoSerif_100Thin_Italic.ttf');
export const NotoSerif_200ExtraLight_Italic = require('./200ExtraLight_Italic/NotoSerif_200ExtraLight_Italic.ttf');
export const NotoSerif_300Light_Italic = require('./300Light_Italic/NotoSerif_300Light_Italic.ttf');
export const NotoSerif_400Regular_Italic = require('./400Regular_Italic/NotoSerif_400Regular_Italic.ttf');
export const NotoSerif_500Medium_Italic = require('./500Medium_Italic/NotoSerif_500Medium_Italic.ttf');
export const NotoSerif_600SemiBold_Italic = require('./600SemiBold_Italic/NotoSerif_600SemiBold_Italic.ttf');
export const NotoSerif_700Bold_Italic = require('./700Bold_Italic/NotoSerif_700Bold_Italic.ttf');
export const NotoSerif_800ExtraBold_Italic = require('./800ExtraBold_Italic/NotoSerif_800ExtraBold_Italic.ttf');
export const NotoSerif_900Black_Italic = require('./900Black_Italic/NotoSerif_900Black_Italic.ttf');
