/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metdata__: Any;
export const Newsreader_200ExtraLight: number;
export const Newsreader_300Light: number;
export const Newsreader_400Regular: number;
export const Newsreader_500Medium: number;
export const Newsreader_600SemiBold: number;
export const Newsreader_700Bold: number;
export const Newsreader_800ExtraBold: number;
export const Newsreader_200ExtraLight_Italic: number;
export const Newsreader_300Light_Italic: number;
export const Newsreader_400Regular_Italic: number;
export const Newsreader_500Medium_Italic: number;
export const Newsreader_600SemiBold_Italic: number;
export const Newsreader_700Bold_Italic: number;
export const Newsreader_800ExtraBold_Italic: number;
