// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansSinhala_700Bold = require('./NotoSansSinhala_700Bold.ttf');
