/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const Murecho_100Thin = require('./Murecho_100Thin.ttf');
export const Murecho_200ExtraLight = require('./Murecho_200ExtraLight.ttf');
export const Murecho_300Light = require('./Murecho_300Light.ttf');
export const Murecho_400Regular = require('./Murecho_400Regular.ttf');
export const Murecho_500Medium = require('./Murecho_500Medium.ttf');
export const Murecho_600SemiBold = require('./Murecho_600SemiBold.ttf');
export const Murecho_700Bold = require('./Murecho_700Bold.ttf');
export const Murecho_800ExtraBold = require('./Murecho_800ExtraBold.ttf');
export const Murecho_900Black = require('./Murecho_900Black.ttf');
