/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteDKUloopet_100Thin = require('./PlaywriteDKUloopet_100Thin.ttf');
export const PlaywriteDKUloopet_200ExtraLight = require('./PlaywriteDKUloopet_200ExtraLight.ttf');
export const PlaywriteDKUloopet_300Light = require('./PlaywriteDKUloopet_300Light.ttf');
export const PlaywriteDKUloopet_400Regular = require('./PlaywriteDKUloopet_400Regular.ttf');
