// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const PlaywriteDKUloopet_100Thin = require('./PlaywriteDKUloopet_100Thin.ttf');
export const PlaywriteDKUloopet_200ExtraLight = require('./PlaywriteDKUloopet_200ExtraLight.ttf');
export const PlaywriteDKUloopet_300Light = require('./PlaywriteDKUloopet_300Light.ttf');
export const PlaywriteDKUloopet_400Regular = require('./PlaywriteDKUloopet_400Regular.ttf');
