// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Nunito_300Light_Italic = require('./Nunito_300Light_Italic.ttf');
