/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export const __fontFamilyName__ = 'Crafty Girls';
export const __fontFamilyVersion__ = 5;

export const CraftyGirls_Regular400 = require('./dc184885668047ca66db5a530c0462f1b1ef2f2d6867b7f938c59dbc9d282de2.ttf');
