/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const FiraSansExtraCondensed_800ExtraBold_Italic = require('./FiraSansExtraCondensed_800ExtraBold_Italic.ttf');
