// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const EduVICWANTBeginner_700Bold = require('./EduVICWANTBeginner_700Bold.ttf');
