/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const Pridi_200ExtraLight: number;
export const Pridi_300Light: number;
export const Pridi_400Regular: number;
export const Pridi_500Medium: number;
export const Pridi_600SemiBold: number;
export const Pridi_700Bold: number;
