// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Pridi_200ExtraLight = require('./Pridi_200ExtraLight.ttf');
export const Pridi_300Light = require('./Pridi_300Light.ttf');
export const Pridi_400Regular = require('./Pridi_400Regular.ttf');
export const Pridi_500Medium = require('./Pridi_500Medium.ttf');
export const Pridi_600SemiBold = require('./Pridi_600SemiBold.ttf');
export const Pridi_700Bold = require('./Pridi_700Bold.ttf');
