// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const Pridi_200ExtraLight: number;
export const Pridi_300Light: number;
export const Pridi_400Regular: number;
export const Pridi_500Medium: number;
export const Pridi_600SemiBold: number;
export const Pridi_700Bold: number;
