/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const LibreCaslonDisplay_Regular400 = require('./c30a6ef1396c17e855a72b95f2848b064fceedce5de3bc974c99f5a75c48148f.ttf');
