/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const RacingSansOne_Regular400 = require('./d832218eb9f68c818398e21dff506b95b27cf9a0830a3866a204eb2d2044027a.ttf');
