/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const JetBrainsMono_200ExtraLight_Italic = require('./JetBrainsMono_200ExtraLight_Italic.ttf');
