// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const FinlandicaText_100Thin = require('./FinlandicaText_100Thin.ttf');
