// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const CormorantGaramond_400Regular = require('./CormorantGaramond_400Regular.ttf');
