// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaypenSansHebrew_300Light = require('./PlaypenSansHebrew_300Light.ttf');
