// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const DavidLibre_400Regular = require('./400Regular/DavidLibre_400Regular.ttf');
export const DavidLibre_500Medium = require('./500Medium/DavidLibre_500Medium.ttf');
export const DavidLibre_700Bold = require('./700Bold/DavidLibre_700Bold.ttf');
