// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const Sora_100Thin: number;
export const Sora_200ExtraLight: number;
export const Sora_300Light: number;
export const Sora_400Regular: number;
export const Sora_500Medium: number;
export const Sora_600SemiBold: number;
export const Sora_700Bold: number;
export const Sora_800ExtraBold: number;
