/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Ribeye_Regular400 = require('./9fe858f86a4e9a56b2a520c8f615ee7dd682f4a2fed5b8033405258755e1105e.ttf');
