// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaywriteFRTrad_200ExtraLight = require('./PlaywriteFRTrad_200ExtraLight.ttf');
