// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const BalsamiqSans_400Regular: number;
export const BalsamiqSans_400Regular_Italic: number;
export const BalsamiqSans_700Bold: number;
export const BalsamiqSans_700Bold_Italic: number;
