/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const NotoSansGurmukhi_100Thin: number;
export const NotoSansGurmukhi_200ExtraLight: number;
export const NotoSansGurmukhi_300Light: number;
export const NotoSansGurmukhi_400Regular: number;
export const NotoSansGurmukhi_500Medium: number;
export const NotoSansGurmukhi_600SemiBold: number;
export const NotoSansGurmukhi_700Bold: number;
export const NotoSansGurmukhi_800ExtraBold: number;
export const NotoSansGurmukhi_900Black: number;
