// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const MPLUSRounded1c_100Thin = require('./MPLUSRounded1c_100Thin.ttf');
export const MPLUSRounded1c_300Light = require('./MPLUSRounded1c_300Light.ttf');
export const MPLUSRounded1c_400Regular = require('./MPLUSRounded1c_400Regular.ttf');
export const MPLUSRounded1c_500Medium = require('./MPLUSRounded1c_500Medium.ttf');
export const MPLUSRounded1c_700Bold = require('./MPLUSRounded1c_700Bold.ttf');
export const MPLUSRounded1c_800ExtraBold = require('./MPLUSRounded1c_800ExtraBold.ttf');
export const MPLUSRounded1c_900Black = require('./MPLUSRounded1c_900Black.ttf');
