// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaywriteDEVA_300Light = require('./PlaywriteDEVA_300Light.ttf');
