// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const KarlaTamilInclined_400Regular = require('./KarlaTamilInclined_400Regular.ttf');
export const KarlaTamilInclined_700Bold = require('./KarlaTamilInclined_700Bold.ttf');
