/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const Dongle_300Light = require('./Dongle_300Light.ttf');
export const Dongle_400Regular = require('./Dongle_400Regular.ttf');
export const Dongle_700Bold = require('./Dongle_700Bold.ttf');
