/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const NotoSansGujarati_800ExtraBold = require('./NotoSansGujarati_800ExtraBold.ttf');
