// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const Gantari_200ExtraLight = require('./Gantari_200ExtraLight.ttf');
