// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NunitoSans_400Regular = require('./NunitoSans_400Regular.ttf');
