/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Elsie_Regular400 = require('./bc0b83b9cbe3b25809361a2f4e495bdc9f10756f669072da3bc89689a42c8845.ttf');
export const Elsie_Black900 = require('./9aca439d3b5c4abdf62ae59fb1a643c185345724ebdb002f388d25d7926f8f98.ttf');
