// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const RedactedScript_400Regular = require('./RedactedScript_400Regular.ttf');
