// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaywriteNL_400Regular = require('./PlaywriteNL_400Regular.ttf');
