// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSerifVithkuqi_500Medium = require('./NotoSerifVithkuqi_500Medium.ttf');
