// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const ReemKufiFun_600SemiBold = require('./ReemKufiFun_600SemiBold.ttf');
