// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export const __metadata__: any;
export const Kedebideri_400Regular: number;
export const Kedebideri_500Medium: number;
export const Kedebideri_600SemiBold: number;
export const Kedebideri_700Bold: number;
export const Kedebideri_800ExtraBold: number;
export const Kedebideri_900Black: number;
