/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export { useFonts } from './useFonts';

export { default as __metadata__ } from './metadata.json';
export const Gupter_400Regular = require('./Gupter_400Regular.ttf');
export const Gupter_500Medium = require('./Gupter_500Medium.ttf');
export const Gupter_700Bold = require('./Gupter_700Bold.ttf');
