// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const IBMPlexSansArabic_600SemiBold = require('./IBMPlexSansArabic_600SemiBold.ttf');
