// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansOriya_800ExtraBold = require('./NotoSansOriya_800ExtraBold.ttf');
