/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const BalooTamma_Regular400 = require('./e8005871563cf3cfadf580fba66361b46649b342e9e1765d65405765af6e92c4.ttf');
