/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const NotoSerifGurmukhi_600SemiBold = require('./NotoSerifGurmukhi_600SemiBold.ttf');
