// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const RedditSans_200ExtraLight = require('./RedditSans_200ExtraLight.ttf');
export const RedditSans_300Light = require('./RedditSans_300Light.ttf');
export const RedditSans_400Regular = require('./RedditSans_400Regular.ttf');
export const RedditSans_500Medium = require('./RedditSans_500Medium.ttf');
export const RedditSans_600SemiBold = require('./RedditSans_600SemiBold.ttf');
export const RedditSans_700Bold = require('./RedditSans_700Bold.ttf');
export const RedditSans_800ExtraBold = require('./RedditSans_800ExtraBold.ttf');
export const RedditSans_900Black = require('./RedditSans_900Black.ttf');
export const RedditSans_200ExtraLight_Italic = require('./RedditSans_200ExtraLight_Italic.ttf');
export const RedditSans_300Light_Italic = require('./RedditSans_300Light_Italic.ttf');
export const RedditSans_400Regular_Italic = require('./RedditSans_400Regular_Italic.ttf');
export const RedditSans_500Medium_Italic = require('./RedditSans_500Medium_Italic.ttf');
export const RedditSans_600SemiBold_Italic = require('./RedditSans_600SemiBold_Italic.ttf');
export const RedditSans_700Bold_Italic = require('./RedditSans_700Bold_Italic.ttf');
export const RedditSans_800ExtraBold_Italic = require('./RedditSans_800ExtraBold_Italic.ttf');
export const RedditSans_900Black_Italic = require('./RedditSans_900Black_Italic.ttf');
