// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const EncodeSansSC_400Regular = require('./EncodeSansSC_400Regular.ttf');
