// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaywriteCZGuides_400Regular = require('./PlaywriteCZGuides_400Regular.ttf');
