/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const NotoTraditionalNushu_500Medium = require('./NotoTraditionalNushu_500Medium.ttf');
