// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const UnifrakturCook_700Bold = require('./700Bold/UnifrakturCook_700Bold.ttf');
