// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const FamiljenGrotesk_400Regular = require('./FamiljenGrotesk_400Regular.ttf');
export const FamiljenGrotesk_500Medium = require('./FamiljenGrotesk_500Medium.ttf');
export const FamiljenGrotesk_600SemiBold = require('./FamiljenGrotesk_600SemiBold.ttf');
export const FamiljenGrotesk_700Bold = require('./FamiljenGrotesk_700Bold.ttf');
export const FamiljenGrotesk_400Regular_Italic = require('./FamiljenGrotesk_400Regular_Italic.ttf');
export const FamiljenGrotesk_500Medium_Italic = require('./FamiljenGrotesk_500Medium_Italic.ttf');
export const FamiljenGrotesk_600SemiBold_Italic = require('./FamiljenGrotesk_600SemiBold_Italic.ttf');
export const FamiljenGrotesk_700Bold_Italic = require('./FamiljenGrotesk_700Bold_Italic.ttf');
