name: Check README
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  check-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            packages
            README.md
            package.json
            yarn.lock

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Generate README
        run: yarn generate-root-readme

      - name: Check for README changes
        run: |
          if [ -n "$(git status --porcelain README.md)" ]; then
            echo "README.md has been modified. Please commit the changes."
            git diff README.md
            exit 1
          fi

