// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const PlaywritePLGuides_400Regular = require('./PlaywritePLGuides_400Regular.ttf');
