// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export const NotoSansMeeteiMayek_100Thin = require('./NotoSansMeeteiMayek_100Thin.ttf');
