/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Electrolize_Regular400 = require('./c68d85c8396ce2228f3bd601b3423d838c24c546404f25a38db6c05e64a4521b.ttf');
