// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export * from './useFonts';
export { default as __metadata__ } from './metadata.json';
export const Lusitana_400Regular = require('./400Regular/Lusitana_400Regular.ttf');
export const Lusitana_700Bold = require('./700Bold/Lusitana_700Bold.ttf');
