/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Wellfleet_Regular400 = require('./9bdc76fbcd0c8aa30aa62c892008d4e6cf4a7df66502008137949866fc091693.ttf');
