/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const Arimo_Regular400: number;
export const Arimo_Regular400_Italic: number;
export const Arimo_Bold700: number;
export const Arimo_Bold700_Italic: number;
