// This file is generated by @expo-google-fonts/generator
// If you want to modify it, go to packages/generator/templates

export { useFonts } from './useFonts';
export const __metadata__: any;
export const Arimo_400Regular: number;
export const Arimo_500Medium: number;
export const Arimo_600SemiBold: number;
export const Arimo_700Bold: number;
export const Arimo_400Regular_Italic: number;
export const Arimo_500Medium_Italic: number;
export const Arimo_600SemiBold_Italic: number;
export const Arimo_700Bold_Italic: number;
